import "./ditto.css";
import Tile from "./components/tile";
import ListRow from "./components/list-row";
import Link from "next/link";
export const metadata = {
 title: "Administratie | Ahneta Advies",
 alternates: {
 canonical: "/administratie"
 },
 openGraph: {
 title: "Administratie | Ahneta Advies",
 url: "/administratie"
 },
 twitter: {
 title: "Administratie | Ahneta Advies"
 }
};
// Generated by clone-site. Do not edit by hand.
const Tile_data = [
 { text: "Lageprijsgarantie" },
 { text: "30 dagen online retourneren" },
 { text: "Standaard verzending" }
];
const ListRow_data = [
 { href: "/pricing", label: "Prijs" },
 { href: "/over-ons", label: "Over ons" },
 { href: "/contactus", label: "Contact" }
];
const Tile_meta: string[][] = [
 ["n10", "n11"],
 ["n12", "n13"],
 ["n14", "n15"]
];
const ListRow_meta: string[][] = [
 ["n48", "style-9", "style-15"],
 ["n51", "style-10", "style-16"],
 ["n54", "style-11", "style-17"]
];
const Tile_styles = [
 { className: "before:content-['']" },
 { className: "before:content-['']" },
 { className: "before:content-['']" }
];

export default function Page() {
 return (
 <>
 <main className="block grow shrink-0">
 <div className="h-full block" id="wrap">
 <div className="block">
 <section className="block relative py-6 overflow-hidden text-background bg-color-004">
 <span className="h-full block absolute top-0 inset-x-0 overflow-hidden bg-cover [background-position:50%_0px] bg-no-repeat [background-attachment:fixed] pointer-events-none max-lg:[background-attachment:initial]" style={{ backgroundImage: "url(\"/assets/cloned/images/2873c8e777c4.jpg\")" }} data-ditto-id="style-span-8" />
 {" "}
 <div className="h-full block absolute top-0 inset-x-0 overflow-hidden bg-color-004 bg-no-repeat pointer-events-none" data-ditto-id="style-div-28" />
 {" "}
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-div-33">
 <h1 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[3.875rem] font-bold leading-[4.625rem] max-md:text-4xl max-md:leading-[2.6875rem] md:max-lg:text-5xl md:max-lg:leading-[3.625rem]" data-ditto-id="style-heading-6" data-component="heading">
 Administratie
 <br className="inline" data-ditto-id="style-div-29" />
 </h1>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 </div>
 {" "}
 <div className="block" data-ditto-id="style-section-5">
 <section className="block relative py-10 bg-background" data-ditto-id="style-div-30">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-p-2">
 <p className="block mb-4" data-ditto-id="style-br-4">
 <br className="inline" data-ditto-id="style-span-20" />
 {"Al vanaf de start van de onderneming heeft Ahneta zich dienstverlenend voor het MKB geprofileerd. Het pakket aan diensten voor het MKB is in de loop der jaren steeds verder uitgebreid. "}
 <br className="inline" data-ditto-id="style-span-6" />
 <br className="inline" data-ditto-id="style-br-5" />
 Door de wijziging van wetgeving verzorgt Ahneta ook voor besloten vennootschappen (B.V.) het complete traject vanaf controle boekhouding tot opstelling van de jaarrekening en de aangifte VPB.
 <br className="inline" />
 <br className="inline" />
 {" Uiteraard kan ook de eenmanszaak of de vennootschap onder firma ("}
 <a className="inline text-color-002 cursor-pointer" data-ditto-id="style-span-5" data-component="link" href="https://v.o.f.)/">
 V.O.F.)
 </a>
 {" door Ahneta worden begeleid."}
 <br className="inline" data-ditto-id="style-u" />
 <br className="inline" data-ditto-id="style-br-10" />
 Alvorens Ahneta voor uw bedrijf werkzaamheden kan verrichten wordt er eerst met u een prijsafspraak gemaakt. In de prijsafspraak wordt helder weergegeven welke werkzaamheden Ahneta voor u zal gaan verrichten en wat de uitvoering van deze werkzaamheden u gaat kosten.
 <br className="inline" data-ditto-id="style-br-3" />
 <br className="inline" data-ditto-id="style-span-7" />
 {" Indien Ahneta voor u de complete boekhouding verzorgt wordt duidelijk aangegeven op hoeveel boekingen de prijsopgave is gebaseerd. Hierop is een met u overeengekomen marge van meer of minder boekingen van toepassing. Worden er minder boekingen verricht ontvangt u een restitutie van honorarium en indien er meer boeking verricht moeten worden wordt de meerprijs aan u extra gedeclareerd. De declaratie wordt u per maand of per kwartaal toegezonden."}
 <br className="inline" data-ditto-id="style-br-15" />
 <br className="inline" data-ditto-id="style-br-7" />
 {" "}
 <u className="inline font-bold underline" data-ditto-id="style-span-10">
 Verzorging van de complete bedrijfsboekhouding
 </u>
 <br className="inline" />
 Als u voor deze module kiest verwachten wij van u dat u één maal per maand uw boekhouding aanlevert. U dient de boekhouding wel te sorteren, de wijze waarop u dient te sorteren wordt vooraf met u doorgenomen.
 <br className="inline" />
 Deze module is interessant voor Bedrijven die of weinig tijd hebben voor boekhouding of voor Bedrijven die geen kennis hebben van boekhouding.
 <br className="inline" />
 <br className="inline" data-ditto-id="style-br-2" />
 <u className="inline font-bold underline" data-ditto-id="style-br-9">
 Controle van de door u ingevoerde boekhouding
 </u>
 <br className="inline" data-ditto-id="style-span-9" />
 Bij deze module wordt door Ahneta controle uitgevoerd op de door u ingevoerde boekhouding. Het kan zijn – bij kleinere ondernemingen – dat u de boekhouding verwerkt in een Excel-bestand of dat u gebruik maakt van een boekhoudprogramma.
 <br className="inline" data-ditto-id="style-br-8" />
 <br className="inline" data-ditto-id="style-br-18" />
 {" De controlewerkzaamheden worden gekoppeld aan de frequentie van uw aangifte voor de BTW. Heeft u maandaangifte dan controleert Ahneta per maand. Heeft u kwartaalaangifte of jaaraangifte voor de BTW dan controleert Ahneta uw boekhouding per drie maanden."}
 <br className="inline" data-ditto-id="style-span-15" />
 <br className="inline" data-ditto-id="style-br-17" />
 <u className="inline font-bold underline" data-ditto-id="style-br-12">
 Opstellen van jaarrekeningen
 </u>
 <br className="inline" data-ditto-id="style-span-13" />
 {"Voor eenmanszaken of "}
 <a className="inline text-color-002 cursor-pointer" data-ditto-id="style-br" data-component="link" href="https://v.o.f.xn--s-ihn/">
 V.O.F.’s
 </a>
 {" die kleine ondernemingen zijn of die ondernemingen zijn die geen jaarrekening nodig hebben voor geldverstrekkers, adviseren wij om geen jaarrekening samen te stellen maar hiervoor de fiscale jaarstukken te gebruiken."}
 <br className="inline" />
 <br className="inline" />
 De fiscale jaarstukken moeten toch gemaakt worden voor de aangifte Inkomstenbelasting en zijn zodanig van samenstelling dat zij u als ondernemer voldoende inzicht geven in het financiële reilen en zeilen van uw onderneming.
 <br className="inline" data-ditto-id="style-br-22" />
 <br className="inline" data-ditto-id="style-br-13" />
 Door af te zien van het opstellen van een jaarrekening en hiervoor de fiscale jaarstukken te gebruiken bespaart u als ondernemer veel geld.
 <br className="inline" data-ditto-id="style-span-22" />
 <br className="inline" data-ditto-id="style-br-21" />
 Indien uw onderneming toch een jaarrekening nodig heeft – u bent een rechtspersoon of uw onderneming heeft geldverstrekkers – die voldoet aan het wettelijke kader van de wet op de jaarrekeningen dan kan Ahneta die ook voor u samenstellen. Ook kan Ahneta in dit kader voor u het deponeren van uw jaarrekening bij de KvK verzorgen.
 <br className="inline" />
 <br className="inline" data-ditto-id="style-span-12" />
 <u className="inline font-bold underline" data-ditto-id="style-u-2">
 Verzorging van loonadministratie
 </u>
 <br className="inline" />
 Voor Bedrijven met personeel waarvoor Ahneta ook boekhoudmodules verzorgt kan Ahneta tevens de loonadministratie in eigen huis regelen.
 <br className="inline" data-ditto-id="style-br-14" />
 <br className="inline" />
 Door Ahneta wordt dan de 1edagsmelding verzorgd voor nieuw personeel en Ahneta zorgt voor berekening van het periodeloon op basis van de door u aangeleverde informatie.
 <br className="inline" data-ditto-id="style-br-16" />
 <br className="inline" data-ditto-id="style-br-6" />
 Ahneta zorgt verder voor de periodieke verzending van de loonstrook aan uw personeel inclusief de jaaropgave. De jaaropgave wordt over het algemeen tegelijk aan uw personeel toegezonden met de loonstrook over de maand december of de loonstrook over de 13e periode. Van alle loonstroken krijgt u als werkgever een kopie toegezonden.
 <br className="inline" />
 <br className="inline" data-ditto-id="style-bottom" />
 Ahneta draagt ook zorg voor de elektronische indiening van uw aangifte voor de loonheffing en de afdracht van premies sociale verzekering. Ook hiervan krijgt u als ondernemer een kopie toegezonden.
 <br className="inline" data-ditto-id="style-footer" />
 Ahneta zorgt ook voor de eindejaarsverwerking van uw loonadministratie inclusief de melding aan uw pensioenfonds of pensioenverzekeraar.
 <br className="inline" data-ditto-id="style-section" />
 <br className="inline" data-ditto-id="style-div-31" />
 <u className="inline font-bold underline" data-ditto-id="style-div-7">
 Verzorging van periodieke aangifte BTW
 </u>
 <br className="inline" data-ditto-id="style-div-32" />
 Ahneta zorgt – na controle van uw boekhouding – ook voor de periodieke elektronische indiening van uw aangifte Omzetbelasting. Deze module is alleen beschikbaar voor Bedrijven die ook gebruik maken van andere boekhoudmodules van Ahneta.
 <br className="inline" data-ditto-id="style-p-3" />
 <br className="inline" data-ditto-id="style-font-12" />
 {" Indien van toepassing kan Ahneta ook voor u de ICL aangifte verzorgen. Voorafgaand hieraan controleren wij of de BTW nummers van uw EU cliënten correct zijn. Ook controleren wij of uw ICL aangifte in overeenstemming is met uw aangiftes BTW."}
 <br className="inline" data-ditto-id="style-font-9" />
 <br className="inline" data-ditto-id="style-br-23" />
 <span className="inline font-bold" data-ditto-id="style-heading-5">
 <u className="inline underline" data-ditto-id="style-font-13">
 Verzorging aangifte inkomstenbelasting
 </u>
 </span>
 <br className="inline" data-ditto-id="style-font-3" />
 {"Voor de Bedrijven met een eenmanszaak of de vennoten van een "}
 <a className="inline text-color-002 cursor-pointer" data-ditto-id="style-div" data-component="link" href="https://v.o.f./">
 V.O.F.
 </a>
 {" verzorgt Ahneta ook de aangifte inkomstenbelasting. Deze dienst is ook alleen beschikbaar voor Bedrijven die één van de boekhoudmodules van Ahneta hebben afgesloten."}
 <br className="inline" data-ditto-id="style-p-4" />
 <br className="inline" data-ditto-id="style-font-41" />
 De aangifte Inkomstenbelasting maakt geen deel uit van het zakelijke dienstenpakket. De kosten hiervan worden u in privé gedeclareerd.
 <br className="inline" />
 <br className="inline" data-ditto-id="style-heading-3" />
 <span className="inline font-bold underline" data-ditto-id="style-span-17">
 Verzorging van aangifte VPB (Vennootschapsbelasting)
 </span>
 <br className="inline" data-ditto-id="style-link-6" />
 <span className="inline" data-ditto-id="style-font-4">
 Voor de rechtspersonen verzorgt Ahneta ook de aangifte VPB. Deze dienst is alleen beschikbaar voor Bedrijven die één van de boekhoudmodules van Ahneta hebben afgesloten.
 </span>
 <br className="inline" data-ditto-id="style-font-14" />
 <br className="inline" data-ditto-id="style-heading" />
 <span className="inline" data-ditto-id="style-link-7">
 {" De aangifte VPB maakt deel uit van het zakelijke dienstenpakket van uw onderneming. De kosten voor de verzorging van deze aangifte zijn dan ook opgenomen in de met u gemaakte prijsafspraken."}
 </span>
 <br className="inline" data-ditto-id="style-font-5" />
 <br className="inline" data-ditto-id="style-font-42" />
 <span className="inline font-bold" data-ditto-id="style-span-16">
 <u className="inline underline" data-ditto-id="style-div-13">
 Advisering bij bedrijfsovernames
 </u>
 </span>
 <br className="inline" />
 <span className="inline" data-ditto-id="style-font-15">
 Indien u als ondernemer uw bedrijf wilt overdragen – aan uw kinderen of aan een derden – kan Ahneta u hierbij begeleiden.
 </span>
 <br className="inline" data-ditto-id="style-font-10" />
 <span className="inline" data-ditto-id="style-br-11">
 Uiteraard is ook deze module uitsluitend beschikbaar voor Bedrijven die gebruik maken van andere diensten van Ahneta.
 </span>
 <br className="inline" data-ditto-id="style-heading-2" />
 <br className="inline" data-ditto-id="style-link-8" />
 <span className="inline" data-ditto-id="style-font-6">
 Voor deze module declareren wij ons honorarium op basis van het aantal bestede uren.
 </span>
 <br className="inline" data-ditto-id="style-font-24" />
 </p>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </main>
 {" "}
 <footer className="block shrink-0 text-background bg-color-004" data-ditto-id="style-div-22" id="bottom">
 <div className="block" data-ditto-id="style-div-11" id="footer">
 <section className="block relative pt-8 pb-4" data-ditto-id="style-p-7">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 " data-ditto-id="style-font-7">
 <div className="flex -mx-[0.9375rem] flex-wrap items-end" data-ditto-id="style-font-35">
 <div className="w-[17.8125rem] h-[8.1rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[123.7px] md:max-lg:w-180 md:max-lg:h-[6.2rem] 2xl:w-82.5" data-ditto-id="style-link-9">
 <p className="block mb-2" data-ditto-id="style-i-3">
 <font className="inline" data-ditto-id="style-link-10">
 {" "}
 <font className="inline" data-ditto-id="style-i-2">
 Hoe kunnen we helpen
 </font>
 {" "}
 </font>
 {" "}
 <br className="inline" data-ditto-id="style-link-11" />
 {" "}
 </p>
 {" "}
 <h4 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-2xl font-bold leading-[1.8125rem] max-md:text-[1.375rem] max-md:leading-[1.625rem] md:max-lg:text-[1.4375rem] md:max-lg:leading-[1.6875rem]" data-ditto-id="style-i" data-component="heading">
 <font className="inline" data-ditto-id="style-section-2">
 {" "}
 <font className="inline" data-ditto-id="style-div-6">
 {"U kunt altijd contact met ons opnemen "}
 </font>
 {" "}
 </font>
 {" "}
 </h4>
 {" "}
 </div>
 {" "}
 <div className="w-[17.8125rem] h-[8.15rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[128.9px] md:max-lg:w-180 md:max-lg:h-[8.1rem] 2xl:w-82.5" data-ditto-id="style-div-5" aria-describedby="tooltip8305">
 <p className="block mb-2" data-ditto-id="style-hr">
 <font className="inline" data-ditto-id="style-section-6">
 {" "}
 <font className="inline" data-ditto-id="style-div-34">
 Bel ons
 </font>
 {" "}
 </font>
 {" "}
 </p>
 {" "}
 <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-ditto-id="style-div-4" data-component="heading">
 <span className="inline" data-ditto-id="style-div-21">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-link-12" data-component="link" href="tel:31 (0) 33 46 11 447">
 {" "}
 <font className="inline" data-ditto-id="style-irketim-logosu">
 {" "}
 <font className="inline" data-ditto-id="style-div-12">
 {"+31 (0) 33 46 11 447 "}
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </span>
 {" "}
 </h5>
 {" "}
 <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-ditto-id="style-ul" data-component="heading" aria-describedby="tooltip842231">
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-li" data-component="link" href="tel:31 (0) 33 46 11 447">
 {" "}
 <font className="inline" data-ditto-id="style-link-13">
 {" "}
 <font className="inline" data-ditto-id="style-font-25">
 +31 (0) 6 11 23 88 30
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 <span className="inline" data-ditto-id="style-font-16">
 {" "}
 </span>
 {" "}
 </h5>
 {" "}
 </div>
 {" "}
 <div className="w-[17.8125rem] h-[6.075rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[6.025rem] md:max-lg:w-180 md:max-lg:h-[6.05rem] 2xl:w-82.5" data-ditto-id="style-li-3" aria-describedby="tooltip941693">
 <p className="block mb-2" data-ditto-id="style-font-22">
 <font className="inline">
 {" "}
 <font className="inline" data-ditto-id="style-li-8">
 Stuur ons een bericht
 </font>
 {" "}
 </font>
 {" "}
 <br className="inline" data-ditto-id="style-link-14" />
 {" "}
 </p>
 {" "}
 <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-ditto-id="style-font-26" data-component="heading">
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-font" data-component="link" href="mailto:info@ahneta.nl">
 {" "}
 <font className="inline" data-ditto-id="style-li-4">
 {" "}
 <font className="inline" data-ditto-id="style-font-19">
 info@ahneta.nl
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </h5>
 {" "}
 </div>
 {" "}
 <div className="w-[17.8125rem] h-[97.3px] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] md:max-lg:w-180 2xl:w-82.5" data-ditto-id="style-font-43">
 <div className="block text-right" data-ditto-id="style-li-11">
 <p className="block mr-[0.4rem] mb-2 align-middle" data-ditto-id="style-link-15">
 <font className="inline align-middle" data-ditto-id="style-font-27">
 {" "}
 <font className="inline align-middle" data-ditto-id="style-font-8">
 Volg ons
 </font>
 {" "}
 </font>
 {" "}
 </p>
 {" "}
 <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-li-2" data-component="link" href="https://www.ahneta.nl/website/social/twitter">
 {" "}
 <i className="flex m-1 justify-center items-center [font-family:FontAwesome-twitter-x-only] leading-4 before:content-[''] before:block before:w-4 before:h-4 before:text-primary before:text-base before:leading-4 before:text-right" data-ditto-id="style-font-33">
 ​
 </i>
 {" "}
 </a>
 {" "}
 <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-font-2" data-component="link" href="https://www.ahneta.nl/website/social/linkedin">
 {" "}
 <i className="flex m-1 justify-center items-center [font-family:FontAwesome] leading-4 before:content-[''] before:block before:w-[13.7px] before:h-4 before:text-primary before:text-base before:leading-4 before:text-right" data-ditto-id="style-li-12" aria-describedby="tooltip290654">
 ​
 </i>
 {" "}
 </a>
 {" "}
 <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-link-16" data-component="link" href="https://www.ahneta.nl/website/social/instagram">
 {" "}
 <i className="flex m-1 justify-center items-center [font-family:FontAwesome] leading-4 before:content-[''] before:block before:w-[13.7px] before:h-4 before:text-primary before:text-base before:leading-4 before:text-right" data-ditto-id="style-font-28">
 ​
 </i>
 {" "}
 </a>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative" data-ditto-id="style-font-34">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 ">
 <div className="block py-4 leading-0" data-ditto-id="style-font-17">
 <hr className="h-px border-t border-solid border-t-muted-foreground block overflow-hidden mx-auto w-[69.375rem] max-md:w-[21.5625rem] md:max-lg:w-[43.125rem] 2xl:w-[80.625rem]" data-ditto-id="style-font-11" />
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative" data-ditto-id="style-li-13">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 " data-ditto-id="style-link-17">
 <div className="flex -mx-[0.9375rem] flex-wrap items-center" aria-describedby="tooltip859185">
 <div className="w-47.5 h-[6.3125rem] min-h-6 block max-w-full pb-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-lg:h-34 md:max-lg:w-180 2xl:w-55 2xl:h-[116.9px]" data-ditto-id="style-font-18">
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-div-2" data-component="link" href="/">
 {" "}
 <img className="w-40 h-[5.3125rem] inline max-w-full overflow-clip align-middle max-lg:w-56.5 max-lg:h-30 2xl:w-47.5 2xl:h-[6.3125rem]" data-component="image" alt="" aria-label="Şirketim logosu" role="img" src="/assets/cloned/images/1461683c0d67.png" title="Benim şirketim" />
 {" "}
 </Link>
 {" "}
 </div>
 {" "}
 <div className="w-237.5 h-10 min-h-6 block max-w-full pb-4 px-[0.9375rem] shrink-0 text-right max-md:w-[23.4375rem] max-md:h-16 md:max-lg:w-180 2xl:w-275" data-ditto-id="style-div-8" aria-describedby="tooltip611099">
 <ul className="h-full block [list-style-type:none] list-outside" data-ditto-id="style-div-14" aria-describedby="tooltip612522">
 <li className="inline-block mr-2" data-ditto-id="style-span-11">
 {" "}
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-p" data-component="link" href="/">
 {" "}
 <font className="inline" data-ditto-id="style-link-18">
 {" "}
 <font className="inline" data-ditto-id="style-div-15">
 Home
 </font>
 {" "}
 </font>
 {" "}
 </Link>
 {" "}
 </li>
 <li className="inline-block mr-2">
 {" "}
 <font className="inline" data-ditto-id="style-link-40">
 {" "}
 <font className="inline" data-ditto-id="style-image">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-link-19">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-website-cookies-bar" data-component="link" href="#">
 {" "}
 <font className="inline" data-ditto-id="style-div-26">
 {" "}
 <font className="inline">
 Over ons
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-div-27">
 {" "}
 <font className="inline" data-ditto-id="style-div-9">
 {" "}
 <font className="inline" data-ditto-id="style-div-16">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block mr-2">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-link-21" data-component="link" href="#">
 {" "}
 <font className="inline" data-ditto-id="style-font-21">
 {" "}
 <font className="inline" data-ditto-id="style-font-36" aria-describedby="tooltip841579">
 Product
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </li>
 <li className="inline-block mr-2">
 {" "}
 <font className="inline" data-ditto-id="style-font-20">
 {" "}
 <font className="inline">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-li-6">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-link-22" data-component="link" href="#">
 {" "}
 <font className="inline" data-ditto-id="style-font-23">
 {" "}
 <font className="inline" aria-describedby="tooltip455312">
 Gebruiksvoorwaarden
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-li-7">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block" data-ditto-id="style-li-5">
 {" "}
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-link-23" data-component="link" aria-describedby="tooltip848069" href="/privacy">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline" data-ditto-id="style-font-37">
 Privacybeleid
 </font>
 {" "}
 </font>
 {" "}
 </Link>
 {" "}
 </li>
 </ul>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 </div>
 {" "}
 <div className="block bg-color-005">
 <div className="block max-w-285 mx-auto py-4 px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 " data-ditto-id="style-div-10">
 <div className="flex -mx-[0.9375rem] flex-wrap">
 <div className="w-full block max-w-full px-[0.9375rem] grow shrink-0 basis-[0%] text-color-003 text-left max-md:text-center max-md:grow-[initial] max-md:basis-[initial]">
 <span className="inline align-middle" data-ditto-id="style-span-18">
 Copyright © Ahneta Advies
 </span>
 {" "}
 <p className="block mb-4" data-ditto-id="style-p-6">
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-link-24" data-component="link" href="/cookie-policy">
 Cookiebeleid
 </Link>
 </p>
 </div>
 {" "}
 <div className="w-142.5 block max-w-full my-[1.3125rem] px-[0.9375rem] grow shrink-0 basis-[0%] text-right max-md:w-[23.4375rem] max-md:text-center max-md:my-0 max-md:grow-[initial] max-md:basis-[initial] md:max-lg:w-90 md:max-lg:my-[0.5625rem] 2xl:w-165" data-ditto-id="style-div-3">
 <div className="h-full block" data-ditto-id="style-div-17">
 {" "}
 <a className="text-color-003 cursor-pointer hover:underline" href="https://imora.nl" target="_blank" rel="noopener noreferrer">
 Maintained by Imora
 </a>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </footer>
 {" "}
 <div className="block shrink-0" id="website_cookies_bar">
 {" "}
 </div>
 {" "}
 {" "}
 <div className="block">
 <div className="block" />
 <div className="block" data-ditto-id="style-div-18" />
 <div className="w-78 h-0 block absolute top-[52.9px] left-240 z-1055 max-md:left-[3.4375rem] md:max-lg:left-112 2xl:left-400" />
 <div className="w-78 h-0 block absolute top-[52.9px] left-240 z-1055 max-md:left-[3.4375rem] md:max-lg:left-112 2xl:left-400" />
 </div>
 </>
 );
}
