import "./ditto.css";
import Tile from "./components/tile";
import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
import Link from "next/link";

export const metadata = {
 "title": "Startende Ondernemer | Ahneta Advies",
 "alternates": {
 "canonical": "/startende-ondernemer"
 },
 "openGraph": {
 "title": "Startende Ondernemer | Ahneta Advies"
 },
 "twitter": {
 "title": "Startende Ondernemer | Ahneta Advies"
 }
};
// Generated by clone-site. Do not edit by hand.
const Tile_data = [
 { text: "Lageprijsgarantie" },
 { text: "30 dagen online retourneren" },
 { text: "Standaard verzending" }
];
const ListRow_data = [
 { href: "/pricing", label: "Prijs" },
 { href: "/over-ons", label: "Over ons" },
 { href: "/contactus", label: "Contact" }
];
const ListRow2_data = [
 { text: "In het eerste jaar van de onderneming geeft Ahneta een korting van 10% op de kosten van het gekozen dienstenpakket." },
 { text: "In het tweede jaar van de onderneming geeft Ahneta een korting van 5% op de kosten van het gekozen dienstenpakket." },
 { text: "In het eerste jaar van de onderneming wordt door Ahneta vijf manuren gratis dienstverlening beschikbaar gesteld. Deze uren gebruikt worden voor ondersteuning bij de aanvraag van vergunning, ondersteuning bij de oprichting van de onderneming, opzetten van facturen, opzetten van grootboekschema voor de boekhouding, telefonische adviezen bij problemen tijdens de dagelijkse praktijk." }
];
const Tile_meta: string[][] = [
 ["n10", "n11"],
 ["n12", "n13"],
 ["n14", "n15"]
];
const ListRow_meta: string[][] = [
 ["n48", "style-9", "style-15"],
 ["n51", "style-10", "style-16"],
 ["n54", "style-11", "style-17"]
];
const ListRow2_meta: string[][] = [
 ["style-br-15", "style-br-7", "style-span-10"],
 ["n92", "n93", "n94"],
 ["style-br-2", "style-br-9", "style-span-9"]
];
const Tile_styles = [
 { className: "before:content-['']" },
 { className: "before:content-['']" },
 { className: "before:content-['']" }
];

export default function Page() {
 return (
 <>
 <main className="block grow shrink-0">
 <div className="h-full block" id="wrap">
 <div className="block">
 <section className="block relative py-6 overflow-hidden text-background bg-color-004">
 <span className="h-full block absolute top-0 inset-x-0 overflow-hidden bg-cover [background-position:50%_0px] bg-no-repeat [background-attachment:fixed] pointer-events-none max-lg:[background-attachment:initial]" style={{ backgroundImage: "url(\"/assets/cloned/images/2873c8e777c4.jpg\")" }} data-ditto-id="style-span-8" />
 {" "}
 <div className="h-full block absolute top-0 inset-x-0 overflow-hidden bg-color-004 bg-no-repeat pointer-events-none" data-ditto-id="style-div-28" />
 {" "}
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-div-33">
 <h1 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[3.875rem] font-bold leading-[4.625rem] max-md:text-4xl max-md:leading-[2.6875rem] md:max-lg:text-5xl md:max-lg:leading-[3.625rem]" data-ditto-id="style-heading-6" data-component="heading">
 Startende Ondernemer
 </h1>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 </div>
 {" "}
 <div className="block" data-ditto-id="style-div-29">
 <section className="block relative pt-10 bg-background" data-ditto-id="style-section-5">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-div-30">
 <p className="block mb-4" data-ditto-id="style-p-2">
 Jaarlijks zetten veel mensen de eerste stap en worden zelfstandig ondernemer. Deze groep heeft meer dan bestaande ondernemers behoefte aan goede begeleiding.Door Ahneta wordt onder startende ondernemer verstaan: die persoon die voor de eerste keer de stap gezet heeft om als zelfstandig ondernemer te beginnen. Indien door de startende ondernemer een bestaande onderneming van familie wordt voortgezet is dit geen startende onderneming. Neemt u daarentegen van een willekeurige persoon een bestaande onderneming over en is dit uw eerste stap op het pad van de zelfstandige ondernemer, dan bent u voor Ahneta een startende ondernemer.
 <br className="inline" data-ditto-id="style-br-4" />
 <br className="inline" data-ditto-id="style-span-20" />
 Startende ondernemers hebben vaak weinig financiële armslag, omdat al het beschikbare geld in de onderneming wordt geïnvesteerd. Voor hen heeft Ahneta een op maat gesneden dienstenpakket samengesteld.
 <br className="inline" data-ditto-id="style-span-6" />
 <br className="inline" data-ditto-id="style-br-5" />
 <span className="inline text-lg font-bold leading-[1.6875rem]">
 Dit dienstenpakket is voor een groot gedeelte gelijk aan het dienstenpakket voor ondernemers, maar startende ondernemers krijgen bij Ahneta een aantal voordelen;
 </span>
 <br className="inline" />
 <br className="inline" data-ditto-id="style-span-5" />
 <br className="inline" data-ditto-id="style-u" />
 </p>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative pb-10" data-ditto-id="style-br-10">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-br-3">
 <ul className="block mb-4 pl-8 [list-style-type:disc] list-outside" data-ditto-id="style-span-7">
 {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} />)}
 <li className="list-item" data-ditto-id="style-br-8">
 In het tweede jaar van de onderneming wordt door Ahneta drie manuren gratis dienstverlening beschikbaar gesteld. Deze uren kunnen gebruikt worden voor verbetering van het facturatieproces of van het gekozen grootboekschema, telefonische adviezen bij problemen tijdens de dag dagelijkse praktijk.
 </li>
 </ul>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </main>
 {" "}
 <footer className="block shrink-0 text-background bg-color-004" data-ditto-id="style-br-18" id="bottom">
 <div className="block" data-ditto-id="style-span-15" id="footer">
 <section className="block relative pt-8 pb-4" data-ditto-id="style-br-17">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 " data-ditto-id="style-br-12">
 <div className="flex -mx-[0.9375rem] flex-wrap items-end" data-ditto-id="style-span-13">
 <div className="w-[17.8125rem] h-[8.1rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[123.7px] md:max-lg:w-180 md:max-lg:h-[6.2rem] 2xl:w-82.5" data-ditto-id="style-br">
 <p className="block mb-2">
 <font className="inline">
 {" "}
 <font className="inline" data-ditto-id="style-br-22">
 Hoe kunnen we helpen
 </font>
 {" "}
 </font>
 {" "}
 <br className="inline" data-ditto-id="style-br-13" />
 {" "}
 </p>
 {" "}
 <h4 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-2xl font-bold leading-[1.8125rem] max-md:text-[1.375rem] max-md:leading-[1.625rem] md:max-lg:text-[1.4375rem] md:max-lg:leading-[1.6875rem]" data-ditto-id="style-span-22" data-component="heading">
 <font className="inline" data-ditto-id="style-br-21">
 {" "}
 <font className="inline">
 {"U kunt altijd contact met ons opnemen "}
 </font>
 {" "}
 </font>
 {" "}
 </h4>
 {" "}
 </div>
 {" "}
 <div className="w-[17.8125rem] h-[8.15rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[128.9px] md:max-lg:w-180 md:max-lg:h-[8.1rem] 2xl:w-82.5" data-ditto-id="style-span-12" aria-describedby="tooltip8305">
 <p className="block mb-2" data-ditto-id="style-u-2">
 <font className="inline">
 {" "}
 <font className="inline" data-ditto-id="style-br-14">
 Bel ons
 </font>
 {" "}
 </font>
 {" "}
 </p>
 {" "}
 <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-component="heading">
 <span className="inline" data-ditto-id="style-br-16">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-br-6" data-component="link" href="tel:31 (0) 33 46 11 447">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline" data-ditto-id="style-bottom">
 {"+31 (0) 33 46 11 447 "}
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </span>
 {" "}
 </h5>
 {" "}
 <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-ditto-id="style-footer" data-component="heading" aria-describedby="tooltip842231">
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-section" data-component="link" href="tel:31 (0) 33 46 11 447">
 {" "}
 <font className="inline" data-ditto-id="style-div-31">
 {" "}
 <font className="inline" data-ditto-id="style-div-7">
 +31 (0) 6 11 23 88 30
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 <span className="inline" data-ditto-id="style-div-32">
 {" "}
 </span>
 {" "}
 </h5>
 {" "}
 </div>
 {" "}
 <div className="w-[17.8125rem] h-[6.075rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[6.025rem] md:max-lg:w-180 md:max-lg:h-[6.05rem] 2xl:w-82.5" data-ditto-id="style-p-3" aria-describedby="tooltip941693">
 <p className="block mb-2" data-ditto-id="style-font-12">
 <font className="inline" data-ditto-id="style-font-9">
 {" "}
 <font className="inline" data-ditto-id="style-br-23">
 Stuur ons een bericht
 </font>
 {" "}
 </font>
 {" "}
 <br className="inline" data-ditto-id="style-heading-5" />
 {" "}
 </p>
 {" "}
 <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-ditto-id="style-font-13" data-component="heading">
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-font-3" data-component="link" href="mailto:info@ahneta.nl">
 {" "}
 <font className="inline" data-ditto-id="style-div">
 {" "}
 <font className="inline" data-ditto-id="style-p-4">
 info@ahneta.nl
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </h5>
 {" "}
 </div>
 {" "}
 <div className="w-[17.8125rem] h-[97.3px] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] md:max-lg:w-180 2xl:w-82.5" data-ditto-id="style-font-41">
 <div className="block text-right">
 <p className="block mr-[0.4rem] mb-2 align-middle" data-ditto-id="style-heading-3">
 <font className="inline align-middle" data-ditto-id="style-span-17">
 {" "}
 <font className="inline align-middle" data-ditto-id="style-link-6">
 Volg ons
 </font>
 {" "}
 </font>
 {" "}
 </p>
 {" "}
 <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-font-4" data-component="link" href="https://www.ahneta.nl/website/social/twitter">
 {" "}
 <i className="flex m-1 justify-center items-center [font-family:FontAwesome-twitter-x-only] leading-4 before:content-[''] before:block before:w-4 before:h-4 before:text-primary before:text-base before:leading-4 before:text-right" data-ditto-id="style-font-14">
 ​
 </i>
 {" "}
 </a>
 {" "}
 <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-heading" data-component="link" href="https://www.ahneta.nl/website/social/linkedin">
 {" "}
 <i className="flex m-1 justify-center items-center [font-family:FontAwesome] leading-4 before:content-[''] before:block before:w-[13.7px] before:h-4 before:text-primary before:text-base before:leading-4 before:text-right" data-ditto-id="style-link-7" aria-describedby="tooltip290654">
 ​
 </i>
 {" "}
 </a>
 {" "}
 <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-font-5" data-component="link" href="https://www.ahneta.nl/website/social/instagram">
 {" "}
 <i className="flex m-1 justify-center items-center [font-family:FontAwesome] leading-4 before:content-[''] before:block before:w-[13.7px] before:h-4 before:text-primary before:text-base before:leading-4 before:text-right" data-ditto-id="style-font-42">
 ​
 </i>
 {" "}
 </a>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative" data-ditto-id="style-span-16">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 " data-ditto-id="style-div-13">
 <div className="block py-4 leading-0">
 <hr className="h-px border-t border-solid border-t-muted-foreground block overflow-hidden mx-auto w-[69.375rem] max-md:w-[21.5625rem] md:max-lg:w-[43.125rem] 2xl:w-[80.625rem]" data-ditto-id="style-font-15" />
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative" data-ditto-id="style-font-10">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 " data-ditto-id="style-br-11">
 <div className="flex -mx-[0.9375rem] flex-wrap items-center" data-ditto-id="style-heading-2" aria-describedby="tooltip859185">
 <div className="w-47.5 h-[6.3125rem] min-h-6 block max-w-full pb-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-lg:h-34 md:max-lg:w-180 2xl:w-55 2xl:h-[116.9px]" data-ditto-id="style-link-8">
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-font-6" data-component="link" href="/">
 {" "}
 <img className="w-40 h-[5.3125rem] inline max-w-full overflow-clip align-middle max-lg:w-56.5 max-lg:h-30 2xl:w-47.5 2xl:h-[6.3125rem]" data-ditto-id="style-font-24" data-component="image" alt="" aria-label="Şirketim logosu" role="img" src="/assets/cloned/images/1461683c0d67.png" title="Benim şirketim" />
 {" "}
 </Link>
 {" "}
 </div>
 {" "}
 <div className="w-237.5 h-10 min-h-6 block max-w-full pb-4 px-[0.9375rem] shrink-0 text-right max-md:w-[23.4375rem] max-md:h-16 md:max-lg:w-180 2xl:w-275" data-ditto-id="style-div-22" aria-describedby="tooltip611099">
 <ul className="h-full block [list-style-type:none] list-outside" data-ditto-id="style-div-11" aria-describedby="tooltip612522">
 <li className="inline-block mr-2" data-ditto-id="style-p-7">
 {" "}
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-font-7" data-component="link" href="/">
 {" "}
 <font className="inline" data-ditto-id="style-font-35">
 {" "}
 <font className="inline" data-ditto-id="style-link-9">
 Home
 </font>
 {" "}
 </font>
 {" "}
 </Link>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-i-3">
 {" "}
 <font className="inline" data-ditto-id="style-link-10">
 {" "}
 <font className="inline" data-ditto-id="style-i-2">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-link-11">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-i" data-component="link" href="#">
 {" "}
 <font className="inline" data-ditto-id="style-section-2">
 {" "}
 <font className="inline" data-ditto-id="style-div-6">
 Over ons
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-div-5">
 {" "}
 <font className="inline" data-ditto-id="style-hr">
 {" "}
 <font className="inline" data-ditto-id="style-section-6">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-div-34">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-div-4" data-component="link" href="#">
 {" "}
 <font className="inline" data-ditto-id="style-div-21">
 {" "}
 <font className="inline" data-ditto-id="style-link-12" aria-describedby="tooltip841579">
 Product
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-irketim-logosu">
 {" "}
 <font className="inline" data-ditto-id="style-div-12">
 {" "}
 <font className="inline" data-ditto-id="style-ul">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-li">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-link-13" data-component="link" href="#">
 {" "}
 <font className="inline" data-ditto-id="style-font-25">
 {" "}
 <font className="inline" data-ditto-id="style-font-16" aria-describedby="tooltip455312">
 Gebruiksvoorwaarden
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-li-3">
 {" "}
 <font className="inline" data-ditto-id="style-font-22">
 {" "}
 <font className="inline">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block" data-ditto-id="style-li-8">
 {" "}
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-link-14" data-component="link" aria-describedby="tooltip848069" href="/privacy">
 {" "}
 <font className="inline" data-ditto-id="style-font-26">
 {" "}
 <font className="inline" data-ditto-id="style-font">
 Privacybeleid
 </font>
 {" "}
 </font>
 {" "}
 </Link>
 {" "}
 </li>
 </ul>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 </div>
 {" "}
 <div className="block bg-color-005" data-ditto-id="style-li-4">
 <div className="block max-w-285 mx-auto py-4 px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 " data-ditto-id="style-font-19">
 <div className="flex -mx-[0.9375rem] flex-wrap" data-ditto-id="style-font-43">
 <div className="w-full block max-w-full px-[0.9375rem] grow shrink-0 basis-[0%] text-color-003 text-left max-md:text-center max-md:grow-[initial] max-md:basis-[initial]" data-ditto-id="style-li-11">
 <span className="inline align-middle" data-ditto-id="style-link-15">
 Copyright © Ahneta Advies
 </span>
 {" "}
 <p className="block mb-4" data-ditto-id="style-font-27">
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-font-8" data-component="link" href="/cookie-policy">
 Cookiebeleid
 </Link>
 </p>
 </div>
 {" "}
 <div className="w-142.5 block max-w-full my-[1.3125rem] px-[0.9375rem] grow shrink-0 basis-[0%] text-right max-md:w-[23.4375rem] max-md:text-center max-md:my-0 max-md:grow-[initial] max-md:basis-[initial] md:max-lg:w-90 md:max-lg:my-[0.5625rem] 2xl:w-165" data-ditto-id="style-li-2">
 <div className="h-full block" data-ditto-id="style-font-33">
 {" "}
 <a className="text-color-003 cursor-pointer hover:underline" href="https://imora.nl" target="_blank" rel="noopener noreferrer">
 Maintained by Imora
 </a>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </footer>
 {" "}
 <div className="block shrink-0" data-ditto-id="style-font-28" id="website_cookies_bar">
 {" "}
 </div>
 {" "}
 {" "}
 <div className="block" data-ditto-id="style-font-34">
 <div className="block" />
 <div className="block" data-ditto-id="style-font-17" />
 <div className="w-78 h-0 block absolute top-[52.9px] left-240 z-1055 max-md:left-[3.4375rem] md:max-lg:left-112 2xl:left-400" data-ditto-id="style-font-11" />
 <div className="w-78 h-0 block absolute top-[52.9px] left-240 z-1055 max-md:left-[3.4375rem] md:max-lg:left-112 2xl:left-400" data-ditto-id="style-li-13" />
 </div>
 </>
 );
}
