import "./ditto.css";
import Tile from "./components/tile";
import ListRow from "./components/list-row";
import Link from "next/link";
import HeroText from "./components/hero-text";
// Generated by clone-site. Do not edit by hand.
const Tile_data = [
 { text: "Lageprijsgarantie" },
 { text: "30 dagen online retourneren" },
 { text: "Standaard verzending" }
];
const ListRow_data = [
 { href: "/pricing", label: "Prijs" },
 { href: "/over-ons", label: "Over ons" },
 { href: "/contactus", label: "Contact" }
];
const Tile_meta: string[][] = [
 ["n10", "n11"],
 ["n12", "n13"],
 ["n14", "n15"]
];
const ListRow_meta: string[][] = [
 ["n48", "style-9", "style-15"],
 ["n51", "style-10", "style-16"],
 ["n54", "style-11", "style-17"]
];
const Tile_styles = [
 { className: "before:content-['']" },
 { className: "before:content-['']" },
 { className: "before:content-['']" }
];

export default function Page() {
 return (
 <>
 <main className="block grow shrink-0">
 <div className="h-full block" id="wrap">
 <section className="h-[41.7875rem] min-h-[41.7875rem] flex relative py-24 flex-col justify-around overflow-hidden text-background bg-color-004 max-md:h-186 max-md:min-h-186 md:max-lg:h-239 md:max-lg:min-h-239">
 <span className="h-full block absolute top-0 inset-x-0 min-w-0 overflow-hidden bg-cover [background-position:50%_0px] bg-no-repeat [background-attachment:fixed] pointer-events-none max-lg:[background-attachment:initial]" style={{ backgroundImage: "url(\"/assets/cloned/images/995292c8c739.jpg\")" }} />
 {" "}
 <div className="h-full block absolute top-0 inset-x-0 min-w-0 overflow-hidden bg-color-004 bg-no-repeat pointer-events-none" data-ditto-id="style-span-8" />
 {" "}
 <div className="h-full block absolute top-0 inset-x-0 min-w-0 overflow-hidden [background-size:100%] [background-position:50%_100%] bg-no-repeat pointer-events-none max-md:hidden" style={{ backgroundImage: "url(\"/assets/cloned/svg/bb90d3edfd2e.svg\")" }} data-ditto-id="style-div-28" />
 {" "}
 <HeroText>
 <div className="block relative max-w-180 mx-auto px-[0.9375rem] max-md:max-w-none before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-div-33">
 <h1 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[3.875rem] font-bold leading-[4.625rem] text-center max-md:text-4xl max-md:leading-[2.6875rem] md:max-lg:text-5xl md:max-lg:leading-[3.625rem]" data-ditto-id="style-heading-6" data-component="heading" data-hero-animate>
 <span className="inline-block z-1" data-ditto-id="style-div-29">
 Ahneta Advies
 </span>
 {" "}
 </h1>
 {" "}
 <p className="block mb-4 text-lg font-light leading-[1.6875rem] text-center" data-ditto-id="style-section-5" aria-describedby="tooltip684660" data-hero-animate>
 <br className="inline" data-ditto-id="style-div-30" />
 {" Ahneta Advies werkt al vele jaren als zelfstandig adviesbureau. Wij zijn belastingadviseurs voor zowel bedrijven (MKB) als ook voor particulieren."}
 </p>
 {" "}
 </div>
 </HeroText>
 {" "}
 </section>
 {" "}
 <section className="block relative pt-6 pb-16" data-ditto-id="style-p-2">
 <div className="h-full block absolute top-0 inset-x-0 overflow-hidden [background-size:100%] [background-position:50%_100%] bg-no-repeat pointer-events-none max-md:hidden" style={{ backgroundImage: "url(\"/assets/cloned/svg/8a41911da489.svg\")" }} data-ditto-id="style-br-4" />
 {" "}
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-span-20">
 <div className="flex -mx-[0.9375rem] flex-wrap items-center" data-ditto-id="style-span-6">
 <div className="w-[41.5625rem] block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] md:max-lg:w-180 2xl:w-192.5" data-ditto-id="style-br-5">
 <img className="w-[39.6875rem] h-[27.8125rem] block max-w-full p-8 overflow-clip align-middle mx-auto max-md:w-[21.5625rem] max-md:h-[15.6875rem] md:max-lg:w-172.5 md:max-lg:h-[30.0625rem] 2xl:w-185 2xl:h-[32.1875rem]" data-component="image" alt="two men in suit sitting on sofa" aria-describedby="tooltip411114" src="/assets/cloned/images/457b551bddc0.jpg" />
 {" "}
 </div>
 {" "}
 <div className="w-[29.6875rem] block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] md:max-lg:w-180 2xl:w-137.5">
 <h2 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[2.75rem] font-bold leading-[3.3125rem] max-md:text-[1.8125rem] max-md:leading-[2.1875rem] md:max-lg:text-4xl md:max-lg:leading-[2.75rem]" data-ditto-id="style-span-5" data-component="heading">
 Bewust persoonlijk
 </h2>
 {" "}
 <p className="block mb-4" data-ditto-id="style-u">
 {" Ahneta is geen groot bedrijf en dat is een bewuste keuze!"}
 <br className="inline" data-ditto-id="style-br-10" />
 <br className="inline" data-ditto-id="style-br-3" />
 Wij kunnen op deze manier voldoende tijd voor u vrij maken en kunnen wij u beter van dienst zijn met een persoonlijk advies.
 <br className="inline" data-ditto-id="style-span-7" />
 <br className="inline" data-ditto-id="style-br-15" />
 Deze keuze heeft ook positieve gevolgen wij hebben hierdoor weinig overheadkosten waardoor wij de tarieven van onze dienstverlening aantrekkelijk kunnen houden.
 </p>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative py-10 text-background bg-color-005" data-ditto-id="style-br-7">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-span-10">
 <h1 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[3.875rem] font-bold leading-[4.625rem] text-center max-md:text-4xl max-md:leading-[2.6875rem] md:max-lg:text-5xl md:max-lg:leading-[3.625rem]" data-component="heading">
 <font className="inline max-lg:text-[3.875rem] max-lg:leading-[4.625rem]">
 {" "}
 <u className="inline underline">
 {" "}
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-br-2" data-component="link" href="/bedrijven">
 Bedrijven
 </Link>
 {" "}
 </u>
 {" "}
 </font>
 {" "}
 </h1>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative pb-30 text-background bg-accent" data-ditto-id="style-br-9">
 <div className="h-full block absolute top-0 inset-x-0 overflow-hidden [background-size:100%] [background-position:50%_0%] bg-no-repeat pointer-events-none max-md:hidden" style={{ backgroundImage: "url(\"/assets/cloned/svg/991d583798c1.svg\")" }} data-ditto-id="style-span-9" />
 {" "}
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-br-8">
 <div className="flex -mx-[0.9375rem] flex-wrap" data-ditto-id="style-br-18">
 <div className="w-190 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] md:max-lg:w-180 2xl:w-220" data-ditto-id="style-span-15">
 <div className="h-full flex rounded-md flex-row-reverse flex-wrap items-center overflow-hidden text-foreground bg-background shadow-[var(--color-006)_0px_4px_16px_0px]" data-ditto-id="style-br-17">
 <div className="w-[243.3px] block max-w-full self-stretch shrink-0 max-md:w-[21.5625rem] md:max-lg:w-172.5 2xl:w-[283.3px]" data-ditto-id="style-br-12">
 <Link className="inline text-color-002 cursor-pointer" data-ditto-id="style-span-13" data-component="link" href="/ondernemersplan">
 {" "}
 <img className="inline overflow-clip object-cover align-middle h-[16.2225rem] w-[243.33px] max-md:h-[14.375rem] max-md:w-[21.5625rem] md:max-lg:h-[28.75rem] md:max-lg:w-[43.125rem] 2xl:w-[283.33px]" data-ditto-id="style-br" data-component="image" alt="" aria-describedby="tooltip771097" src="/assets/cloned/images/b0345c2ec162.jpg" />
 {" "}
 </Link>
 {" "}
 </div>
 {" "}
 <div className="w-[486.7px] block max-w-full p-8 shrink-0 max-md:w-[21.5625rem] md:max-lg:w-172.5 2xl:w-[566.7px]">
 <h3 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-4xl font-bold leading-[2.6875rem] max-md:text-[1.625rem] max-md:leading-[1.9375rem] md:max-lg:text-[1.9375rem] md:max-lg:leading-[2.3125rem]" data-component="heading">
 <span className="inline text-accent" data-ditto-id="style-br-22">
 1.
 </span>
 {" "}
 <Link className="inline text-color-002 cursor-pointer" data-ditto-id="style-br-13" data-component="link" href="/ondernemersplan">
 Ondernemersplan
 </Link>
 {" "}
 </h3>
 {" "}
 <p className="block mb-4" data-ditto-id="style-span-22">
 {" Een ondernemingsplan is het samenspel van u als ondernemer en van Ahneta als adviseur."}
 <br className="inline" data-ditto-id="style-br-21" />
 </p>
 {" "}
 <p className="block mb-4">
 <Link className="border border-solid border-accent inline-block py-[0.45rem] px-[1.35rem] rounded-[100px] align-middle text-background text-center bg-accent cursor-pointer" data-ditto-id="style-span-12" data-component="button" href="/ondernemersplan">
 Lees meer...
 </Link>
 {" "}
 <br className="inline" data-ditto-id="style-u-2" />
 {" "}
 <br className="inline" />
 {" "}
 </p>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 <div className="w-190 block max-w-full ml-47.5 py-6 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-lg:ml-0 md:max-lg:w-180 2xl:w-220 2xl:ml-55" data-ditto-id="style-br-14">
 <div className="h-full flex rounded-md flex-row-reverse flex-wrap items-center overflow-hidden bg-color-005 shadow-[var(--color-006)_0px_4px_16px_0px]">
 <div className="w-[243.3px] block max-w-full self-stretch shrink-0 max-md:w-[21.5625rem] md:max-lg:w-172.5 2xl:w-[283.3px]" data-ditto-id="style-br-16">
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-br-6" data-component="link" href="/administratie">
 {" "}
 <img className="inline overflow-clip object-cover align-middle h-[267.19px] w-[243.33px] max-md:h-[14.4025rem] max-md:w-[21.5625rem] md:max-lg:h-[460.89px] md:max-lg:w-[43.125rem] 2xl:w-[283.33px]" data-component="image" alt="" aria-describedby="tooltip372174" src="/assets/cloned/images/69a875857b13.jpg" />
 {" "}
 </Link>
 {" "}
 </div>
 {" "}
 <div className="w-[486.7px] block max-w-full p-8 shrink-0 max-md:w-[21.5625rem] md:max-lg:w-172.5 2xl:w-[566.7px]" data-ditto-id="style-bottom" aria-describedby="tooltip264557">
 <h3 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-4xl font-bold leading-[2.6875rem] max-md:text-[1.625rem] max-md:leading-[1.9375rem] md:max-lg:text-[1.9375rem] md:max-lg:leading-[2.3125rem]" data-ditto-id="style-footer" data-component="heading">
 {" "}
 </h3>
 {" "}
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-section" data-component="link" aria-describedby="tooltip130468" href="/administratie">
 {" "}
 <h3 className="block mb-2 text-background [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-4xl font-bold leading-[2.6875rem] max-md:text-[1.625rem] max-md:leading-[1.9375rem] md:max-lg:text-[1.9375rem] md:max-lg:leading-[2.3125rem]" data-ditto-id="style-div-31" data-component="heading" aria-describedby="tooltip251966">
 <span className="inline text-accent" data-ditto-id="style-div-7">
 2.
 </span>
 {" Administratie "}
 </h3>
 {" "}
 <p className="block mb-4" data-ditto-id="style-div-32" aria-describedby="tooltip276953">
 {" Al vanaf de start van de onderneming heeft Ahneta zich dienstverlenend voor het MKB geprofileerd."}
 </p>
 {" "}
 </Link>
 {" "}
 <p className="block mb-4" data-ditto-id="style-p-3" aria-describedby="tooltip276953">
 {" "}
 </p>
 {" "}
 <p className="block mb-4" data-ditto-id="style-font-12" aria-describedby="tooltip648902">
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-font-9" data-component="link" aria-describedby="tooltip284591" href="/administratie#top">
 {" "}
 <br className="inline" data-ditto-id="style-br-23" />
 {" "}
 </Link>
 {" "}
 </p>
 {" "}
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-heading-5" data-component="link" aria-describedby="tooltip284591" href="/administratie#top">
 {" "}
 </Link>
 {" "}
 <br className="inline" data-ditto-id="style-font-13" />
 {" "}
 <p className="block mb-4" data-ditto-id="style-font-3" />
 {" "}
 <p className="block mb-4" data-ditto-id="style-div" />
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 <div className="w-[53.4375rem] block max-w-full ml-[17.8125rem] py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-lg:ml-0 md:max-lg:w-180 2xl:w-247.5 2xl:ml-82.5" data-ditto-id="style-p-4">
 <div className="h-full flex rounded-md flex-row-reverse flex-wrap items-center overflow-hidden text-foreground bg-background shadow-[var(--color-006)_0px_4px_16px_0px]" data-ditto-id="style-font-41">
 <div className="w-[17.1875rem] block max-w-full self-stretch shrink-0 max-md:w-[21.5625rem] md:max-lg:w-172.5 2xl:w-80">
 <Link className="inline text-color-002 cursor-pointer" data-ditto-id="style-heading-3" data-component="link" href="/startende-ondernemer">
 {" "}
 <img className="inline overflow-clip object-cover align-middle h-[14.7225rem] w-[274.98px] max-md:h-[14.375rem] max-md:w-[21.5625rem] md:max-lg:h-[28.75rem] md:max-lg:w-[43.125rem] 2xl:w-80" data-ditto-id="style-span-17" data-component="image" alt="three person pointing the silver laptop computer" aria-describedby="tooltip968075" src="/assets/cloned/images/c2f99a13466d.jpg" />
 {" "}
 </Link>
 {" "}
 </div>
 {" "}
 <div className="w-[34.375rem] block max-w-full p-8 shrink-0 max-md:w-[21.5625rem] md:max-lg:w-172.5 2xl:w-[40rem]" data-ditto-id="style-link-6">
 <h3 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-4xl font-bold leading-[2.6875rem] max-md:text-[1.625rem] max-md:leading-[1.9375rem] md:max-lg:text-[1.9375rem] md:max-lg:leading-[2.3125rem]" data-ditto-id="style-font-4" data-component="heading" aria-describedby="tooltip207515">
 <Link className="inline text-color-002 cursor-pointer" data-ditto-id="style-font-14" data-component="link" href="/startende-ondernemer">
 <span className="inline text-accent" data-ditto-id="style-heading">
 3.
 </span>
 {" Startende Ondernemer"}
 <br className="inline" data-ditto-id="style-link-7" />
 </Link>
 {" "}
 </h3>
 {" "}
 <p className="block mb-4" data-ditto-id="style-font-5">
 Een op maat gesneden dienstenpakket met een aantal voordelen
 </p>
 {" "}
 <p className="block mb-4" data-ditto-id="style-font-42">
 <br className="inline" data-ditto-id="style-span-16" />
 {" "}
 <Link className="border border-solid border-accent inline-block py-[0.45rem] px-[1.35rem] rounded-[100px] align-middle text-background text-center bg-accent cursor-pointer" data-ditto-id="style-div-13" data-component="button" href="/startende-ondernemer">
 Lees meer...
 </Link>
 {" "}
 <br className="inline" />
 {" "}
 </p>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative py-10 text-background bg-color-005" data-ditto-id="style-font-15">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-font-10">
 <h1 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[3.875rem] font-bold leading-[4.625rem] text-center max-md:text-4xl max-md:leading-[2.6875rem] md:max-lg:text-5xl md:max-lg:leading-[3.625rem]" data-ditto-id="style-br-11" data-component="heading">
 <font className="inline max-lg:text-[3.875rem] max-lg:leading-[4.625rem]" data-ditto-id="style-heading-2">
 {" "}
 <u className="inline underline" data-ditto-id="style-link-8">
 {" "}
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-font-6" data-component="link" href="/particulieren">
 Particulieren
 </Link>
 {" "}
 </u>
 {" "}
 </font>
 {" "}
 </h1>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative pb-30 text-background bg-accent" data-ditto-id="style-font-24">
 <div className="h-full block absolute top-0 inset-x-0 overflow-hidden [background-size:100%] [background-position:50%_0%] bg-no-repeat pointer-events-none max-md:hidden" style={{ backgroundImage: "url(\"/assets/cloned/svg/1e94cda9097d.svg\")" }} data-ditto-id="style-div-22" />
 {" "}
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-div-11">
 <div className="flex -mx-[0.9375rem] flex-wrap" data-ditto-id="style-p-7" aria-describedby="tooltip283110">
 <div className="w-237.5 block max-w-full ml-[17.8125rem] py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-lg:ml-0 md:max-lg:w-180 2xl:w-275 2xl:ml-82.5" data-ditto-id="style-font-7">
 <div className="h-full flex rounded-md flex-row-reverse flex-wrap items-center overflow-hidden text-foreground bg-background shadow-[var(--color-006)_0px_4px_16px_0px]" data-ditto-id="style-font-35">
 <div className="w-[306.7px] h-[14.725rem] min-h-6 block max-w-full self-stretch shrink-0 max-md:w-[21.5625rem] max-md:h-57.5 md:max-lg:w-172.5 md:max-lg:h-115 2xl:w-[356.7px] 2xl:h-[14.8625rem]" data-ditto-id="style-link-9">
 <Link className="inline text-color-002 cursor-pointer" data-ditto-id="style-i-3" data-component="link" href="/aangifte-ib">
 {" "}
 <img className="inline overflow-clip object-cover align-middle h-[14.7225rem] w-[306.66px] max-md:h-[14.375rem] max-md:w-[21.5625rem] md:max-lg:h-[28.75rem] md:max-lg:w-[43.125rem] 2xl:h-[237.77px] 2xl:w-[356.66px]" data-ditto-id="style-link-10" data-component="image" alt="" aria-describedby="tooltip968075" src="/assets/cloned/images/69326586a004.jpg" />
 {" "}
 </Link>
 {" "}
 </div>
 {" "}
 <div className="w-[613.3px] h-[14.725rem] min-h-6 block max-w-full p-8 shrink-0 max-md:w-[21.5625rem] max-md:h-[18.9375rem] md:max-lg:w-172.5 md:max-lg:h-[229.3px] 2xl:w-[713.3px]" data-ditto-id="style-i-2">
 <h3 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-4xl font-bold leading-[2.6875rem] max-md:text-[1.625rem] max-md:leading-[1.9375rem] md:max-lg:text-[1.9375rem] md:max-lg:leading-[2.3125rem]" data-ditto-id="style-link-11" data-component="heading">
 <span className="inline text-accent" data-ditto-id="style-i">
 1.
 </span>
 {" Aangifte Inkomstenbelasting"}
 <br className="inline" data-ditto-id="style-section-2" />
 </h3>
 {" "}
 <p className="block mb-4" data-ditto-id="style-div-6" aria-describedby="tooltip704300">
 {" De verzorging van de aangifte inkomstenbelasting en de afhandeling van eventuele bezwaar- en beroepsschriften."}
 </p>
 {" "}
 <p className="block mb-4" data-ditto-id="style-div-5" aria-describedby="tooltip704300">
 <Link className="border border-solid border-accent inline-block py-[0.45rem] px-[1.35rem] rounded-[100px] align-middle text-background text-center bg-accent cursor-pointer" data-ditto-id="style-hr" data-component="button" href="/aangifte-ib">
 {"Lees meer... "}
 </Link>
 {" "}
 <br className="inline" data-ditto-id="style-section-6" />
 {" "}
 </p>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 <div className="w-190 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] md:max-lg:w-180 2xl:w-220" data-ditto-id="style-div-34">
 <div className="h-full flex rounded-md flex-row-reverse flex-wrap items-center overflow-hidden text-foreground bg-background shadow-[var(--color-006)_0px_4px_16px_0px]" data-ditto-id="style-div-4">
 <div className="w-[243.3px] block max-w-full self-stretch shrink-0 max-md:w-[21.5625rem] md:max-lg:w-172.5 2xl:w-[283.3px]" data-ditto-id="style-div-21">
 <Link className="inline text-color-002 cursor-pointer" data-ditto-id="style-link-12" data-component="link" href="/estate-planning">
 {" "}
 <img className="inline overflow-clip object-cover align-middle h-[318.78px] w-[243.33px] max-md:h-[28.25rem] max-md:w-[21.5625rem] md:max-lg:h-[56.5rem] md:max-lg:w-[43.125rem] 2xl:h-[371.19px] 2xl:w-[283.33px]" data-ditto-id="style-irketim-logosu" data-component="image" alt="blue ceramic vase on brown wooden table" aria-describedby="tooltip212933" src="/assets/cloned/images/f85b184a3e69.jpg" />
 {" "}
 </Link>
 {" "}
 </div>
 {" "}
 <div className="w-[486.7px] block max-w-full p-8 shrink-0 max-md:w-[21.5625rem] md:max-lg:w-172.5 2xl:w-[566.7px]" data-ditto-id="style-div-12">
 <h3 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-4xl font-bold leading-[2.6875rem] max-md:text-[1.625rem] max-md:leading-[1.9375rem] md:max-lg:text-[1.9375rem] md:max-lg:leading-[2.3125rem]" data-ditto-id="style-ul" data-component="heading">
 <span className="inline text-accent" data-ditto-id="style-li">
 2.
 </span>
 <Link className="inline text-color-002 cursor-pointer" data-ditto-id="style-link-13" data-component="link" href="/estate-planning">
 {"Estate "}
 </Link>
 Planning
 <br className="inline" data-ditto-id="style-font-25" />
 </h3>
 {" "}
 <p className="block mb-4" data-ditto-id="style-font-16">
 {" Ahneta adviseert op gebied van Estate Planning (vermogensplanning)."}
 </p>
 {" "}
 <p className="block mb-4" data-ditto-id="style-li-3">
 <Link className="border border-solid border-accent inline-block py-[0.45rem] px-[1.35rem] rounded-[100px] align-middle text-background text-center bg-accent cursor-pointer" data-ditto-id="style-font-22" data-component="button" href="/estate-planning">
 Lees meer...
 </Link>
 {" "}
 <br className="inline" />
 {" "}
 </p>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative pt-30 pb-60 bg-border" data-ditto-id="style-li-8">
 <div className="h-full block absolute top-0 inset-x-0 overflow-hidden [background-size:100%_100%] [background-position:50%_50%] bg-no-repeat pointer-events-none max-md:hidden" style={{ backgroundImage: "url(\"/assets/cloned/svg/38be1b42ada2.svg\")" }} data-ditto-id="style-link-14">
 Onze referenties
 </div>
 {" "}
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-font-26">
 <p className="block mb-4 text-center" data-ditto-id="style-font">
 We zijn in goed gezelschap.
 </p>
 {" "}
 <div className="flex -mx-[0.9375rem] flex-wrap justify-center max-md:[justify-content:initial]" data-ditto-id="style-li-4">
 <div className="w-95 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] md:max-lg:w-180 2xl:w-110" data-ditto-id="style-font-19">
 <img className="w-87.5 h-27.5 block max-w-full mx-auto overflow-clip object-contain align-middle max-md:w-[21.5625rem] max-md:h-[6.8125rem] md:max-lg:w-[38.8125rem] md:max-lg:h-49 2xl:w-102.5 2xl:h-[8.0625rem]" data-component="image" alt="AFAS Software" src="/assets/cloned/images/b156ac4438bd.png" />
 {" "}
 </div>
 {" "}
 <div className="w-95 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] md:max-lg:w-180 2xl:w-110" data-ditto-id="style-link-15">
 <img className="w-87.5 h-27.5 block max-w-full mx-auto overflow-clip object-contain align-middle max-md:w-[21.5625rem] max-md:h-[6.8125rem] md:max-lg:w-[38.8125rem] md:max-lg:h-49 2xl:w-102.5 2xl:h-[8.0625rem]" data-component="image" alt="Exact" src="/assets/cloned/images/491c04e46455.png" />
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 </div>
 {" "}
 </main>
 {" "}
 <footer className="block shrink-0 text-background bg-color-004" data-ditto-id="style-font-27" id="bottom">
 <div className="block" data-ditto-id="style-font-8" id="footer">
 <section className="block relative pt-8 pb-4" data-ditto-id="style-li-2">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 " data-ditto-id="style-font-33">
 <div className="flex -mx-[0.9375rem] flex-wrap items-end" data-ditto-id="style-font-2">
 <div className="w-[17.8125rem] h-[8.1rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[123.7px] md:max-lg:w-180 md:max-lg:h-[6.2rem] 2xl:w-82.5" data-ditto-id="style-li-12">
 <p className="block mb-2" data-ditto-id="style-link-16">
 <font className="inline" data-ditto-id="style-font-28">
 {" "}
 <font className="inline" data-ditto-id="style-font-34">
 Hoe kunnen we helpen
 </font>
 {" "}
 </font>
 {" "}
 <br className="inline" />
 {" "}
 </p>
 {" "}
 <h4 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-2xl font-bold leading-[1.8125rem] max-md:text-[1.375rem] max-md:leading-[1.625rem] md:max-lg:text-[1.4375rem] md:max-lg:leading-[1.6875rem]" data-ditto-id="style-font-17" data-component="heading">
 <font className="inline" data-ditto-id="style-font-11">
 {" "}
 <font className="inline" data-ditto-id="style-li-13">
 {"U kunt altijd contact met ons opnemen "}
 </font>
 {" "}
 </font>
 {" "}
 </h4>
 {" "}
 </div>
 {" "}
 <div className="w-[17.8125rem] h-[8.15rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[128.9px] md:max-lg:w-180 md:max-lg:h-[8.1rem] 2xl:w-82.5" data-ditto-id="style-link-17" aria-describedby="tooltip8305">
 <p className="block mb-2">
 <font className="inline" data-ditto-id="style-font-18">
 {" "}
 <font className="inline" data-ditto-id="style-div-2">
 Bel ons
 </font>
 {" "}
 </font>
 {" "}
 </p>
 {" "}
 <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-component="heading">
 <span className="inline" data-ditto-id="style-div-8">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-div-14" data-component="link" href="tel:31 (0) 33 46 11 447">
 {" "}
 <font className="inline" data-ditto-id="style-span-11">
 {" "}
 <font className="inline" data-ditto-id="style-p">
 {"+31 (0) 33 46 11 447 "}
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </span>
 {" "}
 </h5>
 {" "}
 <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-ditto-id="style-link-18" data-component="heading" aria-describedby="tooltip842231">
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-div-15" data-component="link" href="tel:31 (0) 33 46 11 447">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline" data-ditto-id="style-link-40">
 +31 (0) 6 11 23 88 30
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 <span className="inline" data-ditto-id="style-image">
 {" "}
 </span>
 {" "}
 </h5>
 {" "}
 </div>
 {" "}
 <div className="w-[17.8125rem] h-[6.075rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[6.025rem] md:max-lg:w-180 md:max-lg:h-[6.05rem] 2xl:w-82.5" data-ditto-id="style-link-19" aria-describedby="tooltip941693">
 <p className="block mb-2" data-ditto-id="style-website-cookies-bar">
 <font className="inline" data-ditto-id="style-div-26">
 {" "}
 <font className="inline">
 Stuur ons een bericht
 </font>
 {" "}
 </font>
 {" "}
 <br className="inline" data-ditto-id="style-div-27" />
 {" "}
 </p>
 {" "}
 <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-ditto-id="style-div-9" data-component="heading">
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-div-16" data-component="link" href="mailto:info@ahneta.nl">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline" data-ditto-id="style-link-21">
 info@ahneta.nl
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </h5>
 {" "}
 </div>
 {" "}
 <div className="w-[17.8125rem] h-[97.3px] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] md:max-lg:w-180 2xl:w-82.5" data-ditto-id="style-font-21">
 <div className="block text-right" data-ditto-id="style-font-36">
 <p className="block mr-[0.4rem] mb-2 align-middle">
 <font className="inline align-middle" data-ditto-id="style-font-20">
 {" "}
 <font className="inline align-middle">
 Volg ons
 </font>
 {" "}
 </font>
 {" "}
 </p>
 {" "}
 <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-li-6" data-component="link" href="https://www.ahneta.nl/website/social/twitter">
 {" "}
 <i className="flex m-1 justify-center items-center [font-family:FontAwesome-twitter-x-only] leading-4 before:content-[''] before:block before:w-4 before:h-4 before:text-primary before:text-base before:leading-4 before:text-right" data-ditto-id="style-link-22">
 ​
 </i>
 {" "}
 </a>
 {" "}
 <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-font-23" data-component="link" href="https://www.ahneta.nl/website/social/linkedin">
 {" "}
 <i className="flex m-1 justify-center items-center [font-family:FontAwesome] leading-4 before:content-[''] before:block before:w-[13.7px] before:h-4 before:text-primary before:text-base before:leading-4 before:text-right" aria-describedby="tooltip290654">
 ​
 </i>
 {" "}
 </a>
 {" "}
 <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-li-7" data-component="link" href="https://www.ahneta.nl/website/social/instagram">
 {" "}
 <i className="flex m-1 justify-center items-center [font-family:FontAwesome] leading-4 before:content-[''] before:block before:w-[13.7px] before:h-4 before:text-primary before:text-base before:leading-4 before:text-right">
 ​
 </i>
 {" "}
 </a>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 " data-ditto-id="style-li-5">
 <div className="block py-4 leading-0" data-ditto-id="style-link-23">
 <hr className="h-px border-t border-solid border-t-muted-foreground block overflow-hidden mx-auto w-[69.375rem] max-md:w-[21.5625rem] md:max-lg:w-[43.125rem] 2xl:w-[80.625rem]" />
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative" data-ditto-id="style-font-37">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 ">
 <div className="flex -mx-[0.9375rem] flex-wrap items-center" data-ditto-id="style-div-10" aria-describedby="tooltip859185">
 <div className="w-47.5 h-10 min-h-6 block max-w-full pb-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] md:max-lg:w-180 2xl:w-55">
 <Link className="inline text-primary cursor-pointer" data-component="link" href="/">
 {" "}
 <img className="w-0 h-px min-h-px inline max-w-full overflow-clip align-middle" data-ditto-id="style-span-18" data-component="image" alt="" aria-label="Şirketim logosu" role="img" src="/assets/cloned/images/1461683c0d67.png" title="Benim şirketim" />
 {" "}
 </Link>
 {" "}
 </div>
 {" "}
 <div className="w-237.5 h-10 min-h-6 block max-w-full pb-4 px-[0.9375rem] shrink-0 text-right max-md:w-[23.4375rem] max-md:h-16 md:max-lg:w-180 2xl:w-275" data-ditto-id="style-p-6" aria-describedby="tooltip611099">
 <ul className="h-full block [list-style-type:none] list-outside" data-ditto-id="style-link-24" aria-describedby="tooltip612522">
 <li className="inline-block mr-2" data-ditto-id="style-div-3">
 {" "}
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-div-17" data-component="link" href="/">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline">
 Home
 </font>
 {" "}
 </font>
 {" "}
 </Link>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-link-25">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block mr-2">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-div-18" data-component="link" href="#">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline">
 Over ons
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-avatar">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block mr-2">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-span-14" data-component="link" href="#">
 {" "}
 <font className="inline" data-ditto-id="style-span-21">
 {" "}
 <font className="inline" aria-describedby="tooltip841579">
 Product
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-span-19">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline" data-ditto-id="style-section-3">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block mr-2">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-div-19" data-component="link" href="#">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline" aria-describedby="tooltip455312">
 Gebruiksvoorwaarden
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-br-19">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block">
 {" "}
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-myquotecarousel617108" data-component="link" aria-describedby="tooltip848069" href="/privacy">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline" data-ditto-id="style-li-9">
 Privacybeleid
 </font>
 {" "}
 </font>
 {" "}
 </Link>
 {" "}
 </li>
 </ul>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 </div>
 {" "}
 <div className="block bg-color-005" data-ditto-id="style-li-10">
 <div className="block max-w-285 mx-auto py-4 px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 ">
 <div className="flex -mx-[0.9375rem] flex-wrap" data-ditto-id="style-footer-2">
 <div className="w-full block max-w-full px-[0.9375rem] grow shrink-0 basis-[0%] text-color-003 text-left max-md:text-center max-md:grow-[initial] max-md:basis-[initial]" data-ditto-id="style-section-4">
 <span className="inline align-middle">
 Copyright © Ahneta Advies
 </span>
 {" "}
 <p className="block mb-4">
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-div-20" data-component="link" href="/cookie-policy">
 Cookiebeleid
 </Link>
 </p>
 </div>
 {" "}
 <div className="w-142.5 block max-w-full my-[1.3125rem] px-[0.9375rem] grow shrink-0 basis-[0%] text-right max-md:w-[23.4375rem] max-md:text-center max-md:my-0 max-md:grow-[initial] max-md:basis-[initial] md:max-lg:w-90 md:max-lg:my-[0.5625rem] 2xl:w-165" data-ditto-id="style-p-5">
 <div className="h-full block">
 {" "}
 <a className="text-color-003 cursor-pointer hover:underline" href="https://imora.nl" target="_blank" rel="noopener noreferrer">
 Maintained by Imora
 </a>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </footer>
 {" "}
 <div className="block shrink-0" id="website_cookies_bar">
 {" "}
 </div>
 {" "}
 {" "}
 <div className="block">
 <div className="block" />
 <div className="block" />
 <div className="w-78 h-0 block absolute top-[52.9px] left-240 z-1055 max-md:left-[3.4375rem] md:max-lg:left-112 2xl:left-400" />
 <div className="w-78 h-0 block absolute top-[52.9px] left-240 z-1055 max-md:left-[3.4375rem] md:max-lg:left-112 2xl:left-400" data-ditto-id="style-font-38" />
 </div>
 </>
 );
}
