import "./ditto.css";
import Tile from "./components/tile";
import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
import Link from "next/link";
// Generated by clone-site. Do not edit by hand.
const Tile_data = [
 { text: "Lageprijsgarantie" },
 { text: "30 dagen online retourneren" },
 { text: "Standaard verzending" }
];
const ListRow_data = [
 { href: "/pricing", label: "Prijs" },
 { href: "/over-ons", label: "Over ons" },
 { href: "/contactus", label: "Contact" }
];
const ListRow2_data = [
 { text: "Advisering bij en de afhandeling van aangiftebiljetten recht van successie." },
 { text: "Advisering bij en afhandeling van aangiftebiljetten schenkingsrechten." },
 { text: "Advisering op gebied van Estate Planning (vermogensplanning)." },
 { text: "Advisering en afhandeling van de aangifte inkomstenbelasting." }
];
const Tile_meta: string[][] = [
 ["n10", "n11"],
 ["n12", "n13"],
 ["n14", "n15"]
];
const ListRow_meta: string[][] = [
 ["n48", "style-9", "style-15"],
 ["n51", "style-10", "style-16"],
 ["n54", "style-11", "style-17"]
];
const ListRow2_meta: string[][] = [
 ["n83"],
 ["style-span-5"],
 ["style-u"],
 ["style-br-10"]
];
const Tile_styles = [
 { className: "before:content-['']" },
 { className: "before:content-['']" },
 { className: "before:content-['']" }
];

export default function Page() {
 return (
 <>
 <main className="block grow shrink-0">
 <div className="h-full block" id="wrap">
 <div className="block">
 <section className="block relative py-6 overflow-hidden text-background bg-color-004">
 <span className="h-full block absolute top-0 inset-x-0 overflow-hidden bg-cover [background-position:50%_0px] bg-no-repeat [background-attachment:fixed] pointer-events-none max-lg:[background-attachment:initial]" style={{ backgroundImage: "url(\"/assets/cloned/images/2873c8e777c4.jpg\")" }} data-ditto-id="style-span-8" />
 {" "}
 <div className="h-full block absolute top-0 inset-x-0 overflow-hidden bg-color-004 bg-no-repeat pointer-events-none" data-ditto-id="style-div-28" />
 {" "}
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-div-33">
 <h1 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[3.875rem] font-bold leading-[4.625rem] max-md:text-4xl max-md:leading-[2.6875rem] md:max-lg:text-5xl md:max-lg:leading-[3.625rem]" data-ditto-id="style-heading-6" data-component="heading">
 Diensten Particulieren
 </h1>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 </div>
 {" "}
 <div className="block" data-ditto-id="style-div-29">
 <section className="block relative py-10 bg-border" data-ditto-id="style-section-5">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-div-30">
 <h1 className="block mb-2 text-color-005 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[3.875rem] font-bold leading-[4.625rem] text-center max-md:text-4xl max-md:leading-[2.6875rem] md:max-lg:text-5xl md:max-lg:leading-[3.625rem]" data-ditto-id="style-p-2" data-component="heading">
 <font className="inline text-color-010 max-lg:text-[3.875rem] max-lg:leading-[4.625rem]" data-ditto-id="style-br-4">
 Ahneta Advies is gespecialiseerd in:
 </font>
 {" "}
 <br className="inline" data-ditto-id="style-span-20" />
 {" "}
 </h1>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative py-10" data-ditto-id="style-span-6">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-br-5">
 <ul className="block mb-4 pl-8 [list-style-type:disc] list-outside">
 {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} />)}
 <li className="list-item" data-ditto-id="style-br-3">
 Advisering en afhandeling van bezwaar- en beroepschriften.
 <br className="inline" data-ditto-id="style-span-7" />
 <br className="inline" data-ditto-id="style-br-15" />
 Ahneta is geen groot bedrijf en hiervoor is bewust gekozen. Hierdoor hebben wij voldoende tijd voor u en kunnen wij u beter van dienst zijn met een persoonlijk advies.
 <br className="inline" data-ditto-id="style-br-7" />
 <br className="inline" data-ditto-id="style-span-10" />
 Door deze keuze hebben wij ook lage overheadkosten waardoor wij de tarieven van onze dienstverlening aantrekkelijk kunnen houden.
 <br className="inline" />
 </li>
 </ul>
 {" "}
 <p className="block mb-4">
 <br className="inline" />
 {" "}
 </p>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative" data-ditto-id="style-br-2">
 <div className="block relative bg-border" data-ditto-id="style-br-9" id="myQuoteCarousel617108">
 <ol className="h-[1.1rem] flex absolute bottom-0 inset-x-0 z-2 mb-4 mx-48 justify-center [list-style-type:none] list-outside max-md:mx-[56.3px] md:max-lg:mx-[7.2rem] " data-ditto-id="style-span-9">
 <li className="box-content w-7.5 h-[0.6rem] list-item mb-2 mx-[0.1875rem] rounded-[4.8px] indent-[-999px] bg-background [background-clip:padding-box] shadow-[var(--color-006)_0px_1px_3px_0px] [-webkit-background-clip:padding-box] cursor-pointer" data-ditto-id="style-br-8" />
 <li className="box-content w-7.5 h-[0.6rem] list-item opacity-50 mb-2 mx-[0.1875rem] rounded-[4.8px] indent-[-999px] bg-background [background-clip:padding-box] shadow-[var(--color-006)_0px_1px_3px_0px] [-webkit-background-clip:padding-box] cursor-pointer" data-ditto-id="style-br-18" />
 <li className="box-content w-7.5 h-[0.6rem] list-item opacity-50 mb-2 mx-[0.1875rem] rounded-[4.8px] indent-[-999px] bg-background [background-clip:padding-box] shadow-[var(--color-006)_0px_1px_3px_0px] [-webkit-background-clip:padding-box] cursor-pointer" data-ditto-id="style-span-15" />
 </ol>
 {" "}
 <div className="block relative isolate overflow-hidden after:content-[''] after:block after:w-full after:h-0" data-ditto-id="style-br-17">
 <div className="w-full h-88.5 min-h-88.5 block relative float-left -mr-320 py-20 bg-cover [background-position:50%_50%] bg-no-repeat max-lg:h-[440.3px] max-lg:min-h-[440.3px] max-md:-mr-[23.4375rem] md:max-lg:-mr-192 2xl:-mr-480" style={{ backgroundImage: "url(\"/assets/cloned/images/647d672ef452.jpg\")" }} data-ditto-id="style-br-12">
 <div className="h-full block absolute top-0 inset-x-0 overflow-hidden text-background bg-color-004 bg-no-repeat pointer-events-none" data-ditto-id="style-span-13" />
 {" "}
 <div className="h-full block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-br">
 <blockquote className="h-full block mx-auto text-xl italic leading-7.5 w-[34.6875rem] max-lg:w-[21.5625rem] 2xl:w-[40.3125rem]">
 <i className="w-12 h-12 block float-left rounded-tl-md rounded-bl-md align-middle text-background [font-family:FontAwesome] text-base not-italic leading-12 text-center bg-accent before:content-[''] before:text-background before:text-base before:leading-12 before:text-center" />
 {" "}
 <div className="h-full block p-6 overflow-hidden bg-background" data-ditto-id="style-br-22">
 <p className="block mb-4" data-ditto-id="style-br-13">
 Schrijf hier een citaat van één van je klanten. Citaten zijn een geweldige manier om het vertrouwen in je producten of diensten te vergroten.
 </p>
 {" "}
 <footer className="block text-muted-foreground text-lg leading-[1.625rem] before:content-['']" data-ditto-id="style-span-22">
 <img className="w-10 h-10 inline max-h-10 mr-2 rounded-[50%] overflow-clip align-middle" data-ditto-id="style-br-21" data-component="avatar" alt="" src="/assets/cloned/images/e964d90c8602.jpg" />
 {" "}
 <span className="inline opacity-75">
 <b className="inline font-bold" data-ditto-id="style-span-12">
 Jane DOE
 </b>
 {" • CEO of MyCompany"}
 </span>
 {" "}
 </footer>
 {" "}
 </div>
 {" "}
 </blockquote>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 <div className="h-full flex absolute top-0 right-[73.6rem] left-0 z-1 justify-start items-center text-background text-center cursor-pointer max-md:hidden md:max-lg:right-[44.1625rem] 2xl:right-[110.4rem]" data-ditto-id="style-u-2" aria-label="Vorige" role="img" title="Vorige">
 <span className="w-[46.9px] h-12 block text-foreground [font-family:FontAwesome] [background-size:100%_100%] [background-position:50%_50%] bg-no-repeat md:max-lg:w-11 md:max-lg:h-[2.6375rem] before:content-[''] before:inline-block before:w-[22.9px] before:h-12 before:ml-6 before:text-background before:text-[2rem] before:leading-12 before:text-center max-md:before:text-[1.5625rem] max-md:before:leading-[2.3125rem] max-md:before:w-auto max-md:before:h-auto md:max-lg:before:w-5 md:max-lg:before:h-[2.6375rem] md:max-lg:before:text-[1.75rem] md:max-lg:before:leading-[2.625rem]" />
 {" "}
 <span className="w-px h-px block absolute top-[177.5px] left-0 min-w-0 -m-px overflow-hidden whitespace-nowrap text-nowrap" data-ditto-id="style-br-14">
 Vorige
 </span>
 {" "}
 </div>
 {" "}
 <div className="h-full flex absolute top-0 right-0 left-[73.6rem] z-1 justify-end items-center text-background text-center cursor-pointer max-md:hidden md:max-lg:left-[44.1625rem] 2xl:left-[110.4rem]" aria-label="Volgende" role="img" title="Volgende">
 <span className="w-[46.9px] h-12 block text-foreground [font-family:FontAwesome] [background-size:100%_100%] [background-position:50%_50%] bg-no-repeat md:max-lg:w-11 md:max-lg:h-[2.6375rem] before:content-[''] before:inline-block before:w-[22.9px] before:h-12 before:mr-6 before:text-background before:text-[2rem] before:leading-12 before:text-center max-md:before:text-[1.5625rem] max-md:before:leading-[2.3125rem] max-md:before:w-auto max-md:before:h-auto md:max-lg:before:w-5 md:max-lg:before:h-[2.6375rem] md:max-lg:before:text-[1.75rem] md:max-lg:before:leading-[2.625rem]" data-ditto-id="style-br-16" />
 {" "}
 <span className="w-px h-px block absolute left-[3.2rem] min-w-0 -m-px overflow-hidden whitespace-nowrap text-nowrap md:max-lg:left-[30.7px] 2xl:left-[4.8rem]" data-ditto-id="style-br-6">
 Volgende
 </span>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </main>
 {" "}
 <footer className="block shrink-0 text-background bg-color-004" id="bottom">
 <div className="block" data-ditto-id="style-bottom" id="footer">
 <section className="block relative pt-8 pb-4" data-ditto-id="style-footer">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 " data-ditto-id="style-section">
 <div className="flex -mx-[0.9375rem] flex-wrap items-end" data-ditto-id="style-div-31">
 <div className="w-[17.8125rem] h-[8.1rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[123.7px] md:max-lg:w-180 md:max-lg:h-[6.2rem] 2xl:w-82.5" data-ditto-id="style-div-7">
 <p className="block mb-2" data-ditto-id="style-div-32">
 <font className="inline" data-ditto-id="style-p-3">
 {" "}
 <font className="inline" data-ditto-id="style-font-12">
 Hoe kunnen we helpen
 </font>
 {" "}
 </font>
 {" "}
 <br className="inline" data-ditto-id="style-font-9" />
 {" "}
 </p>
 {" "}
 <h4 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-2xl font-bold leading-[1.8125rem] max-md:text-[1.375rem] max-md:leading-[1.625rem] md:max-lg:text-[1.4375rem] md:max-lg:leading-[1.6875rem]" data-ditto-id="style-br-23" data-component="heading">
 <font className="inline" data-ditto-id="style-heading-5">
 {" "}
 <font className="inline" data-ditto-id="style-font-13">
 {"U kunt altijd contact met ons opnemen "}
 </font>
 {" "}
 </font>
 {" "}
 </h4>
 {" "}
 </div>
 {" "}
 <div className="w-[17.8125rem] h-[8.15rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[128.9px] md:max-lg:w-180 md:max-lg:h-[8.1rem] 2xl:w-82.5" data-ditto-id="style-font-3" aria-describedby="tooltip8305">
 <p className="block mb-2" data-ditto-id="style-div">
 <font className="inline" data-ditto-id="style-p-4">
 {" "}
 <font className="inline" data-ditto-id="style-font-41">
 Bel ons
 </font>
 {" "}
 </font>
 {" "}
 </p>
 {" "}
 <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-component="heading">
 <span className="inline" data-ditto-id="style-heading-3">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-span-17" data-component="link" href="tel:31 (0) 33 46 11 447">
 {" "}
 <font className="inline" data-ditto-id="style-link-6">
 {" "}
 <font className="inline" data-ditto-id="style-font-4">
 {"+31 (0) 33 46 11 447 "}
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </span>
 {" "}
 </h5>
 {" "}
 <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-ditto-id="style-font-14" data-component="heading" aria-describedby="tooltip842231">
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-heading" data-component="link" href="tel:31 (0) 33 46 11 447">
 {" "}
 <font className="inline" data-ditto-id="style-link-7">
 {" "}
 <font className="inline" data-ditto-id="style-font-5">
 +31 (0) 6 11 23 88 30
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 <span className="inline" data-ditto-id="style-font-42">
 {" "}
 </span>
 {" "}
 </h5>
 {" "}
 </div>
 {" "}
 <div className="w-[17.8125rem] h-[6.075rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[6.025rem] md:max-lg:w-180 md:max-lg:h-[6.05rem] 2xl:w-82.5" data-ditto-id="style-span-16" aria-describedby="tooltip941693">
 <p className="block mb-2" data-ditto-id="style-div-13">
 <font className="inline">
 {" "}
 <font className="inline" data-ditto-id="style-font-15">
 Stuur ons een bericht
 </font>
 {" "}
 </font>
 {" "}
 <br className="inline" data-ditto-id="style-font-10" />
 {" "}
 </p>
 {" "}
 <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-ditto-id="style-br-11" data-component="heading">
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-heading-2" data-component="link" href="mailto:info@ahneta.nl">
 {" "}
 <font className="inline" data-ditto-id="style-link-8">
 {" "}
 <font className="inline" data-ditto-id="style-font-6">
 info@ahneta.nl
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </h5>
 {" "}
 </div>
 {" "}
 <div className="w-[17.8125rem] h-[97.3px] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] md:max-lg:w-180 2xl:w-82.5" data-ditto-id="style-font-24">
 <div className="block text-right" data-ditto-id="style-div-22">
 <p className="block mr-[0.4rem] mb-2 align-middle" data-ditto-id="style-div-11">
 <font className="inline align-middle" data-ditto-id="style-p-7">
 {" "}
 <font className="inline align-middle" data-ditto-id="style-font-7">
 Volg ons
 </font>
 {" "}
 </font>
 {" "}
 </p>
 {" "}
 <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-font-35" data-component="link" href="https://www.ahneta.nl/website/social/twitter">
 {" "}
 <i className="flex m-1 justify-center items-center [font-family:FontAwesome-twitter-x-only] leading-4 before:content-[''] before:block before:w-4 before:h-4 before:text-primary before:text-base before:leading-4 before:text-right" data-ditto-id="style-link-9">
 ​
 </i>
 {" "}
 </a>
 {" "}
 <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-i-3" data-component="link" href="https://www.ahneta.nl/website/social/linkedin">
 {" "}
 <i className="flex m-1 justify-center items-center [font-family:FontAwesome] leading-4 before:content-[''] before:block before:w-[13.7px] before:h-4 before:text-primary before:text-base before:leading-4 before:text-right" data-ditto-id="style-link-10" aria-describedby="tooltip290654">
 ​
 </i>
 {" "}
 </a>
 {" "}
 <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-i-2" data-component="link" href="https://www.ahneta.nl/website/social/instagram">
 {" "}
 <i className="flex m-1 justify-center items-center [font-family:FontAwesome] leading-4 before:content-[''] before:block before:w-[13.7px] before:h-4 before:text-primary before:text-base before:leading-4 before:text-right" data-ditto-id="style-link-11">
 ​
 </i>
 {" "}
 </a>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative" data-ditto-id="style-i">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 " data-ditto-id="style-section-2">
 <div className="block py-4 leading-0" data-ditto-id="style-div-6">
 <hr className="h-px border-t border-solid border-t-muted-foreground block overflow-hidden mx-auto w-[69.375rem] max-md:w-[21.5625rem] md:max-lg:w-[43.125rem] 2xl:w-[80.625rem]" data-ditto-id="style-div-5" />
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative" data-ditto-id="style-hr">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 " data-ditto-id="style-section-6">
 <div className="flex -mx-[0.9375rem] flex-wrap items-center" data-ditto-id="style-div-34" aria-describedby="tooltip859185">
 <div className="w-47.5 h-[6.3125rem] min-h-6 block max-w-full pb-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-lg:h-34 md:max-lg:w-180 2xl:w-55 2xl:h-[116.9px]" data-ditto-id="style-div-4">
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-div-21" data-component="link" href="/">
 {" "}
 <img className="w-40 h-[5.3125rem] inline max-w-full overflow-clip align-middle max-lg:w-56.5 max-lg:h-30 2xl:w-47.5 2xl:h-[6.3125rem]" data-ditto-id="style-link-12" data-component="image" alt="" aria-label="Şirketim logosu" role="img" src="/assets/cloned/images/1461683c0d67.png" title="Benim şirketim" />
 {" "}
 </Link>
 {" "}
 </div>
 {" "}
 <div className="w-237.5 h-10 min-h-6 block max-w-full pb-4 px-[0.9375rem] shrink-0 text-right max-md:w-[23.4375rem] max-md:h-16 md:max-lg:w-180 2xl:w-275" data-ditto-id="style-irketim-logosu" aria-describedby="tooltip611099">
 <ul className="h-full block [list-style-type:none] list-outside" data-ditto-id="style-div-12" aria-describedby="tooltip612522">
 <li className="inline-block mr-2" data-ditto-id="style-ul">
 {" "}
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-li" data-component="link" href="/">
 {" "}
 <font className="inline" data-ditto-id="style-link-13">
 {" "}
 <font className="inline" data-ditto-id="style-font-25">
 Home
 </font>
 {" "}
 </font>
 {" "}
 </Link>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-font-16">
 {" "}
 <font className="inline" data-ditto-id="style-li-3">
 {" "}
 <font className="inline" data-ditto-id="style-font-22">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block mr-2">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-li-8" data-component="link" href="#">
 {" "}
 <font className="inline" data-ditto-id="style-link-14">
 {" "}
 <font className="inline" data-ditto-id="style-font-26">
 Over ons
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-font">
 {" "}
 <font className="inline" data-ditto-id="style-li-4">
 {" "}
 <font className="inline" data-ditto-id="style-font-19">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-font-43">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-li-11" data-component="link" href="#">
 {" "}
 <font className="inline" data-ditto-id="style-link-15">
 {" "}
 <font className="inline" data-ditto-id="style-font-27" aria-describedby="tooltip841579">
 Product
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-font-8">
 {" "}
 <font className="inline" data-ditto-id="style-li-2">
 {" "}
 <font className="inline" data-ditto-id="style-font-33">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-font-2">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-li-12" data-component="link" href="#">
 {" "}
 <font className="inline" data-ditto-id="style-link-16">
 {" "}
 <font className="inline" data-ditto-id="style-font-28" aria-describedby="tooltip455312">
 Gebruiksvoorwaarden
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-font-34">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline" data-ditto-id="style-font-17">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block" data-ditto-id="style-font-11">
 {" "}
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-li-13" data-component="link" aria-describedby="tooltip848069" href="/privacy">
 {" "}
 <font className="inline" data-ditto-id="style-link-17">
 {" "}
 <font className="inline">
 Privacybeleid
 </font>
 {" "}
 </font>
 {" "}
 </Link>
 {" "}
 </li>
 </ul>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 </div>
 {" "}
 <div className="block bg-color-005" data-ditto-id="style-font-18">
 <div className="block max-w-285 mx-auto py-4 px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 " data-ditto-id="style-div-2">
 <div className="flex -mx-[0.9375rem] flex-wrap">
 <div className="w-full block max-w-full px-[0.9375rem] grow shrink-0 basis-[0%] text-color-003 text-left max-md:text-center max-md:grow-[initial] max-md:basis-[initial]" data-ditto-id="style-div-8">
 <span className="inline align-middle" data-ditto-id="style-div-14">
 Copyright © Ahneta Advies
 </span>
 {" "}
 <p className="block mb-4" data-ditto-id="style-span-11">
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-p" data-component="link" href="/cookie-policy">
 Cookiebeleid
 </Link>
 </p>
 </div>
 {" "}
 <div className="w-142.5 block max-w-full my-[1.3125rem] px-[0.9375rem] grow shrink-0 basis-[0%] text-right max-md:w-[23.4375rem] max-md:text-center max-md:my-0 max-md:grow-[initial] max-md:basis-[initial] md:max-lg:w-90 md:max-lg:my-[0.5625rem] 2xl:w-165" data-ditto-id="style-link-18">
 <div className="h-full block" data-ditto-id="style-div-15">
 {" "}
 <a className="text-color-003 cursor-pointer hover:underline" href="https://imora.nl" target="_blank" rel="noopener noreferrer">
 Maintained by Imora
 </a>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </footer>
 {" "}
 <div className="block shrink-0" data-ditto-id="style-link-19" id="website_cookies_bar">
 {" "}
 </div>
 {" "}
 {" "}
 <div className="block" data-ditto-id="style-website-cookies-bar">
 <div className="block" data-ditto-id="style-div-26" />
 <div className="block" />
 <div className="w-78 h-0 block absolute top-[52.9px] left-240 z-1055 max-md:left-[3.4375rem] md:max-lg:left-112 2xl:left-400" data-ditto-id="style-div-27" />
 <div className="w-78 h-0 block absolute top-[52.9px] left-240 z-1055 max-md:left-[3.4375rem] md:max-lg:left-112 2xl:left-400" data-ditto-id="style-div-9" />
 </div>
 </>
 );
}
