import "./ditto.css";
import Tile from "./components/tile";
import ListRow from "./components/list-row";
import Link from "next/link";
// Generated by clone-site. Do not edit by hand.
const Tile_data = [
 { text: "Lageprijsgarantie" },
 { text: "30 dagen online retourneren" },
 { text: "Standaard verzending" }
];
const ListRow_data = [
 { href: "/pricing", label: "Prijs" },
 { href: "/over-ons", label: "Over ons" },
 { href: "/contactus", label: "Contact" }
];
const Tile_meta: string[][] = [
 ["n10", "n11"],
 ["n12", "n13"],
 ["n14", "n15"]
];
const ListRow_meta: string[][] = [
 ["n48", "style-9", "style-15"],
 ["n51", "style-10", "style-16"],
 ["n54", "style-11", "style-17"]
];
const Tile_styles = [
 { className: "before:content-['']" },
 { className: "before:content-['']" },
 { className: "before:content-['']" }
];

export default function Page() {
 return (
 <>
 <main className="block grow shrink-0">
 <div className="h-full block" id="wrap">
 <div className="block">
 <section className="block relative py-6 overflow-hidden text-background bg-color-004">
 <span className="h-full block absolute top-0 inset-x-0 overflow-hidden bg-cover [background-position:50%_0px] bg-no-repeat [background-attachment:fixed] pointer-events-none max-lg:[background-attachment:initial]" style={{ backgroundImage: "url(\"/assets/cloned/images/2873c8e777c4.jpg\")" }} data-ditto-id="style-span-8" />
 {" "}
 <div className="h-full block absolute top-0 inset-x-0 overflow-hidden bg-color-004 bg-no-repeat pointer-events-none" data-ditto-id="style-div-28" />
 {" "}
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-div-33">
 <h1 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[3.875rem] font-bold leading-[4.625rem] max-md:text-4xl max-md:leading-[2.6875rem] md:max-lg:text-5xl md:max-lg:leading-[3.625rem]" data-ditto-id="style-heading-6" data-component="heading">
 Aangifte Inkomstenbelasting
 </h1>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 </div>
 {" "}
 <div className="block" data-ditto-id="style-div-29">
 <section className="block relative py-10 bg-background" data-ditto-id="style-section-5">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-div-30">
 <p className="block mb-4" data-ditto-id="style-p-2">
 <br className="inline" data-ditto-id="style-br-4" />
 <span className="inline font-bold" data-ditto-id="style-span-20">
 <span className="inline text-lg leading-[1.6875rem]" data-ditto-id="style-span-6">
 Aangifte Inkomstenbelasting
 </span>
 <br className="inline" data-ditto-id="style-br-5" />
 Zoals u op de welkomstpagina al hebt kunnen lezen biedt Ahneta veel diensten aan voor de particuliere cliënten. Eén daarvan is de verzorging van de aangifte inkomstenbelasting en de afhandeling van eventuele bezwaar- en beroepsschriften.
 </span>
 <br className="inline" />
 <br className="inline" />
 <span className="inline font-bold" data-ditto-id="style-span-5">
 <u className="inline underline" data-ditto-id="style-u">
 Advisering en afhandeling van de aangifte inkomstenbelasting.
 </u>
 </span>
 <br className="inline" data-ditto-id="style-br-10" />
 <br className="inline" data-ditto-id="style-br-3" />
 <span className="inline" data-ditto-id="style-span-7">
 Iedereen in ons land die inkomsten heeft is met deze vorm van belasting bekend. Op uw loon of uw uitkering of pensioen wordt loonheffing ingehouden. Dit is het voorportaal van de inkomstenbelasting. Als u jaarlijks aangifte doet en u krijgt een aanslag van de Belastingdienst toegezonden heet het ineens Inkomstenbelasting.
 </span>
 <br className="inline" data-ditto-id="style-br-15" />
 <br className="inline" data-ditto-id="style-br-7" />
 <span className="inline" data-ditto-id="style-span-10">
 Dit komt omdat inkomstenbelasting niet alleen gaat over uw inkomsten maar ook over uw aftrekposten voor de inkomstenbelasting, dit deel heet sinds 2001 box 1.
 </span>
 <br className="inline" />
 <br className="inline" />
 <span className="inline">
 Voor de inkomstenbelasting kunt u ook te maken hebben met inkomsten uit box 2. Met dit deel van de inkomstenbelasting heeft u alleen te maken als er sprake is van een zogenaamd ‘aanmerkelijk belang’.
 </span>
 <br className="inline" data-ditto-id="style-br-2" />
 <br className="inline" data-ditto-id="style-br-9" />
 <span className="inline" data-ditto-id="style-span-9">
 U heeft een aanmerkelijk belang als u minimaal 5% van de aandelen, opties of winstbewijzen in een vennootschap of een coöperatie heeft. Ook is er sprake van een aanmerkelijk belang als u samen met uw fiscale partner minimaal 5% van het totaal heeft. Het gaat om aandelen, opties of winstbewijzen in een B.V. of N.V., in een andere binnenlandse of buitenlandse vennootschap of om het lidmaatschap van een coöperatie.
 </span>
 <br className="inline" data-ditto-id="style-br-8" />
 <br className="inline" data-ditto-id="style-br-18" />
 <span className="inline" data-ditto-id="style-span-15">
 Heeft u en aanmerkelijk belang, dan moet u belasting betalen over het voordeel daarvan.
 </span>
 <br className="inline" data-ditto-id="style-br-17" />
 <br className="inline" data-ditto-id="style-br-12" />
 <span className="inline" data-ditto-id="style-span-13">
 Ook kunt u inkomsten genieten die voor de inkomstenbelastingvallen in box 3. Met dit deel van de inkomstenbelasting heeft u te maken als uw vermogen meer bedraagt dan de vrijstelling die voor u van toepassing is.
 </span>
 <br className="inline" data-ditto-id="style-br" />
 <br className="inline" />
 <span className="inline">
 De standaard vrijstelling voor 2007 is € 20.014,00 Bent u gehuwd of woont u samen en heeft u gekozen voor fiscaal partnerschap dan heeft u recht op 2x de standaard vrijstelling. Heeft u een kind of kinderen is de vrijstelling nog hoger. Let wel het gaat hierbij om uw totaal vermogen dus uw bezittingen minus uw schulden.
 </span>
 <br className="inline" data-ditto-id="style-br-22" />
 <br className="inline" data-ditto-id="style-br-13" />
 <span className="inline" data-ditto-id="style-span-22">
 De waarde van uw woonhuis en de daarop rustende hypotheek zijn vrijgesteld van opname in box 3. Heeft u nog een vakantiewoning – eventueel met hypotheek – moet die tweede woning wel vermeld worden als bezitting in box 3. Heeft u veel spaargeld en een kleine hypotheek kan het interessant zijn om de hypotheek af te lossen.
 </span>
 <br className="inline" data-ditto-id="style-br-21" />
 <br className="inline" />
 <span className="inline font-bold" data-ditto-id="style-span-12">
 <u className="inline underline" data-ditto-id="style-u-2">
 Advisering en afhandeling van bezwaar- en beroepschriften.
 </u>
 </span>
 <br className="inline" />
 <br className="inline" data-ditto-id="style-br-14" />
 <span className="inline">
 Hoe zorgvuldig uw aangiftebiljet ook wordt ingevuld er bestaat altijd de kans dat de belastingdienst niet instemt met de opgevoerde aftrekposten. Voorafgaand aan de afwijzing van aftrekposten heeft er veelal al overleg plaatsgevonden met de belastingdienst over de opgevoerde aftrekposten, op basis van die informatie bepaald de belastingdienst haar standpunt.
 </span>
 <br className="inline" data-ditto-id="style-br-16" />
 <br className="inline" data-ditto-id="style-br-6" />
 Voor cliënten van Ahneta hanteren wij voor bezwaarschriften het principe van ‘no cure, no pay’. Wordt het bezwaarschrift toegewezen dan proberen wij op basis van de bestaande jurisprudentie de kosten van de bezwaarschriftprocedure van de belastingdienst vergoed te krijgen. Lukt dit niet dan wordt bij positief resultaat de kosten voor de bezwaarschriftprocedure aan u in rekening gebracht. Ahneta verzorgt ook beroepsprocedures bij de belastingkamer van de Rechtbanken in Nederland. De werkwijze en kostenberekening is gelijk aan die voorwaarden die gelden voor de afhandeling van bezwaarschriften.
 <br className="inline" />
 </p>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </main>
 {" "}
 <footer className="block shrink-0 text-background bg-color-004" data-ditto-id="style-bottom" id="bottom">
 <div className="block" data-ditto-id="style-footer" id="footer">
 <section className="block relative pt-8 pb-4" data-ditto-id="style-section">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 " data-ditto-id="style-div-31">
 <div className="flex -mx-[0.9375rem] flex-wrap items-end" data-ditto-id="style-div-7">
 <div className="w-[17.8125rem] h-[8.1rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[123.7px] md:max-lg:w-180 md:max-lg:h-[6.2rem] 2xl:w-82.5" data-ditto-id="style-div-32">
 <p className="block mb-2" data-ditto-id="style-p-3">
 <font className="inline" data-ditto-id="style-font-12">
 {" "}
 <font className="inline" data-ditto-id="style-font-9">
 Hoe kunnen we helpen
 </font>
 {" "}
 </font>
 {" "}
 <br className="inline" data-ditto-id="style-br-23" />
 {" "}
 </p>
 {" "}
 <h4 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-2xl font-bold leading-[1.8125rem] max-md:text-[1.375rem] max-md:leading-[1.625rem] md:max-lg:text-[1.4375rem] md:max-lg:leading-[1.6875rem]" data-ditto-id="style-heading-5" data-component="heading">
 <font className="inline" data-ditto-id="style-font-13">
 {" "}
 <font className="inline" data-ditto-id="style-font-3">
 {"U kunt altijd contact met ons opnemen "}
 </font>
 {" "}
 </font>
 {" "}
 </h4>
 {" "}
 </div>
 {" "}
 <div className="w-[17.8125rem] h-[8.15rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[128.9px] md:max-lg:w-180 md:max-lg:h-[8.1rem] 2xl:w-82.5" data-ditto-id="style-div" aria-describedby="tooltip8305">
 <p className="block mb-2" data-ditto-id="style-p-4">
 <font className="inline" data-ditto-id="style-font-41">
 {" "}
 <font className="inline">
 Bel ons
 </font>
 {" "}
 </font>
 {" "}
 </p>
 {" "}
 <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-ditto-id="style-heading-3" data-component="heading">
 <span className="inline" data-ditto-id="style-span-17">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-link-6" data-component="link" href="tel:31 (0) 33 46 11 447">
 {" "}
 <font className="inline" data-ditto-id="style-font-4">
 {" "}
 <font className="inline" data-ditto-id="style-font-14">
 {"+31 (0) 33 46 11 447 "}
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </span>
 {" "}
 </h5>
 {" "}
 <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-ditto-id="style-heading" data-component="heading" aria-describedby="tooltip842231">
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-link-7" data-component="link" href="tel:31 (0) 33 46 11 447">
 {" "}
 <font className="inline" data-ditto-id="style-font-5">
 {" "}
 <font className="inline" data-ditto-id="style-font-42">
 +31 (0) 6 11 23 88 30
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 <span className="inline" data-ditto-id="style-span-16">
 {" "}
 </span>
 {" "}
 </h5>
 {" "}
 </div>
 {" "}
 <div className="w-[17.8125rem] h-[6.075rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[6.025rem] md:max-lg:w-180 md:max-lg:h-[6.05rem] 2xl:w-82.5" data-ditto-id="style-div-13" aria-describedby="tooltip941693">
 <p className="block mb-2">
 <font className="inline" data-ditto-id="style-font-15">
 {" "}
 <font className="inline" data-ditto-id="style-font-10">
 Stuur ons een bericht
 </font>
 {" "}
 </font>
 {" "}
 <br className="inline" data-ditto-id="style-br-11" />
 {" "}
 </p>
 {" "}
 <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-ditto-id="style-heading-2" data-component="heading">
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-link-8" data-component="link" href="mailto:info@ahneta.nl">
 {" "}
 <font className="inline" data-ditto-id="style-font-6">
 {" "}
 <font className="inline" data-ditto-id="style-font-24">
 info@ahneta.nl
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </h5>
 {" "}
 </div>
 {" "}
 <div className="w-[17.8125rem] h-[97.3px] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] md:max-lg:w-180 2xl:w-82.5" data-ditto-id="style-div-22">
 <div className="block text-right" data-ditto-id="style-div-11">
 <p className="block mr-[0.4rem] mb-2 align-middle" data-ditto-id="style-p-7">
 <font className="inline align-middle" data-ditto-id="style-font-7">
 {" "}
 <font className="inline align-middle" data-ditto-id="style-font-35">
 Volg ons
 </font>
 {" "}
 </font>
 {" "}
 </p>
 {" "}
 <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-link-9" data-component="link" href="https://www.ahneta.nl/website/social/twitter">
 {" "}
 <i className="flex m-1 justify-center items-center [font-family:FontAwesome-twitter-x-only] leading-4 before:content-[''] before:block before:w-4 before:h-4 before:text-primary before:text-base before:leading-4 before:text-right" data-ditto-id="style-i-3">
 ​
 </i>
 {" "}
 </a>
 {" "}
 <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-link-10" data-component="link" href="https://www.ahneta.nl/website/social/linkedin">
 {" "}
 <i className="flex m-1 justify-center items-center [font-family:FontAwesome] leading-4 before:content-[''] before:block before:w-[13.7px] before:h-4 before:text-primary before:text-base before:leading-4 before:text-right" data-ditto-id="style-i-2" aria-describedby="tooltip290654">
 ​
 </i>
 {" "}
 </a>
 {" "}
 <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-link-11" data-component="link" href="https://www.ahneta.nl/website/social/instagram">
 {" "}
 <i className="flex m-1 justify-center items-center [font-family:FontAwesome] leading-4 before:content-[''] before:block before:w-[13.7px] before:h-4 before:text-primary before:text-base before:leading-4 before:text-right" data-ditto-id="style-i">
 ​
 </i>
 {" "}
 </a>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative" data-ditto-id="style-section-2">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 " data-ditto-id="style-div-6">
 <div className="block py-4 leading-0" data-ditto-id="style-div-5">
 <hr className="h-px border-t border-solid border-t-muted-foreground block overflow-hidden mx-auto w-[69.375rem] max-md:w-[21.5625rem] md:max-lg:w-[43.125rem] 2xl:w-[80.625rem]" data-ditto-id="style-hr" />
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative" data-ditto-id="style-section-6">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 " data-ditto-id="style-div-34">
 <div className="flex -mx-[0.9375rem] flex-wrap items-center" data-ditto-id="style-div-4" aria-describedby="tooltip859185">
 <div className="w-47.5 h-[6.3125rem] min-h-6 block max-w-full pb-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-lg:h-34 md:max-lg:w-180 2xl:w-55 2xl:h-[116.9px]" data-ditto-id="style-div-21">
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-link-12" data-component="link" href="/">
 {" "}
 <img className="w-40 h-[5.3125rem] inline max-w-full overflow-clip align-middle max-lg:w-56.5 max-lg:h-30 2xl:w-47.5 2xl:h-[6.3125rem]" data-ditto-id="style-irketim-logosu" data-component="image" alt="" aria-label="Şirketim logosu" role="img" src="/assets/cloned/images/1461683c0d67.png" title="Benim şirketim" />
 {" "}
 </Link>
 {" "}
 </div>
 {" "}
 <div className="w-237.5 h-10 min-h-6 block max-w-full pb-4 px-[0.9375rem] shrink-0 text-right max-md:w-[23.4375rem] max-md:h-16 md:max-lg:w-180 2xl:w-275" data-ditto-id="style-div-12" aria-describedby="tooltip611099">
 <ul className="h-full block [list-style-type:none] list-outside" data-ditto-id="style-ul" aria-describedby="tooltip612522">
 <li className="inline-block mr-2" data-ditto-id="style-li">
 {" "}
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-link-13" data-component="link" href="/">
 {" "}
 <font className="inline" data-ditto-id="style-font-25">
 {" "}
 <font className="inline" data-ditto-id="style-font-16">
 Home
 </font>
 {" "}
 </font>
 {" "}
 </Link>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-li-3">
 {" "}
 <font className="inline" data-ditto-id="style-font-22">
 {" "}
 <font className="inline">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-li-8">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-link-14" data-component="link" href="#">
 {" "}
 <font className="inline" data-ditto-id="style-font-26">
 {" "}
 <font className="inline" data-ditto-id="style-font">
 Over ons
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-li-4">
 {" "}
 <font className="inline" data-ditto-id="style-font-19">
 {" "}
 <font className="inline" data-ditto-id="style-font-43">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-li-11">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-link-15" data-component="link" href="#">
 {" "}
 <font className="inline" data-ditto-id="style-font-27">
 {" "}
 <font className="inline" data-ditto-id="style-font-8" aria-describedby="tooltip841579">
 Product
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-li-2">
 {" "}
 <font className="inline" data-ditto-id="style-font-33">
 {" "}
 <font className="inline" data-ditto-id="style-font-2">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-li-12">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-link-16" data-component="link" href="#">
 {" "}
 <font className="inline" data-ditto-id="style-font-28">
 {" "}
 <font className="inline" data-ditto-id="style-font-34" aria-describedby="tooltip455312">
 Gebruiksvoorwaarden
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </li>
 <li className="inline-block mr-2">
 {" "}
 <font className="inline" data-ditto-id="style-font-17">
 {" "}
 <font className="inline" data-ditto-id="style-font-11">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block" data-ditto-id="style-li-13">
 {" "}
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-link-17" data-component="link" aria-describedby="tooltip848069" href="/privacy">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline" data-ditto-id="style-font-18">
 Privacybeleid
 </font>
 {" "}
 </font>
 {" "}
 </Link>
 {" "}
 </li>
 </ul>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 </div>
 {" "}
 <div className="block bg-color-005" data-ditto-id="style-div-2">
 <div className="block max-w-285 mx-auto py-4 px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 ">
 <div className="flex -mx-[0.9375rem] flex-wrap" data-ditto-id="style-div-8">
 <div className="w-full block max-w-full px-[0.9375rem] grow shrink-0 basis-[0%] text-color-003 text-left max-md:text-center max-md:grow-[initial] max-md:basis-[initial]" data-ditto-id="style-div-14">
 <span className="inline align-middle" data-ditto-id="style-span-11">
 Copyright © Ahneta Advies
 </span>
 {" "}
 <p className="block mb-4" data-ditto-id="style-p">
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-link-18" data-component="link" href="/cookie-policy">
 Cookiebeleid
 </Link>
 </p>
 </div>
 {" "}
 <div className="w-142.5 block max-w-full my-[1.3125rem] px-[0.9375rem] grow shrink-0 basis-[0%] text-right max-md:w-[23.4375rem] max-md:text-center max-md:my-0 max-md:grow-[initial] max-md:basis-[initial] md:max-lg:w-90 md:max-lg:my-[0.5625rem] 2xl:w-165" data-ditto-id="style-div-15">
 <div className="h-full block">
 {" "}
 <a className="text-color-003 cursor-pointer hover:underline" href="https://imora.nl" target="_blank" rel="noopener noreferrer">
 Maintained by Imora
 </a>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </footer>
 {" "}
 <div className="block shrink-0" data-ditto-id="style-website-cookies-bar" id="website_cookies_bar">
 {" "}
 </div>
 {" "}
 {" "}
 <div className="block" data-ditto-id="style-div-26">
 <div className="block" />
 <div className="block" data-ditto-id="style-div-27" />
 <div className="w-78 h-0 block absolute top-[52.9px] left-240 z-1055 max-md:left-[3.4375rem] md:max-lg:left-112 2xl:left-400" data-ditto-id="style-div-9" />
 <div className="w-78 h-0 block absolute top-[52.9px] left-240 z-1055 max-md:left-[3.4375rem] md:max-lg:left-112 2xl:left-400" data-ditto-id="style-div-16" />
 </div>
 </>
 );
}
