import "./ditto.css";
import Tile from "./components/tile";
import ListRow from "./components/list-row";
import Link from "next/link";
// Generated by clone-site. Do not edit by hand.
const Tile_data = [
    { text: "Lageprijsgarantie" },
    { text: "30 dagen online retourneren" },
    { text: "Standaard verzending" }
];
const ListRow_data = [
    { href: "/pricing", label: "Prijs" },
    { href: "/over-ons", label: "Over ons" },
    { href: "/contactus", label: "Contact" }
];
const Tile_meta: string[][] = [
    ["n10", "n11"],
    ["n12", "n13"],
    ["n14", "n15"]
];
const ListRow_meta: string[][] = [
    ["n48", "style-9", "style-15"],
    ["n51", "style-10", "style-16"],
    ["n54", "style-11", "style-17"]
];
const Tile_styles = [
    { className: "before:content-['']" },
    { className: "before:content-['']" },
    { className: "before:content-['']" }
];
const ListRow_styles = [
    { className: "text-color-001" },
    { className: "text-color-001" },
    { className: "text-color-007" }
];

export default function Page() {
  return (
    <>
      <main className="block grow shrink-0">
          {" "}
          <div className="h-full block" id="wrap">
            <section className="block relative py-6 overflow-hidden text-background bg-color-004">
              <span className="h-full block absolute top-0 inset-x-0 overflow-hidden bg-cover [background-position:50%_0px] bg-no-repeat [background-attachment:fixed] pointer-events-none max-lg:[background-attachment:initial]" style={{ backgroundImage: "url(\"/assets/cloned/images/2873c8e777c4.jpg\")" }} />
              {" "}
              <div className="h-full block absolute top-0 inset-x-0 overflow-hidden bg-color-004 bg-no-repeat pointer-events-none" data-ditto-id="style-span-8" />
              {" "}
              <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-div-28">
                <h1 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[3.875rem] font-bold leading-[4.625rem] max-md:text-4xl max-md:leading-[2.6875rem] md:max-lg:text-5xl md:max-lg:leading-[3.625rem]" data-ditto-id="style-div-33" data-component="heading">
                  Contact
                </h1>
                {" "}
              </div>
              {" "}
            </section>
            {" "}
            <section className="block relative pt-10">
              <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330">
                <div className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-accent/20 bg-accent/5 p-6 max-md:flex-col max-md:items-start">
                  <div>
                    <p className="text-sm font-medium text-foreground">Liever eerst een paar korte vragen?</p>
                    <p className="mt-1 text-sm text-color-001">
                      Beantwoord enkele vragen over uw situatie en wij nemen gericht contact met u op.
                    </p>
                  </div>
                  <Link
                    href="/start"
                    className="inline-flex shrink-0 items-center rounded-full bg-accent px-6 py-3 text-sm font-medium text-background transition-colors hover:bg-accent/90 cursor-pointer"
                  >
                    Start uw traject
                  </Link>
                </div>
              </div>
            </section>
            {" "}
            <section className="block relative py-10" data-ditto-id="style-heading-6">
              <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-div-29">
                <div className="flex -mx-[0.9375rem] flex-wrap" data-ditto-id="style-section-5">
                  <div className="w-190 h-[29.95rem] min-h-6 block max-w-full px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[47.2rem] max-lg:mt-6 md:max-lg:w-180 2xl:w-220" data-ditto-id="style-div-30">
                    <p className="block mb-4" data-ditto-id="style-p-2">
                      {" Neem contact met ons op over alles wat met ons bedrijf of onze diensten te maken heeft."}
                      <br className="inline" data-ditto-id="style-br-4" />
                      {" We doen ons best om zo snel mogelijk bij je terug te komen. "}
                    </p>
                    {" "}
                    <section className="block relative" data-ditto-id="style-span-20">
                      <div className="block relative max-w-285 max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-span-6">
                        <form className="block" data-ditto-id="style-br-5" id="contactus_form">
                          <div className="flex -mx-[0.9375rem] flex-wrap">
                            <div className="basis-full shrink-0 block max-w-full py-2 px-[0.9375rem]">
                              <div className="h-full flex -mx-[0.9375rem] flex-wrap" data-ditto-id="style-span-5">
                                <label className="w-50 block max-w-full py-[0.4375rem] px-[0.9375rem] shrink-0 cursor-default max-md:w-[5.9625rem]" data-ditto-id="style-u" htmlFor="contact1">
                                  {" "}
                                  <span className="inline" data-ditto-id="style-br-10">
                                    Je naam
                                  </span>
                                  {" "}
                                  <span className="inline text-sm leading-[1.25rem]" data-ditto-id="style-br-3">
                                    {" *"}
                                  </span>
                                  {" "}
                                </label>
                                {" "}
                                <div className="w-full block max-w-full px-[0.9375rem] grow shrink-0 basis-[0%] max-md:grow-[initial] max-md:basis-[initial]" data-ditto-id="style-span-7">
                                  <input className="w-full h-9.5 border border-solid border-clr-0 block py-1.5 px-3 rounded-md overflow-clip bg-background [background-size:16px_18px] [background-position:98%_50%] bg-no-repeat [background-clip:padding-box] [-webkit-background-clip:padding-box]" style={{ backgroundImage: "url(data:image/png" }} data-ditto-id="style-br-15" data-component="input" id="contact1" name="name" type="text" />
                                  {" "}
                                </div>
                                {" "}
                              </div>
                              {" "}
                            </div>
                            {" "}
                            <div className="basis-full shrink-0 block max-w-full py-2 px-[0.9375rem]" data-ditto-id="style-br-7">
                              <div className="h-full flex -mx-[0.9375rem] flex-wrap" data-ditto-id="style-span-10">
                                <label className="w-50 block max-w-full py-[0.4375rem] px-[0.9375rem] shrink-0 cursor-default max-md:w-[9.35rem]" htmlFor="contact2">
                                  {" "}
                                  <span className="inline">
                                    Telefoonnummer
                                  </span>
                                  {" "}
                                </label>
                                {" "}
                                <div className="w-full block max-w-full px-[0.9375rem] grow shrink-0 basis-[0%] max-md:grow-[initial] max-md:basis-[initial]">
                                  <input className="w-full h-9.5 border border-solid border-clr-0 block py-1.5 px-3 rounded-md overflow-clip bg-background [background-clip:padding-box] [-webkit-background-clip:padding-box] cursor-text" data-ditto-id="style-br-2" data-component="input" id="contact2" name="phone" type="tel" />
                                  {" "}
                                </div>
                                {" "}
                              </div>
                              {" "}
                            </div>
                            {" "}
                            <div className="basis-full shrink-0 block max-w-full py-2 px-[0.9375rem]" data-ditto-id="style-br-9">
                              <div className="h-full flex -mx-[0.9375rem] flex-wrap" data-ditto-id="style-span-9">
                                <label className="w-50 block max-w-full py-[0.4375rem] px-[0.9375rem] shrink-0 cursor-default max-md:w-[100.5px]" data-ditto-id="style-br-8" htmlFor="contact3">
                                  {" "}
                                  <span className="inline" data-ditto-id="style-br-18">
                                    Je e-mail
                                  </span>
                                  {" "}
                                  <span className="inline text-sm leading-[1.25rem]" data-ditto-id="style-span-15">
                                    {" *"}
                                  </span>
                                  {" "}
                                </label>
                                {" "}
                                <div className="w-full block max-w-full px-[0.9375rem] grow shrink-0 basis-[0%] max-md:grow-[initial] max-md:basis-[initial]" data-ditto-id="style-br-17">
                                  <input className="w-full h-9.5 border border-solid border-clr-0 block py-1.5 px-3 rounded-md overflow-clip bg-background [background-clip:padding-box] [-webkit-background-clip:padding-box] cursor-text" data-ditto-id="style-br-12" data-component="input" id="contact3" name="email_from" type="email" />
                                  {" "}
                                </div>
                                {" "}
                              </div>
                              {" "}
                            </div>
                            {" "}
                            <div className="basis-full shrink-0 block max-w-full py-2 px-[0.9375rem]" data-ditto-id="style-span-13">
                              <div className="h-full flex -mx-[0.9375rem] flex-wrap" data-ditto-id="style-br">
                                <label className="w-50 block max-w-full py-[0.4375rem] px-[0.9375rem] shrink-0 cursor-default max-md:w-[116.5px]" htmlFor="contact4">
                                  {" "}
                                  <span className="inline">
                                    Jouw bedrijf
                                  </span>
                                  {" "}
                                </label>
                                {" "}
                                <div className="w-full block max-w-full px-[0.9375rem] grow shrink-0 basis-[0%] max-md:grow-[initial] max-md:basis-[initial]" data-ditto-id="style-br-22">
                                  <input className="w-full h-9.5 border border-solid border-clr-0 block py-1.5 px-3 rounded-md overflow-clip bg-background [background-clip:padding-box] [-webkit-background-clip:padding-box] cursor-text" data-ditto-id="style-br-13" data-component="input" id="contact4" name="company" type="text" />
                                  {" "}
                                </div>
                                {" "}
                              </div>
                              {" "}
                            </div>
                            {" "}
                            <div className="basis-full shrink-0 block max-w-full py-2 px-[0.9375rem]" data-ditto-id="style-span-22">
                              <div className="h-full flex -mx-[0.9375rem] flex-wrap" data-ditto-id="style-br-21">
                                <label className="w-50 block max-w-full py-[0.4375rem] px-[0.9375rem] shrink-0 cursor-default max-md:w-[7.5rem]" htmlFor="contact5">
                                  {" "}
                                  <span className="inline" data-ditto-id="style-span-12">
                                    Onderwerp
                                  </span>
                                  {" "}
                                  <span className="inline text-sm leading-[1.25rem]" data-ditto-id="style-u-2">
                                    {" *"}
                                  </span>
                                  {" "}
                                </label>
                                {" "}
                                <div className="w-full block max-w-full px-[0.9375rem] grow shrink-0 basis-[0%] max-md:grow-[initial] max-md:basis-[initial]">
                                  <input className="w-full h-9.5 border border-solid border-clr-0 block py-1.5 px-3 rounded-md overflow-clip bg-background [background-clip:padding-box] [-webkit-background-clip:padding-box] cursor-text" data-ditto-id="style-br-14" data-component="input" id="contact5" name="subject" type="text" />
                                  {" "}
                                </div>
                                {" "}
                              </div>
                              {" "}
                            </div>
                            {" "}
                            <div className="basis-full shrink-0 block max-w-full py-2 px-[0.9375rem]">
                              <div className="h-full flex -mx-[0.9375rem] flex-wrap" data-ditto-id="style-br-16">
                                <label className="w-50 block max-w-full py-[0.4375rem] px-[0.9375rem] shrink-0 cursor-default max-md:w-[6.8125rem]" data-ditto-id="style-br-6" htmlFor="contact6">
                                  {" "}
                                  <span className="inline">
                                    Jouw vraag
                                  </span>
                                  {" "}
                                </label>
                                {" "}
                                <div className="w-full block max-w-full px-[0.9375rem] grow shrink-0 basis-[0%] max-md:grow-[initial] max-md:basis-[initial]" data-ditto-id="style-bottom">
                                  <textarea className="w-full h-15.5 min-h-9.5 border border-solid border-clr-0 block py-1.5 px-3 rounded-md overflow-auto whitespace-pre-wrap [overflow-wrap:break-word] bg-background [background-clip:padding-box] [-webkit-background-clip:padding-box] cursor-text" data-ditto-id="style-footer" data-component="textarea" id="contact6" name="description" />
                                  {" "}
                                </div>
                                {" "}
                              </div>
                              {" "}
                            </div>
                            {" "}
                            <div className="basis-full shrink-0 block max-w-full py-2 px-[0.9375rem]" data-ditto-id="style-section">
                              <div className="w-50 h-px block float-left max-md:w-0" data-ditto-id="style-div-31" />
                              {" "}
                              <a className="w-[8.5625rem] border border-solid border-accent inline-block py-[0.6rem] px-[1.8rem] rounded-[160px] align-middle text-background text-xl leading-7.5 text-center bg-accent cursor-pointer" data-ditto-id="style-div-7" data-component="button" href="#" role="button">
                                Verstuur
                              </a>
                              {" "}
                              <span className="inline" data-ditto-id="style-div-32" id="s_website_form_result" />
                              {" "}
                            </div>
                            {" "}
                          </div>
                          {" "}
                        </form>
                        {" "}
                      </div>
                      {" "}
                    </section>
                    {" "}
                  </div>
                  {" "}
                  <div className="w-95 h-[29.95rem] min-h-6 block max-w-full px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-lg:h-48 max-lg:mt-6 md:max-lg:w-180 2xl:w-110" data-ditto-id="style-p-3">
                    <ul className="block pl-2 [list-style-type:none] list-outside" data-ditto-id="style-font-12">
                      <li className="list-item" data-ditto-id="style-font-9">
                        Ahneta Adviesgroep B.V.
                        <br className="inline" data-ditto-id="style-br-23" />
                      </li>
                      <li className="list-item" data-ditto-id="style-heading-5">
                        <i className="inline-block mr-2 [font-family:FontAwesome] leading-4 text-center before:content-[''] before:text-foreground before:text-base before:leading-4 before:text-center" data-ditto-id="style-font-13" />
                        {" Plantageweg 13 - C "}
                        <span className="inline" data-ditto-id="style-font-3">
                          <br className="inline" data-ditto-id="style-div" />
                          {" 3833 AZ LEUSDEN"}
                        </span>
                      </li>
                      <li className="list-item" data-ditto-id="style-p-4">
                        <br className="inline" data-ditto-id="style-font-41" />
                        {" "}
                      </li>
                      <li className="list-item">
                        <i className="inline-block mr-2 [font-family:FontAwesome] leading-4 text-center before:content-[''] before:text-foreground before:text-base before:leading-4 before:text-center" data-ditto-id="style-heading-3" aria-describedby="tooltip100040" />
                        {" "}
                        <span className="inline" data-ditto-id="style-span-17">
                          + 31 33 461 14 47
                        </span>
                        {" "}
                      </li>
                      <li className="list-item" data-ditto-id="style-link-6">
                        <i className="inline-block [font-family:FontAwesome] leading-4 text-center before:content-[''] before:text-foreground before:text-base before:leading-4 before:text-center" data-ditto-id="style-font-4" aria-describedby="tooltip409766" />
                        {" + 31 33 461 63 01"}
                      </li>
                      <li className="list-item" data-ditto-id="style-font-14">
                        <i className="inline-block [font-family:FontAwesome] leading-4 text-center before:content-[''] before:text-foreground before:text-base before:leading-4 before:text-center" data-ditto-id="style-heading" aria-describedby="tooltip552749" />
                        {" + 31 6 11 23 88 30"}
                      </li>
                      <li className="list-item" data-ditto-id="style-link-7">
                        <i className="inline-block mr-2 [font-family:FontAwesome] leading-4 text-center before:content-[''] before:text-foreground before:text-base before:leading-4 before:text-center" data-ditto-id="style-font-5" />
                        {" "}
                        <span className="inline" data-ditto-id="style-font-42">
                          info@ahneta.nl
                        </span>
                        {" "}
                      </li>
                    </ul>
                    {" "}
                    <div className="mt-4 block overflow-hidden rounded-md">
                      <iframe
                        title="Ahneta Adviesgroep B.V. op Google Maps"
                        src="https://www.google.com/maps?q=Plantageweg+13-C,+3833+AZ+Leusden&output=embed"
                        className="h-48 w-full border-0"
                        loading="lazy"
                        referrerPolicy="no-referrer-when-downgrade"
                      />
                      <a
                        href="https://www.google.com/maps/search/?api=1&query=Plantageweg+13-C,+3833+AZ+Leusden"
                        target="_blank"
                        rel="noopener noreferrer"
                        className="mt-1 inline-block text-xs text-accent hover:underline"
                      >
                        Route op Google Maps
                      </a>
                    </div>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </section>
            {" "}
          </div>
          {" "}
        </main>
        {" "}
        <footer className="block shrink-0 text-background bg-color-004" data-ditto-id="style-span-16" id="bottom">
          <div className="block" data-ditto-id="style-div-13" id="footer">
            <section className="block relative pt-8 pb-4">
              <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330" data-ditto-id="style-font-15">
                <div className="flex -mx-[0.9375rem] flex-wrap items-end" data-ditto-id="style-font-10">
                  <div className="w-[17.8125rem] h-[8.1rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[123.7px] md:max-lg:w-180 md:max-lg:h-[6.2rem] 2xl:w-82.5" data-ditto-id="style-br-11">
                    <p className="block mb-2" data-ditto-id="style-heading-2">
                      <font className="inline" data-ditto-id="style-link-8">
                        {" "}
                        <font className="inline" data-ditto-id="style-font-6">
                          Hoe kunnen we helpen
                        </font>
                        {" "}
                      </font>
                      {" "}
                      <br className="inline" data-ditto-id="style-font-24" />
                      {" "}
                    </p>
                    {" "}
                    <h4 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-2xl font-bold leading-[1.8125rem] max-md:text-[1.375rem] max-md:leading-[1.625rem] md:max-lg:text-[1.4375rem] md:max-lg:leading-[1.6875rem]" data-ditto-id="style-div-22" data-component="heading">
                      <font className="inline" data-ditto-id="style-div-11">
                        {" "}
                        <font className="inline" data-ditto-id="style-p-7">
                          {"U kunt altijd contact met ons opnemen "}
                        </font>
                        {" "}
                      </font>
                      {" "}
                    </h4>
                    {" "}
                  </div>
                  {" "}
                  <div className="w-[17.8125rem] h-[8.15rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[128.9px] md:max-lg:w-180 md:max-lg:h-[8.1rem] 2xl:w-82.5" data-ditto-id="style-font-7" aria-describedby="tooltip8305">
                    <p className="block mb-2" data-ditto-id="style-font-35">
                      <font className="inline" data-ditto-id="style-link-9">
                        {" "}
                        <font className="inline" data-ditto-id="style-i-3">
                          Bel ons
                        </font>
                        {" "}
                      </font>
                      {" "}
                    </p>
                    {" "}
                    <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-ditto-id="style-link-10" data-component="heading">
                      <span className="inline" data-ditto-id="style-i-2">
                        {" "}
                        <a className="inline text-primary cursor-pointer" data-ditto-id="style-link-11" data-component="link" href="tel:31 (0) 33 46 11 447">
                          {" "}
                          <font className="inline" data-ditto-id="style-i">
                            {" "}
                            <font className="inline" data-ditto-id="style-section-2">
                              {"+31 (0) 33 46 11 447 "}
                            </font>
                            {" "}
                          </font>
                          {" "}
                        </a>
                        {" "}
                      </span>
                      {" "}
                    </h5>
                    {" "}
                    <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-ditto-id="style-div-6" data-component="heading" aria-describedby="tooltip842231">
                      <a className="inline text-primary cursor-pointer" data-ditto-id="style-div-5" data-component="link" href="tel:31 (0) 33 46 11 447">
                        {" "}
                        <font className="inline" data-ditto-id="style-hr">
                          {" "}
                          <font className="inline" data-ditto-id="style-section-6">
                            +31 (0) 6 11 23 88 30
                          </font>
                          {" "}
                        </font>
                        {" "}
                      </a>
                      {" "}
                      <span className="inline" data-ditto-id="style-div-34">
                        {" "}
                      </span>
                      {" "}
                    </h5>
                    {" "}
                  </div>
                  {" "}
                  <div className="w-[17.8125rem] h-[6.075rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[6.025rem] md:max-lg:w-180 md:max-lg:h-[6.05rem] 2xl:w-82.5" data-ditto-id="style-div-4" aria-describedby="tooltip941693">
                    <p className="block mb-2" data-ditto-id="style-div-21">
                      <font className="inline" data-ditto-id="style-link-12">
                        {" "}
                        <font className="inline" data-ditto-id="style-irketim-logosu">
                          Stuur ons een bericht
                        </font>
                        {" "}
                      </font>
                      {" "}
                      <br className="inline" data-ditto-id="style-div-12" />
                      {" "}
                    </p>
                    {" "}
                    <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-ditto-id="style-ul" data-component="heading">
                      <a className="inline text-primary cursor-pointer" data-ditto-id="style-li" data-component="link" href="mailto:info@ahneta.nl">
                        {" "}
                        <font className="inline" data-ditto-id="style-link-13">
                          {" "}
                          <font className="inline" data-ditto-id="style-font-25">
                            info@ahneta.nl
                          </font>
                          {" "}
                        </font>
                        {" "}
                      </a>
                      {" "}
                    </h5>
                    {" "}
                  </div>
                  {" "}
                  <div className="w-[17.8125rem] h-[97.3px] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] md:max-lg:w-180 2xl:w-82.5" data-ditto-id="style-font-16">
                    <div className="block text-right" data-ditto-id="style-li-3">
                      <p className="block mr-[0.4rem] mb-2 align-middle" data-ditto-id="style-font-22">
                        <font className="inline align-middle">
                          {" "}
                          <font className="inline align-middle" data-ditto-id="style-li-8">
                            Volg ons
                          </font>
                          {" "}
                        </font>
                        {" "}
                      </p>
                      {" "}
                      <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-link-14" data-component="link" href="https://www.ahneta.nl/website/social/twitter">
                        {" "}
                        <i className="flex m-1 justify-center items-center [font-family:FontAwesome-twitter-x-only] leading-4 before:content-[''] before:block before:w-4 before:h-4 before:text-primary before:text-base before:leading-4 before:text-right" data-ditto-id="style-font-26">
                          ​
                        </i>
                        {" "}
                      </a>
                      {" "}
                      <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-font" data-component="link" href="https://www.ahneta.nl/website/social/linkedin">
                        {" "}
                        <i className="flex m-1 justify-center items-center [font-family:FontAwesome] leading-4 before:content-[''] before:block before:w-[13.7px] before:h-4 before:text-primary before:text-base before:leading-4 before:text-right" data-ditto-id="style-li-4" aria-describedby="tooltip290654">
                          ​
                        </i>
                        {" "}
                      </a>
                      {" "}
                      <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-font-19" data-component="link" href="https://www.ahneta.nl/website/social/instagram">
                        {" "}
                        <i className="flex m-1 justify-center items-center [font-family:FontAwesome] leading-4 before:content-[''] before:block before:w-[13.7px] before:h-4 before:text-primary before:text-base before:leading-4 before:text-right" data-ditto-id="style-font-43">
                          ​
                        </i>
                        {" "}
                      </a>
                      {" "}
                    </div>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </section>
            {" "}
            <section className="block relative" data-ditto-id="style-li-11">
              <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330" data-ditto-id="style-link-15">
                <div className="block py-4 leading-0" data-ditto-id="style-font-27">
                  <hr className="h-px border-t border-solid border-t-muted-foreground block overflow-hidden mx-auto w-[69.375rem] max-md:w-[21.5625rem] md:max-lg:w-[43.125rem] 2xl:w-[80.625rem]" data-ditto-id="style-font-8" />
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </section>
            {" "}
            <section className="block relative" data-ditto-id="style-li-2">
              <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330" data-ditto-id="style-font-33">
                <div className="flex -mx-[0.9375rem] flex-wrap items-center" data-ditto-id="style-font-2" aria-describedby="tooltip859185">
                  <div className="w-47.5 h-[6.3125rem] min-h-6 block max-w-full pb-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-lg:h-34 md:max-lg:w-180 2xl:w-55 2xl:h-[116.9px]" data-ditto-id="style-li-12">
                    <Link className="inline text-primary cursor-pointer" data-ditto-id="style-link-16" data-component="link" href="/">
                      {" "}
                      <img className="w-40 h-[5.3125rem] inline max-w-full overflow-clip align-middle max-lg:w-56.5 max-lg:h-30 2xl:w-47.5 2xl:h-[6.3125rem]" data-ditto-id="style-font-28" data-component="image" alt="" aria-label="Şirketim logosu" role="img" src="/assets/cloned/images/1461683c0d67.png" title="Benim şirketim" />
                      {" "}
                    </Link>
                    {" "}
                  </div>
                  {" "}
                  <div className="w-237.5 h-10 min-h-6 block max-w-full pb-4 px-[0.9375rem] shrink-0 text-right max-md:w-[23.4375rem] max-md:h-16 md:max-lg:w-180 2xl:w-275" data-ditto-id="style-font-34" aria-describedby="tooltip611099">
                    <ul className="h-full block [list-style-type:none] list-outside" aria-describedby="tooltip612522">
                      <li className="inline-block mr-2" data-ditto-id="style-font-17">
                        {" "}
                        <Link className="inline text-primary cursor-pointer" data-ditto-id="style-font-11" data-component="link" href="/">
                          {" "}
                          <font className="inline" data-ditto-id="style-li-13">
                            {" "}
                            <font className="inline" data-ditto-id="style-link-17">
                              Home
                            </font>
                            {" "}
                          </font>
                          {" "}
                        </Link>
                        {" "}
                      </li>
                      <li className="inline-block mr-2">
                        {" "}
                        <font className="inline" data-ditto-id="style-font-18">
                          {" "}
                          <font className="inline" data-ditto-id="style-div-2">
                            •
                          </font>
                          {" "}
                        </font>
                        {" "}
                      </li>
                      <li className="inline-block mr-2">
                        {" "}
                        <a className="inline text-primary cursor-pointer" data-ditto-id="style-div-8" data-component="link" href="#">
                          {" "}
                          <font className="inline" data-ditto-id="style-div-14">
                            {" "}
                            <font className="inline" data-ditto-id="style-span-11">
                              Over ons
                            </font>
                            {" "}
                          </font>
                          {" "}
                        </a>
                        {" "}
                      </li>
                      <li className="inline-block mr-2" data-ditto-id="style-p">
                        {" "}
                        <font className="inline" data-ditto-id="style-link-18">
                          {" "}
                          <font className="inline" data-ditto-id="style-div-15">
                            •
                          </font>
                          {" "}
                        </font>
                        {" "}
                      </li>
                      <li className="inline-block mr-2">
                        {" "}
                        <a className="inline text-primary cursor-pointer" data-ditto-id="style-link-40" data-component="link" href="#">
                          {" "}
                          <font className="inline" data-ditto-id="style-image">
                            {" "}
                            <font className="inline" data-ditto-id="style-link-19" aria-describedby="tooltip841579">
                              Product
                            </font>
                            {" "}
                          </font>
                          {" "}
                        </a>
                        {" "}
                      </li>
                      <li className="inline-block mr-2" data-ditto-id="style-website-cookies-bar">
                        {" "}
                        <font className="inline" data-ditto-id="style-div-26">
                          {" "}
                          <font className="inline">
                            •
                          </font>
                          {" "}
                        </font>
                        {" "}
                      </li>
                      <li className="inline-block mr-2" data-ditto-id="style-div-27">
                        {" "}
                        <a className="inline text-primary cursor-pointer" data-ditto-id="style-div-9" data-component="link" href="#">
                          {" "}
                          <font className="inline" data-ditto-id="style-div-16">
                            {" "}
                            <font className="inline" aria-describedby="tooltip455312">
                              Gebruiksvoorwaarden
                            </font>
                            {" "}
                          </font>
                          {" "}
                        </a>
                        {" "}
                      </li>
                      <li className="inline-block mr-2" data-ditto-id="style-link-21">
                        {" "}
                        <font className="inline" data-ditto-id="style-font-21">
                          {" "}
                          <font className="inline" data-ditto-id="style-font-36">
                            •
                          </font>
                          {" "}
                        </font>
                        {" "}
                      </li>
                      <li className="inline-block">
                        {" "}
                        <Link className="inline text-primary cursor-pointer" data-ditto-id="style-font-20" data-component="link" aria-describedby="tooltip848069" href="/privacy">
                          {" "}
                          <font className="inline">
                            {" "}
                            <font className="inline" data-ditto-id="style-li-6">
                              Privacybeleid
                            </font>
                            {" "}
                          </font>
                          {" "}
                        </Link>
                        {" "}
                      </li>
                    </ul>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </section>
            {" "}
          </div>
          {" "}
          <div className="block bg-color-005" data-ditto-id="style-link-22">
            <div className="block max-w-285 mx-auto py-4 px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330" data-ditto-id="style-font-23">
              <div className="flex -mx-[0.9375rem] flex-wrap">
                <div className="w-full block max-w-full px-[0.9375rem] grow shrink-0 basis-[0%] text-color-003 text-left max-md:text-center max-md:grow-[initial] max-md:basis-[initial]" data-ditto-id="style-li-7">
                  <span className="inline align-middle">
                    Copyright © Ahneta Advies
                  </span>
                  {" "}
                  <p className="block mb-4">
                    <Link className="inline text-primary cursor-pointer" data-ditto-id="style-li-5" data-component="link" href="/cookie-policy">
                      Cookiebeleid
                    </Link>
                  </p>
                </div>
                {" "}
                <div className="w-142.5 block max-w-full my-[1.3125rem] px-[0.9375rem] grow shrink-0 basis-[0%] text-right max-md:w-[23.4375rem] max-md:text-center max-md:my-0 max-md:grow-[initial] max-md:basis-[initial] md:max-lg:w-90 md:max-lg:my-[0.5625rem] 2xl:w-165" data-ditto-id="style-link-23">
                  <div className="h-full block">
                    {" "}
                    <a className="text-color-003 cursor-pointer hover:underline" href="https://imora.nl" target="_blank" rel="noopener noreferrer">
                      Maintained by Imora
                    </a>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </footer>
        {" "}
        <div className="block shrink-0" id="website_cookies_bar">
          {" "}
        </div>
        {" "}
      {" "}
      <div className="block">
        <div className="block" data-ditto-id="style-span-18" />
        <div className="block" data-ditto-id="style-p-6" />
        <div className="w-78 h-0 block absolute top-[52.9px] left-240 z-1055 max-md:left-[3.4375rem] md:max-lg:left-112 2xl:left-400" data-ditto-id="style-link-24" />
        <div className="w-78 h-0 block absolute top-[52.9px] left-240 z-1055 max-md:left-[3.4375rem] md:max-lg:left-112 2xl:left-400" data-ditto-id="style-div-3" />
 </div>
    </>
  );
}
