import "./ditto.css";
import Tile from "./components/tile";
import ListRow from "./components/list-row";
import Link from "next/link";
// Generated by clone-site. Do not edit by hand.
const Tile_data = [
 { text: "Lageprijsgarantie" },
 { text: "30 dagen online retourneren" },
 { text: "Standaard verzending" }
];
const ListRow_data = [
 { href: "/pricing", label: "Prijs" },
 { href: "/over-ons", label: "Over ons" },
 { href: "/contactus", label: "Contact" }
];
const Tile_meta: string[][] = [
 ["n10", "n11"],
 ["n12", "n13"],
 ["n14", "n15"]
];
const ListRow_meta: string[][] = [
 ["n48", "style-9", "style-15"],
 ["n51", "style-10", "style-16"],
 ["n54", "style-11", "style-17"]
];
const Tile_styles = [
 { className: "before:content-['']" },
 { className: "before:content-['']" },
 { className: "before:content-['']" }
];

export default function Page() {
 return (
 <>
 <main className="block grow shrink-0">
 <div className="h-full block" id="wrap">
 <div className="block">
 <section className="block relative py-6 overflow-hidden text-background bg-color-004">
 <span className="h-full block absolute top-0 inset-x-0 overflow-hidden bg-cover [background-position:50%_0px] bg-no-repeat [background-attachment:fixed] pointer-events-none max-lg:[background-attachment:initial]" style={{ backgroundImage: "url(\"/assets/cloned/images/2873c8e777c4.jpg\")" }} data-ditto-id="style-span-8" />
 {" "}
 <div className="h-full block absolute top-0 inset-x-0 overflow-hidden bg-color-004 bg-no-repeat pointer-events-none" data-ditto-id="style-div-28" />
 {" "}
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-div-33">
 <h1 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[3.875rem] font-bold leading-[4.625rem] max-md:text-4xl max-md:leading-[2.6875rem] md:max-lg:text-5xl md:max-lg:leading-[3.625rem]" data-ditto-id="style-heading-6" data-component="heading">
 Ondernemersplan
 <br className="inline" data-ditto-id="style-div-29" />
 </h1>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 </div>
 {" "}
 <div className="block" data-ditto-id="style-section-5">
 <section className="block relative py-10 bg-background" data-ditto-id="style-div-30">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-p-2">
 <p className="block mb-4" data-ditto-id="style-br-4">
 <br className="inline" data-ditto-id="style-span-20" />
 Of het nu gaat om een starter of om een onderneming die al enige tijd bestaat er is altijd wel behoefte om een ondernemingsplan te laten opstellen. Tegenwoordig wordt een ondernemersplan vaak ook wel een businessplan genoemd. Ahneta heeft op dit terrein zijn sporen wel verdiend.
 <br className="inline" data-ditto-id="style-span-6" />
 Voor activiteiten in het buitenland, waarvoor zowel subsidies uit de EU als geld geleend van commerciële banken van grote betekenis zijn, hebben wij ondernemingsplannen opgezet. Maar ook voor de financiering van een kinderdagverblijf, nieuwe HORECA gelegenheid en alles wat er tussenin kan zitten, stelt Ahneta een gedegen ondernemersplan op.
 <br className="inline" data-ditto-id="style-br-5" />
 <br className="inline" />
 Een ondernemingsplan is het samenspel van u als ondernemer en van Ahneta als adviseur. Ook hier geldt dat wij voorafgaand aan het opstellen van de rapportage met u een aantal gesprekken zullen voeren over uw plannen. Hierna zullen wij aan de hand van uw locatiekeuze onderzoek instellen naar de markt, de concurrentie, de benodigde vergunningen, het klantenpotentieel, de diverse onkosten, uw marktaandeel e.d..
 <br className="inline" />
 <br className="inline" data-ditto-id="style-span-5" />
 Het onderzoek naar uw beoogde vestigingsplaats is er deels op gericht om de meeste actuele informatie te krijgen over het klantenpotentieel ter plaatse en de regio daar omheen. Het is echter ook gericht op eventueel aanwezige verzorgingsfunctie die uw beoogde vestigingsplaats speelt in de regio.
 <br className="inline" data-ditto-id="style-u" />
 <br className="inline" data-ditto-id="style-br-10" />
 Ook probeert Ahneta in dit onderzoek te achterhalen of er in de (nabije) toekomst belangrijke wijzigingen te verwachten zijn zoals van het bestemmingsplan, eventueel grootschalig wegenonderhoud of wijksanering ter plaatse en dergelijke.
 <br className="inline" data-ditto-id="style-br-3" />
 <br className="inline" data-ditto-id="style-span-7" />
 De prijs voor het opstellen van een ondernemingsplan is afhankelijk van de hoeveelheid tijd die er in geïnvesteerd moet worden en de eventuele kosten die voor informatievergaring betaald moet worden. Bij financiering kijken wij meteen of er mogelijkheden zijn voor garantiestellingen door bijvoorbeeld gemeente, provincie of staat. Ook wordt geïnventariseerd welke subsidies eventueel mogelijk zijn.
 </p>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </main>
 {" "}
 <footer className="block shrink-0 text-background bg-color-004" data-ditto-id="style-br-15" id="bottom">
 <div className="block" data-ditto-id="style-br-7" id="footer">
 <section className="block relative pt-8 pb-4" data-ditto-id="style-span-10">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 ">
 <div className="flex -mx-[0.9375rem] flex-wrap items-end">
 <div className="w-[17.8125rem] h-[8.1rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[123.7px] md:max-lg:w-180 md:max-lg:h-[6.2rem] 2xl:w-82.5">
 <p className="block mb-2" data-ditto-id="style-br-2">
 <font className="inline" data-ditto-id="style-br-9">
 {" "}
 <font className="inline" data-ditto-id="style-span-9">
 Hoe kunnen we helpen
 </font>
 {" "}
 </font>
 {" "}
 <br className="inline" data-ditto-id="style-br-8" />
 {" "}
 </p>
 {" "}
 <h4 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-2xl font-bold leading-[1.8125rem] max-md:text-[1.375rem] max-md:leading-[1.625rem] md:max-lg:text-[1.4375rem] md:max-lg:leading-[1.6875rem]" data-ditto-id="style-br-18" data-component="heading">
 <font className="inline" data-ditto-id="style-span-15">
 {" "}
 <font className="inline" data-ditto-id="style-br-17">
 {"U kunt altijd contact met ons opnemen "}
 </font>
 {" "}
 </font>
 {" "}
 </h4>
 {" "}
 </div>
 {" "}
 <div className="w-[17.8125rem] h-[8.15rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[128.9px] md:max-lg:w-180 md:max-lg:h-[8.1rem] 2xl:w-82.5" data-ditto-id="style-br-12" aria-describedby="tooltip8305">
 <p className="block mb-2" data-ditto-id="style-span-13">
 <font className="inline" data-ditto-id="style-br">
 {" "}
 <font className="inline">
 Bel ons
 </font>
 {" "}
 </font>
 {" "}
 </p>
 {" "}
 <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-component="heading">
 <span className="inline" data-ditto-id="style-br-22">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-br-13" data-component="link" href="tel:31 (0) 33 46 11 447">
 {" "}
 <font className="inline" data-ditto-id="style-span-22">
 {" "}
 <font className="inline" data-ditto-id="style-br-21">
 {"+31 (0) 33 46 11 447 "}
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </span>
 {" "}
 </h5>
 {" "}
 <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-component="heading" aria-describedby="tooltip842231">
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-span-12" data-component="link" href="tel:31 (0) 33 46 11 447">
 {" "}
 <font className="inline" data-ditto-id="style-u-2">
 {" "}
 <font className="inline">
 +31 (0) 6 11 23 88 30
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 <span className="inline" data-ditto-id="style-br-14">
 {" "}
 </span>
 {" "}
 </h5>
 {" "}
 </div>
 {" "}
 <div className="w-[17.8125rem] h-[6.075rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[6.025rem] md:max-lg:w-180 md:max-lg:h-[6.05rem] 2xl:w-82.5" aria-describedby="tooltip941693">
 <p className="block mb-2" data-ditto-id="style-br-16">
 <font className="inline" data-ditto-id="style-br-6">
 {" "}
 <font className="inline">
 Stuur ons een bericht
 </font>
 {" "}
 </font>
 {" "}
 <br className="inline" data-ditto-id="style-bottom" />
 {" "}
 </p>
 {" "}
 <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-ditto-id="style-footer" data-component="heading">
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-section" data-component="link" href="mailto:info@ahneta.nl">
 {" "}
 <font className="inline" data-ditto-id="style-div-31">
 {" "}
 <font className="inline" data-ditto-id="style-div-7">
 info@ahneta.nl
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </h5>
 {" "}
 </div>
 {" "}
 <div className="w-[17.8125rem] h-[97.3px] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] md:max-lg:w-180 2xl:w-82.5" data-ditto-id="style-div-32">
 <div className="block text-right" data-ditto-id="style-p-3">
 <p className="block mr-[0.4rem] mb-2 align-middle" data-ditto-id="style-font-12">
 <font className="inline align-middle" data-ditto-id="style-font-9">
 {" "}
 <font className="inline align-middle" data-ditto-id="style-br-23">
 Volg ons
 </font>
 {" "}
 </font>
 {" "}
 </p>
 {" "}
 <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-heading-5" data-component="link" href="https://www.ahneta.nl/website/social/twitter">
 {" "}
 <i className="flex m-1 justify-center items-center [font-family:FontAwesome-twitter-x-only] leading-4 before:content-[''] before:block before:w-4 before:h-4 before:text-primary before:text-base before:leading-4 before:text-right" data-ditto-id="style-font-13">
 ​
 </i>
 {" "}
 </a>
 {" "}
 <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-font-3" data-component="link" href="https://www.ahneta.nl/website/social/linkedin">
 {" "}
 <i className="flex m-1 justify-center items-center [font-family:FontAwesome] leading-4 before:content-[''] before:block before:w-[13.7px] before:h-4 before:text-primary before:text-base before:leading-4 before:text-right" data-ditto-id="style-div" aria-describedby="tooltip290654">
 ​
 </i>
 {" "}
 </a>
 {" "}
 <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-p-4" data-component="link" href="https://www.ahneta.nl/website/social/instagram">
 {" "}
 <i className="flex m-1 justify-center items-center [font-family:FontAwesome] leading-4 before:content-[''] before:block before:w-[13.7px] before:h-4 before:text-primary before:text-base before:leading-4 before:text-right" data-ditto-id="style-font-41">
 ​
 </i>
 {" "}
 </a>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 " data-ditto-id="style-heading-3">
 <div className="block py-4 leading-0" data-ditto-id="style-span-17">
 <hr className="h-px border-t border-solid border-t-muted-foreground block overflow-hidden mx-auto w-[69.375rem] max-md:w-[21.5625rem] md:max-lg:w-[43.125rem] 2xl:w-[80.625rem]" data-ditto-id="style-link-6" />
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative" data-ditto-id="style-font-4">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 " data-ditto-id="style-font-14">
 <div className="flex -mx-[0.9375rem] flex-wrap items-center" data-ditto-id="style-heading" aria-describedby="tooltip859185">
 <div className="w-47.5 h-[6.3125rem] min-h-6 block max-w-full pb-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-lg:h-34 md:max-lg:w-180 2xl:w-55 2xl:h-[116.9px]" data-ditto-id="style-link-7">
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-font-5" data-component="link" href="/">
 {" "}
 <img className="w-40 h-[5.3125rem] inline max-w-full overflow-clip align-middle max-lg:w-56.5 max-lg:h-30 2xl:w-47.5 2xl:h-[6.3125rem]" data-ditto-id="style-font-42" data-component="image" alt="" aria-label="Şirketim logosu" role="img" src="/assets/cloned/images/1461683c0d67.png" title="Benim şirketim" />
 {" "}
 </Link>
 {" "}
 </div>
 {" "}
 <div className="w-237.5 h-10 min-h-6 block max-w-full pb-4 px-[0.9375rem] shrink-0 text-right max-md:w-[23.4375rem] max-md:h-16 md:max-lg:w-180 2xl:w-275" data-ditto-id="style-span-16" aria-describedby="tooltip611099">
 <ul className="h-full block [list-style-type:none] list-outside" data-ditto-id="style-div-13" aria-describedby="tooltip612522">
 <li className="inline-block mr-2">
 {" "}
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-font-15" data-component="link" href="/">
 {" "}
 <font className="inline" data-ditto-id="style-font-10">
 {" "}
 <font className="inline" data-ditto-id="style-br-11">
 Home
 </font>
 {" "}
 </font>
 {" "}
 </Link>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-heading-2">
 {" "}
 <font className="inline" data-ditto-id="style-link-8">
 {" "}
 <font className="inline" data-ditto-id="style-font-6">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-font-24">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-div-22" data-component="link" href="#">
 {" "}
 <font className="inline" data-ditto-id="style-div-11">
 {" "}
 <font className="inline" data-ditto-id="style-p-7">
 Over ons
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-font-7">
 {" "}
 <font className="inline" data-ditto-id="style-font-35">
 {" "}
 <font className="inline" data-ditto-id="style-link-9">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-i-3">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-link-10" data-component="link" href="#">
 {" "}
 <font className="inline" data-ditto-id="style-i-2">
 {" "}
 <font className="inline" data-ditto-id="style-link-11" aria-describedby="tooltip841579">
 Product
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-i">
 {" "}
 <font className="inline" data-ditto-id="style-section-2">
 {" "}
 <font className="inline" data-ditto-id="style-div-6">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-div-5">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-hr" data-component="link" href="#">
 {" "}
 <font className="inline" data-ditto-id="style-section-6">
 {" "}
 <font className="inline" data-ditto-id="style-div-34" aria-describedby="tooltip455312">
 Gebruiksvoorwaarden
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-div-4">
 {" "}
 <font className="inline" data-ditto-id="style-div-21">
 {" "}
 <font className="inline" data-ditto-id="style-link-12">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block" data-ditto-id="style-irketim-logosu">
 {" "}
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-div-12" data-component="link" aria-describedby="tooltip848069" href="/privacy">
 {" "}
 <font className="inline" data-ditto-id="style-ul">
 {" "}
 <font className="inline" data-ditto-id="style-li">
 Privacybeleid
 </font>
 {" "}
 </font>
 {" "}
 </Link>
 {" "}
 </li>
 </ul>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 </div>
 {" "}
 <div className="block bg-color-005" data-ditto-id="style-link-13">
 <div className="block max-w-285 mx-auto py-4 px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 " data-ditto-id="style-font-25">
 <div className="flex -mx-[0.9375rem] flex-wrap" data-ditto-id="style-font-16">
 <div className="w-full block max-w-full px-[0.9375rem] grow shrink-0 basis-[0%] text-color-003 text-left max-md:text-center max-md:grow-[initial] max-md:basis-[initial]" data-ditto-id="style-li-3">
 <span className="inline align-middle" data-ditto-id="style-font-22">
 Copyright © Ahneta Advies
 </span>
 {" "}
 <p className="block mb-4">
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-li-8" data-component="link" href="/cookie-policy">
 Cookiebeleid
 </Link>
 </p>
 </div>
 {" "}
 <div className="w-142.5 block max-w-full my-[1.3125rem] px-[0.9375rem] grow shrink-0 basis-[0%] text-right max-md:w-[23.4375rem] max-md:text-center max-md:my-0 max-md:grow-[initial] max-md:basis-[initial] md:max-lg:w-90 md:max-lg:my-[0.5625rem] 2xl:w-165" data-ditto-id="style-link-14">
 <div className="h-full block" data-ditto-id="style-font-26">
 {" "}
 <a className="text-color-003 cursor-pointer hover:underline" href="https://imora.nl" target="_blank" rel="noopener noreferrer">
 Maintained by Imora
 </a>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </footer>
 {" "}
 <div className="block shrink-0" data-ditto-id="style-font-43" id="website_cookies_bar">
 {" "}
 </div>
 {" "}
 {" "}
 <div className="block" data-ditto-id="style-li-11">
 <div className="block" data-ditto-id="style-link-15" />
 <div className="block" data-ditto-id="style-font-27" />
 <div className="w-78 h-0 block absolute top-[52.9px] left-240 z-1055 max-md:left-[3.4375rem] md:max-lg:left-112 2xl:left-400" data-ditto-id="style-font-8" />
 <div className="w-78 h-0 block absolute top-[52.9px] left-240 z-1055 max-md:left-[3.4375rem] md:max-lg:left-112 2xl:left-400" data-ditto-id="style-li-2" />
 </div>
 </>
 );
}
