import "./ditto.css";
import Tile from "./components/tile";
import ListRow from "./components/list-row";
import Link from "next/link";

export const metadata = {
 title: "Success Stories | Ahneta Advies",
 alternates: {
 canonical: "/blog/success-stories-2"
 },
 openGraph: {
 title: "Success Stories | Ahneta Advies",
 url: "/blog/success-stories-2"
 },
 twitter: {
 title: "Success Stories | Ahneta Advies"
 }
};
// Generated by clone-site. Do not edit by hand.
const Tile_data = [
 { text: "Lageprijsgarantie" },
 { text: "30 dagen online retourneren" },
 { text: "Standaard verzending" }
];
const ListRow_data = [
 { href: "/pricing", label: "Prijs" },
 { href: "/over-ons", label: "Over ons" },
 { href: "/contactus", label: "Contact" }
];
const Tile_meta: string[][] = [
 ["n10", "n11"],
 ["n12", "n13"],
 ["n14", "n15"]
];
const ListRow_meta: string[][] = [
 ["n48", "style-9", "style-15"],
 ["n51", "style-10", "style-16"],
 ["n54", "style-11", "style-17"]
];
const Tile_styles = [
 { className: "before:content-['']" },
 { className: "before:content-['']" },
 { className: "before:content-['']" }
];

export default function Page() {
 return (
 <>
 <main className="block grow shrink-0">
 <div className="block" id="wrap">
 <div className="block" id="o_wblog_blog_top">
 <div className="min-h-px flex relative py-12 flex-col bg-clr-3 h-[187.19px] max-md:h-[160.45px] md:max-lg:h-[10.825rem]">
 <div className="h-full block absolute top-0 inset-x-0 min-w-0 bg-cover [background-position:50%_50%] bg-no-repeat" data-ditto-id="style-span-8" />
 {" "}
 <div className="h-full block absolute top-0 inset-x-0 opacity-20 min-w-0 text-background bg-color-007 bg-cover [background-position:50%_50%] bg-no-repeat" data-ditto-id="style-div-28" />
 {" "}
 <div className="w-full flex relative max-w-285 mx-auto px-[0.9375rem] flex-col justify-around h-[91.19px] max-md:max-w-none max-md:h-[64.45px] md:max-lg:max-w-180 md:max-lg:h-[4.825rem] 2xl:max-w-330 before:content-[''] before:table before:w-full before:h-0 after:content-[''] after:table after:w-full after:h-0" data-ditto-id="style-div-33">
 <div className="h-full block text-background" data-ditto-id="style-heading-6">
 <span className="inline" data-ditto-id="style-div-29" title="Success Stories">
 {" "}
 <div className="block text-[3.5rem] font-light leading-[4.1875rem] max-md:text-[2.125rem] max-md:leading-[2.5625rem] md:max-lg:text-[2.75rem] md:max-lg:leading-[3.3125rem]" data-ditto-id="style-section-5" id="o_wblog_post_name" placeholder="Titel blog">
 Success Stories
 </div>
 {" "}
 </span>
 {" "}
 <div className="block" data-ditto-id="style-div-30">
 <span className="inline" data-ditto-id="style-p-2">
 {" "}
 </span>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 <nav className="flex relative pt-6 justify-start items-center bg-background max-lg:flex-wrap max-lg:justify-between" data-ditto-id="style-br-4" data-component="nav">
 <div className="flex max-w-285 mx-auto px-[0.9375rem] justify-between items-center gap-2 w-[71.25rem] max-md:flex-wrap max-md:max-w-none max-md:w-[23.4375rem] md:max-lg:max-w-180 md:max-lg:w-[45rem] 2xl:max-w-330 2xl:w-[82.5rem] before:content-[''] before:hidden after:content-[''] after:hidden" data-ditto-id="style-span-20">
 <ul className="flex flex-wrap shrink-[2] [list-style-type:none] list-outside max-lg:hidden" data-ditto-id="style-span-6">
 <li className="list-item" data-ditto-id="style-br-5">
 <span className="block py-2 pr-2 text-color-013 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] cursor-default pointer-events-none">
 Blogs:
 </span>
 {" "}
 </li>
 <li className="list-item">
 <Link className="block p-2 text-color-001 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] font-semibold cursor-pointer" data-ditto-id="style-span-5" data-component="link" href="/blog">
 Alle
 </Link>
 {" "}
 </li>
 <li className="list-item" data-ditto-id="style-u">
 <Link className="h-10 block p-2 text-color-001 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] cursor-pointer" data-ditto-id="style-br-10" data-component="link" href="/blog/reis-1">
 {" "}
 <b className="inline font-bold" data-ditto-id="style-br-3">
 Reis
 </b>
 {" "}
 </Link>
 {" "}
 </li>
 <li className="list-item" data-ditto-id="style-span-7">
 <Link className="h-10 block p-2 text-color-007 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] cursor-pointer" data-ditto-id="style-br-15" data-component="link" href="/blog/success-stories-2">
 {" "}
 <b className="inline font-bold" data-ditto-id="style-br-7">
 Success Stories
 </b>
 {" "}
 </Link>
 {" "}
 </li>
 </ul>
 {" "}
 <div className="hidden relative min-w-0 order-[2] max-md:w-[21.5625rem] max-lg:block max-md:grow md:max-lg:w-[10.2625rem]" data-ditto-id="style-span-10">
 <a className="border border-solid border-border flex py-[0.45rem] px-[1.35rem] rounded-[160px] justify-between items-center align-middle text-center whitespace-nowrap text-nowrap bg-border cursor-pointer max-lg:h-[2.525rem] after:content-[''] after:block after:ml-1 max-lg:after:w-2 max-lg:after:h-1" aria-expanded="false" role="button" title="Success Stories">
 {" "}
 <span className="block min-w-0 overflow-hidden">
 Success Stories
 </span>
 {" "}
 </a>
 {" "}
 </div>
 {" "}
 <form className="block max-lg:grow">
 <div className="flex relative items-stretch" data-ditto-id="style-br-2" role="search">
 <input className="w-[12.8125rem] h-10 block relative min-w-0 py-1.5 pr-[1.4375rem] pl-3 rounded-tl-md rounded-bl-md grow overflow-clip bg-border [background-clip:padding-box] [-webkit-background-clip:padding-box] cursor-text max-md:w-[17.8125rem] md:max-lg:w-114.5" data-ditto-id="style-br-9" data-component="input" name="search" placeholder="Zoeken..." type="search" />
 {" "}
 <button className="h-[2.525rem] border border-solid border-border block relative z-2 -ml-px py-[0.45rem] px-[1.35rem] rounded-tr-md rounded-br-md align-middle text-center whitespace-nowrap text-nowrap bg-border cursor-pointer" data-ditto-id="style-span-9" data-component="button" aria-label="Zoeken" title="Zoeken" type="submit">
 <i className="inline-block [font-family:odoo\_ui\_icons] leading-4 before:content-[''] before:text-foreground before:text-base before:leading-4 before:text-center" data-ditto-id="style-br-8" />
 {" "}
 </button>
 {" "}
 </div>
 {" "}
 </form>
 {" "}
 </div>
 {" "}
 </nav>
 {" "}
 <section className="block relative" data-ditto-id="style-br-18" id="o_wblog_index_content">
 <div className="block relative max-w-285 mx-auto py-6 px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-span-15">
 <div className="flex -mx-[0.9375rem] flex-wrap justify-center" data-ditto-id="style-br-17">
 <div className="w-285 block max-w-full px-[0.9375rem] grow shrink-0 basis-[0%] max-md:w-[23.4375rem] md:max-lg:w-180 2xl:w-330" data-ditto-id="style-br-12" id="o_wblog_posts_loop_container">
 <div className="h-full block" data-ditto-id="style-span-13" id="o_wblog_posts_loop">
 <div className="h-full flex -mx-[0.9375rem] flex-wrap" data-ditto-id="style-br">
 <div className="w-285 block max-w-full px-[0.9375rem] grow shrink-0 basis-[0%] max-md:w-[23.4375rem] md:max-lg:w-180 2xl:w-330">
 <h2 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[2.75rem] font-bold leading-[3.3125rem] max-md:text-[1.8125rem] max-md:leading-[2.1875rem] md:max-lg:text-4xl md:max-lg:leading-[2.75rem]" data-component="heading">
 Nog geen blogposts.
 </h2>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <div className="block" data-ditto-id="style-br-22" id="oe_structure_blog_footer" />
 {" "}
 </div>
 {" "}
 </main>
 {" "}
 <footer className="block shrink-0 text-background bg-color-004" data-ditto-id="style-br-13" id="bottom">
 <div className="block" data-ditto-id="style-span-22" id="footer">
 <section className="block relative pt-8 pb-4" data-ditto-id="style-br-21">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 ">
 <div className="flex -mx-[0.9375rem] flex-wrap items-end" data-ditto-id="style-span-12">
 <div className="w-[17.8125rem] h-[8.1rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[123.7px] md:max-lg:w-180 md:max-lg:h-[6.2rem] 2xl:w-82.5" data-ditto-id="style-u-2">
 <p className="block mb-2">
 <font className="inline" data-ditto-id="style-br-14">
 {" "}
 <font className="inline">
 Hoe kunnen we helpen
 </font>
 {" "}
 </font>
 {" "}
 <br className="inline" data-ditto-id="style-br-16" />
 {" "}
 </p>
 {" "}
 <h4 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-2xl font-bold leading-[1.8125rem] max-md:text-[1.375rem] max-md:leading-[1.625rem] md:max-lg:text-[1.4375rem] md:max-lg:leading-[1.6875rem]" data-ditto-id="style-br-6" data-component="heading">
 <font className="inline">
 {" "}
 <font className="inline" data-ditto-id="style-bottom">
 {"U kunt altijd contact met ons opnemen "}
 </font>
 {" "}
 </font>
 {" "}
 </h4>
 {" "}
 </div>
 {" "}
 <div className="w-[17.8125rem] h-[8.15rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[128.9px] md:max-lg:w-180 md:max-lg:h-[8.1rem] 2xl:w-82.5" data-ditto-id="style-footer" aria-describedby="tooltip8305">
 <p className="block mb-2" data-ditto-id="style-section">
 <font className="inline" data-ditto-id="style-div-31">
 {" "}
 <font className="inline" data-ditto-id="style-div-7">
 Bel ons
 </font>
 {" "}
 </font>
 {" "}
 </p>
 {" "}
 <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-ditto-id="style-div-32" data-component="heading">
 <span className="inline" data-ditto-id="style-p-3">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-font-12" data-component="link" href="tel:31 (0) 33 46 11 447">
 {" "}
 <font className="inline" data-ditto-id="style-font-9">
 {" "}
 <font className="inline" data-ditto-id="style-br-23">
 {"+31 (0) 33 46 11 447 "}
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </span>
 {" "}
 </h5>
 {" "}
 <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-ditto-id="style-heading-5" data-component="heading" aria-describedby="tooltip842231">
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-font-13" data-component="link" href="tel:31 (0) 33 46 11 447">
 {" "}
 <font className="inline" data-ditto-id="style-font-3">
 {" "}
 <font className="inline" data-ditto-id="style-div">
 +31 (0) 6 11 23 88 30
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 <span className="inline" data-ditto-id="style-p-4">
 {" "}
 </span>
 {" "}
 </h5>
 {" "}
 </div>
 {" "}
 <div className="w-[17.8125rem] h-[6.075rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[6.025rem] md:max-lg:w-180 md:max-lg:h-[6.05rem] 2xl:w-82.5" data-ditto-id="style-font-41" aria-describedby="tooltip941693">
 <p className="block mb-2">
 <font className="inline" data-ditto-id="style-heading-3">
 {" "}
 <font className="inline" data-ditto-id="style-span-17">
 Stuur ons een bericht
 </font>
 {" "}
 </font>
 {" "}
 <br className="inline" data-ditto-id="style-link-6" />
 {" "}
 </p>
 {" "}
 <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-ditto-id="style-font-4" data-component="heading">
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-font-14" data-component="link" href="mailto:info@ahneta.nl">
 {" "}
 <font className="inline" data-ditto-id="style-heading">
 {" "}
 <font className="inline" data-ditto-id="style-link-7">
 info@ahneta.nl
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </h5>
 {" "}
 </div>
 {" "}
 <div className="w-[17.8125rem] h-[97.3px] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] md:max-lg:w-180 2xl:w-82.5" data-ditto-id="style-font-5">
 <div className="block text-right" data-ditto-id="style-font-42">
 <p className="block mr-[0.4rem] mb-2 align-middle" data-ditto-id="style-span-16">
 <font className="inline align-middle" data-ditto-id="style-div-13">
 {" "}
 <font className="inline align-middle">
 Volg ons
 </font>
 {" "}
 </font>
 {" "}
 </p>
 {" "}
 <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-font-15" data-component="link" href="https://www.ahneta.nl/website/social/twitter">
 {" "}
 <i className="flex m-1 justify-center items-center [font-family:FontAwesome-twitter-x-only] leading-4 before:content-[''] before:block before:w-4 before:h-4 before:text-primary before:text-base before:leading-4 before:text-right" data-ditto-id="style-font-10">
 ​
 </i>
 {" "}
 </a>
 {" "}
 <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-br-11" data-component="link" href="https://www.ahneta.nl/website/social/linkedin">
 {" "}
 <i className="flex m-1 justify-center items-center [font-family:FontAwesome] leading-4 before:content-[''] before:block before:w-[13.7px] before:h-4 before:text-primary before:text-base before:leading-4 before:text-right" data-ditto-id="style-heading-2" aria-describedby="tooltip290654">
 ​
 </i>
 {" "}
 </a>
 {" "}
 <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-link-8" data-component="link" href="https://www.ahneta.nl/website/social/instagram">
 {" "}
 <i className="flex m-1 justify-center items-center [font-family:FontAwesome] leading-4 before:content-[''] before:block before:w-[13.7px] before:h-4 before:text-primary before:text-base before:leading-4 before:text-right" data-ditto-id="style-font-6">
 ​
 </i>
 {" "}
 </a>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative" data-ditto-id="style-font-24">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 " data-ditto-id="style-div-22">
 <div className="block py-4 leading-0" data-ditto-id="style-div-11">
 <hr className="h-px border-t border-solid border-t-muted-foreground block overflow-hidden mx-auto w-[69.375rem] max-md:w-[21.5625rem] md:max-lg:w-[43.125rem] 2xl:w-[80.625rem]" data-ditto-id="style-p-7" />
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative" data-ditto-id="style-font-7">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 " data-ditto-id="style-font-35">
 <div className="flex -mx-[0.9375rem] flex-wrap items-center" data-ditto-id="style-link-9" aria-describedby="tooltip859185">
 <div className="w-47.5 h-[6.3125rem] min-h-6 block max-w-full pb-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-lg:h-34 md:max-lg:w-180 2xl:w-55 2xl:h-[116.9px]" data-ditto-id="style-i-3">
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-link-10" data-component="link" href="/">
 {" "}
 <img className="w-40 h-[5.3125rem] inline max-w-full overflow-clip align-middle max-lg:w-56.5 max-lg:h-30 2xl:w-47.5 2xl:h-[6.3125rem]" data-ditto-id="style-i-2" data-component="image" alt="" aria-label="Şirketim logosu" role="img" src="/assets/cloned/images/1461683c0d67.png" title="Benim şirketim" />
 {" "}
 </Link>
 {" "}
 </div>
 {" "}
 <div className="w-237.5 h-10 min-h-6 block max-w-full pb-4 px-[0.9375rem] shrink-0 text-right max-md:w-[23.4375rem] max-md:h-16 md:max-lg:w-180 2xl:w-275" data-ditto-id="style-link-11" aria-describedby="tooltip611099">
 <ul className="h-full block [list-style-type:none] list-outside" data-ditto-id="style-i" aria-describedby="tooltip612522">
 <li className="inline-block mr-2" data-ditto-id="style-section-2">
 {" "}
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-div-6" data-component="link" href="/">
 {" "}
 <font className="inline" data-ditto-id="style-div-5">
 {" "}
 <font className="inline" data-ditto-id="style-hr">
 Home
 </font>
 {" "}
 </font>
 {" "}
 </Link>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-section-6">
 {" "}
 <font className="inline" data-ditto-id="style-div-34">
 {" "}
 <font className="inline" data-ditto-id="style-div-4">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-div-21">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-link-12" data-component="link" href="#">
 {" "}
 <font className="inline" data-ditto-id="style-irketim-logosu">
 {" "}
 <font className="inline" data-ditto-id="style-div-12">
 Over ons
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-ul">
 {" "}
 <font className="inline" data-ditto-id="style-li">
 {" "}
 <font className="inline" data-ditto-id="style-link-13">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-font-25">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-font-16" data-component="link" href="#">
 {" "}
 <font className="inline" data-ditto-id="style-li-3">
 {" "}
 <font className="inline" data-ditto-id="style-font-22" aria-describedby="tooltip841579">
 Product
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </li>
 <li className="inline-block mr-2">
 {" "}
 <font className="inline" data-ditto-id="style-li-8">
 {" "}
 <font className="inline" data-ditto-id="style-link-14">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-font-26">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-font" data-component="link" href="#">
 {" "}
 <font className="inline" data-ditto-id="style-li-4">
 {" "}
 <font className="inline" data-ditto-id="style-font-19" aria-describedby="tooltip455312">
 Gebruiksvoorwaarden
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-font-43">
 {" "}
 <font className="inline" data-ditto-id="style-li-11">
 {" "}
 <font className="inline" data-ditto-id="style-link-15">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block" data-ditto-id="style-font-27">
 {" "}
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-font-8" data-component="link" aria-describedby="tooltip848069" href="/privacy">
 {" "}
 <font className="inline" data-ditto-id="style-li-2">
 {" "}
 <font className="inline" data-ditto-id="style-font-33">
 Privacybeleid
 </font>
 {" "}
 </font>
 {" "}
 </Link>
 {" "}
 </li>
 </ul>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 </div>
 {" "}
 <div className="block bg-color-005" data-ditto-id="style-font-2">
 <div className="block max-w-285 mx-auto py-4 px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 " data-ditto-id="style-li-12">
 <div className="flex -mx-[0.9375rem] flex-wrap" data-ditto-id="style-link-16">
 <div className="w-full block max-w-full px-[0.9375rem] grow shrink-0 basis-[0%] text-color-003 text-left max-md:text-center max-md:grow-[initial] max-md:basis-[initial]" data-ditto-id="style-font-28">
 <span className="inline align-middle" data-ditto-id="style-font-34">
 Copyright © Ahneta Advies
 </span>
 {" "}
 <p className="block mb-4">
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-font-17" data-component="link" href="/cookie-policy">
 Cookiebeleid
 </Link>
 </p>
 </div>
 {" "}
 <div className="w-142.5 block max-w-full my-[1.3125rem] px-[0.9375rem] grow shrink-0 basis-[0%] text-right max-md:w-[23.4375rem] max-md:text-center max-md:my-0 max-md:grow-[initial] max-md:basis-[initial] md:max-lg:w-90 md:max-lg:my-[0.5625rem] 2xl:w-165" data-ditto-id="style-font-11">
 <div className="h-full block" data-ditto-id="style-li-13">
 {" "}
 <a className="text-color-003 cursor-pointer hover:underline" href="https://imora.nl" target="_blank" rel="noopener noreferrer">
 Maintained by Imora
 </a>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </footer>
 {" "}
 <div className="block shrink-0" data-ditto-id="style-div-2" id="website_cookies_bar">
 {" "}
 </div>
 {" "}
 {" "}
 <div className="block">
 <div className="block" data-ditto-id="style-div-8" />
 <div className="block" data-ditto-id="style-div-14" />
 <div className="w-78 h-0 block absolute top-[52.9px] left-240 z-1055 max-md:left-[3.4375rem] md:max-lg:left-112 2xl:left-400" data-ditto-id="style-span-11" />
 <div className="w-78 h-0 block absolute top-[52.9px] left-240 z-1055 max-md:left-[3.4375rem] md:max-lg:left-112 2xl:left-400" data-ditto-id="style-p" />
 </div>
 </>
 );
}
