import "./ditto.css";
import Tile from "./components/tile";
import ListRow from "./components/list-row";
import Link from "next/link";
// Generated by clone-site. Do not edit by hand.
const Tile_data = [
    { text: "Lageprijsgarantie" },
    { text: "30 dagen online retourneren" },
    { text: "Standaard verzending" }
];
const ListRow_data = [
    { href: "/pricing", label: "Prijs" },
    { href: "/over-ons", label: "Over ons" },
    { href: "/contactus", label: "Contact" }
];
const Tile_meta: string[][] = [
    ["n10", "n11"],
    ["n12", "n13"],
    ["n14", "n15"]
];
const ListRow_meta: string[][] = [
    ["n48", "style-9", "style-15"],
    ["n51", "style-10", "style-16"],
    ["n54", "style-11", "style-17"]
];
const Tile_styles = [
    { className: "before:content-['']" },
    { className: "before:content-['']" },
    { className: "before:content-['']" }
];

export default function Page() {
  return (
    <>
      <main className="block grow shrink-0">
          <div className="h-full block" id="wrap">
            <section className="h-full block relative py-2">
              <div className="h-full block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0">
                <h2 className="block mb-2 pt-4 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[2.75rem] font-bold leading-[3.3125rem] max-md:text-[1.8125rem] max-md:leading-[2.1875rem] md:max-lg:text-4xl md:max-lg:leading-[2.75rem]" data-ditto-id="style-span-8" data-component="heading">
                  Cookiebeleid
                </h2>
                {" "}
                <p className="block mb-4" data-ditto-id="style-div-28">
                  {" Cookies zijn kleine stukjes tekst die door onze servers naar je computer of toestel worden gestuurd wanneer je onze services opent. Ze worden opgeslagen in je browser en later teruggestuurd naar onze servers, zodat we contextuele inhoud kunnen bieden. Zonder cookies zou het gebruik van internet een veel frustrerendere ervaring zijn. We gebruiken ze om je activiteiten op onze website te ondersteunen. Bijvoorbeeld je sessie (zodat jij niet opnieuw hoeft in te loggen) of je winkelmandje. "}
                  <br className="inline" data-ditto-id="style-div-33" />
                  {" Cookies worden ook gebruikt om ons te helpen je voorkeuren te begrijpen op basis van eerdere of huidige activiteiten op onze website (de pagina's die je hebt bezocht), je taal en land, waardoor wij je betere diensten kunnen verlenen. We gebruiken ook cookies om ons te helpen geaggregeerde gegevens over siteverkeer en site-interactie samen te stellen, zodat we betere site-ervaringen en tools kunnen aanbieden in de toekomst. "}
                </p>
                {" "}
                <p className="block mb-4" data-ditto-id="style-heading-6">
                  {" Hier is een overzicht van de cookies die op je apparaat kunnen worden opgeslagen wanneer je onze website bezoekt: "}
                </p>
                {" "}
                <div className="block overflow-auto" data-ditto-id="style-div-29">
                  <table className="table mb-4 align-top text-sm leading-[1.3125rem] text-center [overflow-wrap:break-word] [table-layout:fixed] [border-collapse:collapse] [border-spacing:2px] max-md:[table-layout:initial]" data-ditto-id="style-section-5">
                    <thead className="table-header-group align-bottom [border-collapse:collapse] [border-spacing:2px]" data-ditto-id="style-div-30">
                      <tr className="border-t border-solid border-t-surface border-b border-b-surface table-row align-bottom [border-collapse:collapse] [border-spacing:2px]" data-ditto-id="style-p-2">
                        <th className="border-r border-solid border-r-surface border-l border-l-surface table-cell p-3 align-bottom font-bold bg-border shadow-[var(--color-008)_0px_0px_0px_9999px_inset] [border-collapse:collapse] [border-spacing:2px]" data-ditto-id="style-br-4">
                          Cookie categorie
                        </th>
                        <th className="w-[554.5px] border-r border-solid border-r-surface border-l border-l-surface table-cell min-w-50 p-3 align-bottom font-bold bg-border shadow-[var(--color-008)_0px_0px_0px_9999px_inset] [border-collapse:collapse] [border-spacing:2px] max-md:w-50 md:max-lg:w-[344.5px] 2xl:w-[644.5px]" data-ditto-id="style-span-20">
                          Doel
                        </th>
                        <th className="border-r border-solid border-r-surface border-l border-l-surface table-cell p-3 align-bottom font-bold bg-border shadow-[var(--color-008)_0px_0px_0px_9999px_inset] [border-collapse:collapse] [border-spacing:2px]" data-ditto-id="style-span-6">
                          Voorbeelden
                        </th>
                      </tr>
                    </thead>
                    <tbody className="border-t-2 border-solid border-t-clr-0 table-row-group align-top [border-collapse:collapse] [border-spacing:2px]" data-ditto-id="style-br-5">
                      <tr className="border-t border-solid border-t-clr-0 border-b border-b-clr-0 table-row align-top [border-collapse:collapse] [border-spacing:2px]">
                        <td className="w-[13.8625rem] border-r border-solid border-r-clr-0 border-l border-l-clr-0 table-cell min-w-5 p-3 align-top shadow-[var(--color-008)_0px_0px_0px_9999px_inset] [border-collapse:collapse] [border-spacing:2px] max-md:w-[10.2rem] md:max-lg:w-[8.6125rem] 2xl:w-[16.1125rem]">
                          <p className="block mb-4 [border-collapse:collapse] [border-spacing:2px]" data-ditto-id="style-span-5">
                            {"Sessie & Beveiliging"}
                            <br className="inline [border-collapse:collapse] [border-spacing:2px]" data-ditto-id="style-u" />
                            (essentieel)
                          </p>
                          {" "}
                        </td>
                        <td className="w-[554.5px] border-r border-solid border-r-clr-0 border-l border-l-clr-0 table-cell min-w-5 p-3 align-top shadow-[var(--color-008)_0px_0px_0px_9999px_inset] [border-collapse:collapse] [border-spacing:2px] max-md:w-50 md:max-lg:w-[344.5px] 2xl:w-[644.5px]" data-ditto-id="style-br-10">
                          <p className="block mb-4 [border-collapse:collapse] [border-spacing:2px]" data-ditto-id="style-br-3">
                            {" Verifieer gebruikers, bescherm gebruikersgegevens en laat de website de diensten leveren die gebruikers verwachten, zoals het bijhouden van de inhoud van hun winkelmandje of het uploaden van bestanden. "}
                          </p>
                          {" "}
                          <p className="block mb-4 [border-collapse:collapse] [border-spacing:2px]" data-ditto-id="style-span-7">
                            De website zal niet correct werken als je deze cookies weigert of verwijdert.
                          </p>
                          {" "}
                        </td>
                        <td className="w-[332.7px] border-r border-solid border-r-clr-0 border-l border-l-clr-0 table-cell min-w-5 p-3 align-top shadow-[var(--color-008)_0px_0px_0px_9999px_inset] [border-collapse:collapse] [border-spacing:2px] max-md:w-[236.3px] md:max-lg:w-[206.7px] 2xl:w-[386.7px]" data-ditto-id="style-br-15">
                          {" session_id (Odoo)"}
                          <br className="inline [border-collapse:collapse] [border-spacing:2px]" data-ditto-id="style-br-7" />
                          {" "}
                        </td>
                      </tr>
                      <tr className="border-t border-solid border-t-clr-0 border-b border-b-clr-0 table-row align-top [border-collapse:collapse] [border-spacing:2px]" data-ditto-id="style-span-10">
                        <td className="w-[13.8625rem] border-r border-solid border-r-clr-0 border-l border-l-clr-0 table-cell min-w-5 p-3 align-top shadow-[var(--color-008)_0px_0px_0px_9999px_inset] [border-collapse:collapse] [border-spacing:2px] max-md:w-[10.2rem] md:max-lg:w-[8.6125rem] 2xl:w-[16.1125rem]">
                          <p className="block mb-4 [border-collapse:collapse] [border-spacing:2px]">
                            Voorkeuren
                            <br className="inline [border-collapse:collapse] [border-spacing:2px]" />
                            (essentieel)
                          </p>
                          {" "}
                        </td>
                        <td className="w-[554.5px] border-r border-solid border-r-clr-0 border-l border-l-clr-0 table-cell min-w-5 p-3 align-top shadow-[var(--color-008)_0px_0px_0px_9999px_inset] [border-collapse:collapse] [border-spacing:2px] max-md:w-50 md:max-lg:w-[344.5px] 2xl:w-[644.5px]" data-ditto-id="style-br-2">
                          <p className="block mb-4 [border-collapse:collapse] [border-spacing:2px]" data-ditto-id="style-br-9">
                            Onthoud informatie over het gewenste uiterlijk of gedrag van de website, zoals je voorkeurstaal of regio.
                          </p>
                          {" "}
                          <p className="block mb-4 [border-collapse:collapse] [border-spacing:2px]" data-ditto-id="style-span-9">
                            Je ervaring kan verslechteren als je die cookies weggooit, maar de website zal nog steeds werken.
                          </p>
                          {" "}
                        </td>
                        <td className="w-[332.7px] border-r border-solid border-r-clr-0 border-l border-l-clr-0 table-cell min-w-5 p-3 align-top shadow-[var(--color-008)_0px_0px_0px_9999px_inset] [border-collapse:collapse] [border-spacing:2px] max-md:w-[236.3px] md:max-lg:w-[206.7px] 2xl:w-[386.7px]" data-ditto-id="style-br-8">
                          {" frontend_lang (Odoo) "}
                        </td>
                      </tr>
                      <tr className="border-t border-solid border-t-clr-0 border-b border-b-clr-0 table-row align-top [border-collapse:collapse] [border-spacing:2px]" data-ditto-id="style-br-18">
                        <td className="w-[13.8625rem] border-r border-solid border-r-clr-0 border-l border-l-clr-0 table-cell min-w-5 p-3 align-top shadow-[var(--color-008)_0px_0px_0px_9999px_inset] [border-collapse:collapse] [border-spacing:2px] max-md:w-[10.2rem] md:max-lg:w-[8.6125rem] 2xl:w-[16.1125rem]" data-ditto-id="style-span-15">
                          Interactiegeschiedenis
                          <br className="inline [border-collapse:collapse] [border-spacing:2px]" data-ditto-id="style-br-17" />
                          (optioneel)
                        </td>
                        <td className="w-[554.5px] border-r border-solid border-r-clr-0 border-l border-l-clr-0 table-cell min-w-5 p-3 align-top shadow-[var(--color-008)_0px_0px_0px_9999px_inset] [border-collapse:collapse] [border-spacing:2px] max-md:w-50 md:max-lg:w-[344.5px] 2xl:w-[644.5px]" data-ditto-id="style-br-12">
                          <p className="block mb-4 [border-collapse:collapse] [border-spacing:2px]" data-ditto-id="style-span-13">
                            {" Wordt gebruikt om informatie te verzamelen over je interacties met de website, de pagina's die je hebt gezien en elke specifieke marketingcampagne die je naar de website heeft geleid. "}
                          </p>
                          {" "}
                          <p className="block mb-4 [border-collapse:collapse] [border-spacing:2px]" data-ditto-id="style-br">
                            We kunnen je mogelijk niet de beste service bieden als je die cookies weigert, maar de website werkt wel.
                          </p>
                          {" "}
                        </td>
                        <td className="w-[332.7px] border-r border-solid border-r-clr-0 border-l border-l-clr-0 table-cell min-w-5 p-3 align-top shadow-[var(--color-008)_0px_0px_0px_9999px_inset] [border-collapse:collapse] [border-spacing:2px] max-md:w-[236.3px] md:max-lg:w-[206.7px] 2xl:w-[386.7px]">
                          {" im_livechat_previous_operator_pid (Odoo)"}
                          <br className="inline [border-collapse:collapse] [border-spacing:2px]" />
                          {" utm_campaign (Odoo)"}
                          <br className="inline [border-collapse:collapse] [border-spacing:2px]" data-ditto-id="style-br-22" />
                          {" utm_source (Odoo)"}
                          <br className="inline [border-collapse:collapse] [border-spacing:2px]" data-ditto-id="style-br-13" />
                          {" utm_medium (Odoo) "}
                        </td>
                      </tr>
                      <tr className="border-t border-solid border-t-clr-0 border-b border-b-clr-0 table-row align-top [border-collapse:collapse] [border-spacing:2px]" data-ditto-id="style-span-22">
                        <td className="w-[13.8625rem] border-r border-solid border-r-clr-0 border-l border-l-clr-0 table-cell min-w-5 p-3 align-top shadow-[var(--color-008)_0px_0px_0px_9999px_inset] [border-collapse:collapse] [border-spacing:2px] max-md:w-[10.2rem] md:max-lg:w-[8.6125rem] 2xl:w-[16.1125rem]" data-ditto-id="style-br-21">
                          <p className="block mb-4 [border-collapse:collapse] [border-spacing:2px]">
                            {"Reclame & Marketing"}
                            <br className="inline [border-collapse:collapse] [border-spacing:2px]" data-ditto-id="style-span-12" />
                            (optioneel)
                          </p>
                          {" "}
                        </td>
                        <td className="w-[554.5px] border-r border-solid border-r-clr-0 border-l border-l-clr-0 table-cell min-w-5 p-3 align-top shadow-[var(--color-008)_0px_0px_0px_9999px_inset] [border-collapse:collapse] [border-spacing:2px] max-md:w-50 md:max-lg:w-[344.5px] 2xl:w-[644.5px]" data-ditto-id="style-u-2">
                          <p className="block mb-4 [border-collapse:collapse] [border-spacing:2px]">
                            {" Wordt gebruikt om advertenties aantrekkelijker te maken voor gebruikers en waardevoller voor uitgevers en adverteerders, zoals het aanbieden van relevantere advertenties wanneer je andere websites bezoekt waarop advertenties worden weergegeven of om de rapportage over de prestaties van advertentiecampagnes te verbeteren. "}
                          </p>
                          {" "}
                          <p className="block mb-4 [border-collapse:collapse] [border-spacing:2px]" data-ditto-id="style-br-14">
                            Houd er rekening mee dat sommige services van derden aanvullende cookies in je browser kunnen installeren om je te identificeren.
                          </p>
                          {" "}
                          <p className="block mb-4 [border-collapse:collapse] [border-spacing:2px]">
                            {" Je kunt zich afmelden voor het gebruik van cookies door een derde partij door de "}
                            <a className="inline text-color-002 cursor-pointer [border-collapse:collapse] [border-spacing:2px]" data-ditto-id="style-br-16" data-component="link" href="https://optout.networkadvertising.org/?c=1" rel="nofollow">
                              Afmeldingspagina voor Network Advertising Initiative
                            </a>
                            {". De website werkt nog steeds als je deze cookies weigert of verwijdert. "}
                          </p>
                          {" "}
                        </td>
                        <td className="w-[332.7px] border-r border-solid border-r-clr-0 border-l border-l-clr-0 table-cell min-w-5 p-3 align-top shadow-[var(--color-008)_0px_0px_0px_9999px_inset] [border-collapse:collapse] [border-spacing:2px] max-md:w-[236.3px] md:max-lg:w-[206.7px] 2xl:w-[386.7px]" data-ditto-id="style-br-6">
                          {" __gads (Google)"}
                          <br className="inline [border-collapse:collapse] [border-spacing:2px]" />
                          {" __gac (Google) "}
                        </td>
                      </tr>
                      <tr className="border-t border-solid border-t-clr-0 border-b border-b-clr-0 table-row align-top [border-collapse:collapse] [border-spacing:2px]" data-ditto-id="style-bottom">
                        <td className="w-[13.8625rem] border-r border-solid border-r-clr-0 border-l border-l-clr-0 table-cell min-w-5 p-3 align-top shadow-[var(--color-008)_0px_0px_0px_9999px_inset] [border-collapse:collapse] [border-spacing:2px] max-md:w-[10.2rem] md:max-lg:w-[8.6125rem] 2xl:w-[16.1125rem]" data-ditto-id="style-footer">
                          <p className="block mb-4 [border-collapse:collapse] [border-spacing:2px]" data-ditto-id="style-section">
                            Analytics
                            <br className="inline [border-collapse:collapse] [border-spacing:2px]" data-ditto-id="style-div-31" />
                            (optioneel)
                          </p>
                          {" "}
                        </td>
                        <td className="w-[554.5px] border-r border-solid border-r-clr-0 border-l border-l-clr-0 table-cell min-w-5 p-3 align-top shadow-[var(--color-008)_0px_0px_0px_9999px_inset] [border-collapse:collapse] [border-spacing:2px] max-md:w-50 md:max-lg:w-[344.5px] 2xl:w-[644.5px]" data-ditto-id="style-div-7">
                          <p className="block mb-4 [border-collapse:collapse] [border-spacing:2px]" data-ditto-id="style-div-32">
                            {" Begrijp hoe bezoekers omgaan met onze website, via Google Analytics. Leer meer over "}
                            <a className="inline text-color-002 cursor-pointer [border-collapse:collapse] [border-spacing:2px]" data-ditto-id="style-p-3" data-component="link" href="https://developers.google.com/analytics/resources/concepts/gaConceptsCookies?hl=en">
                              Analytics cookies en privacy-informatie.
                            </a>
                            {" "}
                          </p>
                          {" "}
                          <p className="block mb-4 [border-collapse:collapse] [border-spacing:2px]" data-ditto-id="style-font-12">
                            De website werkt nog steeds als je deze cookies weigert of verwijdert.
                          </p>
                          {" "}
                        </td>
                        <td className="w-[332.7px] border-r border-solid border-r-clr-0 border-l border-l-clr-0 table-cell min-w-5 p-3 align-top shadow-[var(--color-008)_0px_0px_0px_9999px_inset] [border-collapse:collapse] [border-spacing:2px] max-md:w-[236.3px] md:max-lg:w-[206.7px] 2xl:w-[386.7px]" data-ditto-id="style-font-9">
                          {" _ga (Google)"}
                          <br className="inline [border-collapse:collapse] [border-spacing:2px]" data-ditto-id="style-br-23" />
                          {" _gat (Google)"}
                          <br className="inline [border-collapse:collapse] [border-spacing:2px]" data-ditto-id="style-heading-5" />
                          {" _gid (Google)"}
                          <br className="inline [border-collapse:collapse] [border-spacing:2px]" data-ditto-id="style-font-13" />
                          {" _gac_* (Google) "}
                        </td>
                      </tr>
                    </tbody>
                  </table>
                  {" "}
                </div>
                {" "}
                <p className="block mb-4" data-ditto-id="style-font-3">
                  {" Je kunt ervoor kiezen om je computer je te laten waarschuwen telkens wanneer een cookie wordt verzonden, of je kunt ervoor kiezen om alle cookies uit te schakelen. Elke browser is een beetje anders, dus kijk in het Help-menu van je browser voor de juiste manier om je cookies aan te passen. "}
                </p>
                {" "}
                <p className="block mb-4" data-ditto-id="style-div">
                  We ondersteunen momenteel geen Do Not Track-signalen, aangezien er geen industriestandaard is voor naleving.
                </p>
                {" "}
              </div>
              {" "}
            </section>
            {" "}
          </div>
          {" "}
        </main>
        {" "}
        <footer className="block shrink-0 text-background bg-color-004" data-ditto-id="style-p-4" id="bottom">
          <div className="block" data-ditto-id="style-font-41" id="footer">
            <section className="block relative pt-8 pb-4">
              <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330" data-ditto-id="style-heading-3">
                <div className="flex -mx-[0.9375rem] flex-wrap items-end" data-ditto-id="style-span-17">
                  <div className="w-[17.8125rem] h-[8.1rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[123.7px] md:max-lg:w-180 md:max-lg:h-[6.2rem] 2xl:w-82.5" data-ditto-id="style-link-6">
                    <p className="block mb-2" data-ditto-id="style-font-4">
                      <font className="inline" data-ditto-id="style-font-14">
                        {" "}
                        <font className="inline" data-ditto-id="style-heading">
                          Hoe kunnen we helpen
                        </font>
                        {" "}
                      </font>
                      {" "}
                      <br className="inline" data-ditto-id="style-link-7" />
                      {" "}
                    </p>
                    {" "}
                    <h4 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-2xl font-bold leading-[1.8125rem] max-md:text-[1.375rem] max-md:leading-[1.625rem] md:max-lg:text-[1.4375rem] md:max-lg:leading-[1.6875rem]" data-ditto-id="style-font-5" data-component="heading">
                      <font className="inline" data-ditto-id="style-font-42">
                        {" "}
                        <font className="inline" data-ditto-id="style-span-16">
                          {"U kunt altijd contact met ons opnemen "}
                        </font>
                        {" "}
                      </font>
                      {" "}
                    </h4>
                    {" "}
                  </div>
                  {" "}
                  <div className="w-[17.8125rem] h-[8.15rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[128.9px] md:max-lg:w-180 md:max-lg:h-[8.1rem] 2xl:w-82.5" data-ditto-id="style-div-13" aria-describedby="tooltip8305">
                    <p className="block mb-2">
                      <font className="inline" data-ditto-id="style-font-15">
                        {" "}
                        <font className="inline" data-ditto-id="style-font-10">
                          Bel ons
                        </font>
                        {" "}
                      </font>
                      {" "}
                    </p>
                    {" "}
                    <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-ditto-id="style-br-11" data-component="heading">
                      <span className="inline" data-ditto-id="style-heading-2">
                        {" "}
                        <a className="inline text-primary cursor-pointer" data-ditto-id="style-link-8" data-component="link" href="tel:31 (0) 33 46 11 447">
                          {" "}
                          <font className="inline" data-ditto-id="style-font-6">
                            {" "}
                            <font className="inline" data-ditto-id="style-font-24">
                              {"+31 (0) 33 46 11 447 "}
                            </font>
                            {" "}
                          </font>
                          {" "}
                        </a>
                        {" "}
                      </span>
                      {" "}
                    </h5>
                    {" "}
                    <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-ditto-id="style-div-22" data-component="heading" aria-describedby="tooltip842231">
                      <a className="inline text-primary cursor-pointer" data-ditto-id="style-div-11" data-component="link" href="tel:31 (0) 33 46 11 447">
                        {" "}
                        <font className="inline" data-ditto-id="style-p-7">
                          {" "}
                          <font className="inline" data-ditto-id="style-font-7">
                            +31 (0) 6 11 23 88 30
                          </font>
                          {" "}
                        </font>
                        {" "}
                      </a>
                      {" "}
                      <span className="inline" data-ditto-id="style-font-35">
                        {" "}
                      </span>
                      {" "}
                    </h5>
                    {" "}
                  </div>
                  {" "}
                  <div className="w-[17.8125rem] h-[6.075rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[6.025rem] md:max-lg:w-180 md:max-lg:h-[6.05rem] 2xl:w-82.5" data-ditto-id="style-link-9" aria-describedby="tooltip941693">
                    <p className="block mb-2" data-ditto-id="style-i-3">
                      <font className="inline" data-ditto-id="style-link-10">
                        {" "}
                        <font className="inline" data-ditto-id="style-i-2">
                          Stuur ons een bericht
                        </font>
                        {" "}
                      </font>
                      {" "}
                      <br className="inline" data-ditto-id="style-link-11" />
                      {" "}
                    </p>
                    {" "}
                    <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-ditto-id="style-i" data-component="heading">
                      <a className="inline text-primary cursor-pointer" data-ditto-id="style-section-2" data-component="link" href="mailto:info@ahneta.nl">
                        {" "}
                        <font className="inline" data-ditto-id="style-div-6">
                          {" "}
                          <font className="inline" data-ditto-id="style-div-5">
                            info@ahneta.nl
                          </font>
                          {" "}
                        </font>
                        {" "}
                      </a>
                      {" "}
                    </h5>
                    {" "}
                  </div>
                  {" "}
                  <div className="w-[17.8125rem] h-[97.3px] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] md:max-lg:w-180 2xl:w-82.5" data-ditto-id="style-hr">
                    <div className="block text-right" data-ditto-id="style-section-6">
                      <p className="block mr-[0.4rem] mb-2 align-middle" data-ditto-id="style-div-34">
                        <font className="inline align-middle" data-ditto-id="style-div-4">
                          {" "}
                          <font className="inline align-middle" data-ditto-id="style-div-21">
                            Volg ons
                          </font>
                          {" "}
                        </font>
                        {" "}
                      </p>
                      {" "}
                      <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-link-12" data-component="link" href="https://www.ahneta.nl/website/social/twitter">
                        {" "}
                        <i className="flex m-1 justify-center items-center [font-family:FontAwesome-twitter-x-only] leading-4 before:content-[''] before:block before:w-4 before:h-4 before:text-primary before:text-base before:leading-4 before:text-right" data-ditto-id="style-irketim-logosu">
                          ​
                        </i>
                        {" "}
                      </a>
                      {" "}
                      <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-div-12" data-component="link" href="https://www.ahneta.nl/website/social/linkedin">
                        {" "}
                        <i className="flex m-1 justify-center items-center [font-family:FontAwesome] leading-4 before:content-[''] before:block before:w-[13.7px] before:h-4 before:text-primary before:text-base before:leading-4 before:text-right" data-ditto-id="style-ul" aria-describedby="tooltip290654">
                          ​
                        </i>
                        {" "}
                      </a>
                      {" "}
                      <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-li" data-component="link" href="https://www.ahneta.nl/website/social/instagram">
                        {" "}
                        <i className="flex m-1 justify-center items-center [font-family:FontAwesome] leading-4 before:content-[''] before:block before:w-[13.7px] before:h-4 before:text-primary before:text-base before:leading-4 before:text-right" data-ditto-id="style-link-13">
                          ​
                        </i>
                        {" "}
                      </a>
                      {" "}
                    </div>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </section>
            {" "}
            <section className="block relative" data-ditto-id="style-font-25">
              <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330" data-ditto-id="style-font-16">
                <div className="block py-4 leading-0" data-ditto-id="style-li-3">
                  <hr className="h-px border-t border-solid border-t-muted-foreground block overflow-hidden mx-auto w-[69.375rem] max-md:w-[21.5625rem] md:max-lg:w-[43.125rem] 2xl:w-[80.625rem]" data-ditto-id="style-font-22" />
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </section>
            {" "}
            <section className="block relative">
              <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330" data-ditto-id="style-li-8">
                <div className="flex -mx-[0.9375rem] flex-wrap items-center" data-ditto-id="style-link-14" aria-describedby="tooltip859185">
                  <div className="w-47.5 h-[6.3125rem] min-h-6 block max-w-full pb-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-lg:h-34 md:max-lg:w-180 2xl:w-55 2xl:h-[116.9px]" data-ditto-id="style-font-26">
                    <Link className="inline text-primary cursor-pointer" data-ditto-id="style-font" data-component="link" href="/">
                      {" "}
                      <img className="w-40 h-[5.3125rem] inline max-w-full overflow-clip align-middle max-lg:w-56.5 max-lg:h-30 2xl:w-47.5 2xl:h-[6.3125rem]" data-ditto-id="style-li-4" data-component="image" alt="" aria-label="Şirketim logosu" role="img" src="/assets/cloned/images/1461683c0d67.png" title="Benim şirketim" />
                      {" "}
                    </Link>
                    {" "}
                  </div>
                  {" "}
                  <div className="w-237.5 h-10 min-h-6 block max-w-full pb-4 px-[0.9375rem] shrink-0 text-right max-md:w-[23.4375rem] max-md:h-16 md:max-lg:w-180 2xl:w-275" data-ditto-id="style-font-19" aria-describedby="tooltip611099">
                    <ul className="h-full block [list-style-type:none] list-outside" data-ditto-id="style-font-43" aria-describedby="tooltip612522">
                      <li className="inline-block mr-2" data-ditto-id="style-li-11">
                        {" "}
                        <Link className="inline text-primary cursor-pointer" data-ditto-id="style-link-15" data-component="link" href="/">
                          {" "}
                          <font className="inline" data-ditto-id="style-font-27">
                            {" "}
                            <font className="inline" data-ditto-id="style-font-8">
                              Home
                            </font>
                            {" "}
                          </font>
                          {" "}
                        </Link>
                        {" "}
                      </li>
                      <li className="inline-block mr-2" data-ditto-id="style-li-2">
                        {" "}
                        <font className="inline" data-ditto-id="style-font-33">
                          {" "}
                          <font className="inline" data-ditto-id="style-font-2">
                            •
                          </font>
                          {" "}
                        </font>
                        {" "}
                      </li>
                      <li className="inline-block mr-2" data-ditto-id="style-li-12">
                        {" "}
                        <a className="inline text-primary cursor-pointer" data-ditto-id="style-link-16" data-component="link" href="#">
                          {" "}
                          <font className="inline" data-ditto-id="style-font-28">
                            {" "}
                            <font className="inline" data-ditto-id="style-font-34">
                              Over ons
                            </font>
                            {" "}
                          </font>
                          {" "}
                        </a>
                        {" "}
                      </li>
                      <li className="inline-block mr-2">
                        {" "}
                        <font className="inline" data-ditto-id="style-font-17">
                          {" "}
                          <font className="inline" data-ditto-id="style-font-11">
                            •
                          </font>
                          {" "}
                        </font>
                        {" "}
                      </li>
                      <li className="inline-block mr-2" data-ditto-id="style-li-13">
                        {" "}
                        <a className="inline text-primary cursor-pointer" data-ditto-id="style-link-17" data-component="link" href="#">
                          {" "}
                          <font className="inline">
                            {" "}
                            <font className="inline" data-ditto-id="style-font-18" aria-describedby="tooltip841579">
                              Product
                            </font>
                            {" "}
                          </font>
                          {" "}
                        </a>
                        {" "}
                      </li>
                      <li className="inline-block mr-2" data-ditto-id="style-div-2">
                        {" "}
                        <font className="inline">
                          {" "}
                          <font className="inline" data-ditto-id="style-div-8">
                            •
                          </font>
                          {" "}
                        </font>
                        {" "}
                      </li>
                      <li className="inline-block mr-2" data-ditto-id="style-div-14">
                        {" "}
                        <a className="inline text-primary cursor-pointer" data-ditto-id="style-span-11" data-component="link" href="#">
                          {" "}
                          <font className="inline" data-ditto-id="style-p">
                            {" "}
                            <font className="inline" data-ditto-id="style-link-18" aria-describedby="tooltip455312">
                              Gebruiksvoorwaarden
                            </font>
                            {" "}
                          </font>
                          {" "}
                        </a>
                        {" "}
                      </li>
                      <li className="inline-block mr-2" data-ditto-id="style-div-15">
                        {" "}
                        <font className="inline">
                          {" "}
                          <font className="inline" data-ditto-id="style-link-40">
                            •
                          </font>
                          {" "}
                        </font>
                        {" "}
                      </li>
                      <li className="inline-block" data-ditto-id="style-image">
                        {" "}
                        <Link className="inline text-primary cursor-pointer" data-ditto-id="style-link-19" data-component="link" aria-describedby="tooltip848069" href="/privacy">
                          {" "}
                          <font className="inline" data-ditto-id="style-website-cookies-bar">
                            {" "}
                            <font className="inline" data-ditto-id="style-div-26">
                              Privacybeleid
                            </font>
                            {" "}
                          </font>
                          {" "}
                        </Link>
                        {" "}
                      </li>
                    </ul>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </section>
            {" "}
          </div>
          {" "}
          <div className="block bg-color-005">
            <div className="block max-w-285 mx-auto py-4 px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330" data-ditto-id="style-div-27">
              <div className="flex -mx-[0.9375rem] flex-wrap" data-ditto-id="style-div-9">
                <div className="w-full block max-w-full px-[0.9375rem] grow shrink-0 basis-[0%] text-color-003 text-left max-md:text-center max-md:grow-[initial] max-md:basis-[initial]" data-ditto-id="style-div-16">
                  <span className="inline align-middle">
                    Copyright © Ahneta Advies
                  </span>
                  {" "}
                  <p className="block mb-4" data-ditto-id="style-link-21">
                    <Link className="inline text-primary cursor-pointer" data-ditto-id="style-font-21" data-component="link" href="/cookie-policy">
                      Cookiebeleid
                    </Link>
                  </p>
                </div>
                {" "}
                <div className="w-142.5 block max-w-full my-[1.3125rem] px-[0.9375rem] grow shrink-0 basis-[0%] text-right max-md:w-[23.4375rem] max-md:text-center max-md:my-0 max-md:grow-[initial] max-md:basis-[initial] md:max-lg:w-90 md:max-lg:my-[0.5625rem] 2xl:w-165" data-ditto-id="style-font-36">
                  <div className="h-full block">
                    {" "}
                    <a className="text-color-003 cursor-pointer hover:underline" href="https://imora.nl" target="_blank" rel="noopener noreferrer">
                      Maintained by Imora
                    </a>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </footer>
        {" "}
        <button className="w-[9.7625rem] h-[1.85rem] border border-solid border-color-012 flex fixed right-4 bottom-4 z-1056 min-w-0 py-[0.3rem] px-[0.9rem] rounded-[100px] items-center shrink-0 gap-2 align-middle text-background text-xs leading-4.5 text-center bg-color-012 cursor-pointer" data-ditto-id="style-link-22" data-component="button">
          <i className="block [font-family:FontAwesome] leading-3 before:content-[''] before:text-background before:text-xs before:leading-3 before:text-center" data-ditto-id="style-font-23" alt="" aria-hidden="true" />
          {" "}
          <span className="block">
            Toon de cookiesbalk
          </span>
          {" "}
        </button>
        <div className="block shrink-0" data-ditto-id="style-li-7" id="website_cookies_bar">
          {" "}
        </div>
        {" "}
      {" "}
      <div className="block">
        <div className="block" />
        <div className="block" data-ditto-id="style-li-5" />
        <div className="w-78 h-0 block absolute top-[52.9px] left-240 z-1055 max-md:left-[3.4375rem] md:max-lg:left-112 2xl:left-400" data-ditto-id="style-link-23" />
        <div className="w-78 h-0 block absolute top-[52.9px] left-240 z-1055 max-md:left-[3.4375rem] md:max-lg:left-112 2xl:left-400" />
 </div>
    </>
  );
}
