import "./ditto.css";
import Tile from "./components/tile";
import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
import Logo from "./components/logo";
import QuoteCarousel from "./components/quote-carousel";
import Link from "next/link";
export const metadata = {
 title: "Bedrijven | Ahneta Advies",
 alternates: {
 canonical: "/bedrijven"
 },
 openGraph: {
 title: "Bedrijven | Ahneta Advies",
 url: "/bedrijven"
 },
 twitter: {
 title: "Bedrijven | Ahneta Advies"
 }
};
// Generated by clone-site. Do not edit by hand.
const Tile_data = [
 { text: "Lageprijsgarantie" },
 { text: "30 dagen online retourneren" },
 { text: "Standaard verzending" }
];
const ListRow_data = [
 { href: "/pricing", label: "Prijs" },
 { href: "/over-ons", label: "Over ons" },
 { href: "/contactus", label: "Contact" }
];
const ListRow2_data = [
 { text: "Verzorging van de complete bedrijfsboekhouding." },
 { text: "Controle van de door u ingevoerde boekhouding." },
 { text: "Opstellen van jaarrekeningen." },
 { text: "Verzorging van loonadministratie inclusief periodieke aangifte." },
 { text: "Verzorging van periodieke aangifte BTW." },
 { text: "Verzorging van aangifte VPB (Vennootschapsbelasting)." },
 { text: "Advisering bij bedrijfsovernames." }
];
const Logo_data = [
 { ariadescribedby: "tooltip956794", imgSrc: "/assets/cloned/images/9b235f68888a.png" },
 { ariadescribedby: "tooltip185143", imgSrc: "/assets/cloned/images/156e327bf149.png" },
 { ariadescribedby: "tooltip729894", imgSrc: "/assets/cloned/images/fe97ae990133.png" }
];
const Tile_meta: string[][] = [
 ["n10", "n11"],
 ["n12", "n13"],
 ["n14", "n15"]
];
const ListRow_meta: string[][] = [
 ["n48", "style-9", "style-15"],
 ["n51", "style-10", "style-16"],
 ["n54", "style-11", "style-17"]
];
const ListRow2_meta: string[][] = [
 ["n83"],
 ["style-span-5"],
 ["style-u"],
 ["style-br-10"],
 ["style-br-3"],
 ["style-span-7"],
 ["style-br-15"]
];
const Logo_meta: string[][] = [
 ["n281", "n282"],
 ["style-myquotecarousel617108", "n284"],
 ["style-li-9", "style-li-10"]
];
const Tile_styles = [
 { className: "before:content-['']" },
 { className: "before:content-['']" },
 { className: "before:content-['']" }
];
const Logo_styles = [
 { className: "w-55.5 h-25" },
 { className: "w-87.5 h-27.5 max-md:w-[21.5625rem] max-md:h-[6.8125rem] md:max-lg:w-[38.8125rem] md:max-lg:h-49 2xl:w-102.5 2xl:h-[8.0625rem]" },
 { className: "w-87.5 h-[4.6875rem] max-md:w-[21.5625rem] max-md:h-18.5 md:max-lg:w-172.5 md:max-lg:h-[9.1875rem] 2xl:w-102.5 2xl:h-[5.4375rem]" }
];

export default function Page() {
 return (
 <>
 <main className="block grow shrink-0">
 <div className="h-full block" id="wrap">
 <div className="block">
 <section className="block relative py-6 overflow-hidden text-background bg-color-004">
 <span className="h-full block absolute top-0 inset-x-0 overflow-hidden bg-cover [background-position:50%_0px] bg-no-repeat [background-attachment:fixed] pointer-events-none max-lg:[background-attachment:initial]" style={{ backgroundImage: "url(\"/assets/cloned/images/2873c8e777c4.jpg\")" }} data-ditto-id="style-span-8" />
 {" "}
 <div className="h-full block absolute top-0 inset-x-0 overflow-hidden bg-color-004 bg-no-repeat pointer-events-none" data-ditto-id="style-div-28" />
 {" "}
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-div-33">
 <h1 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[3.875rem] font-bold leading-[4.625rem] max-md:text-4xl max-md:leading-[2.6875rem] md:max-lg:text-5xl md:max-lg:leading-[3.625rem]" data-ditto-id="style-heading-6" data-component="heading">
 Diensten Bedrijven
 </h1>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 </div>
 {" "}
 <div className="block" data-ditto-id="style-div-29">
 <section className="block relative py-10 bg-border" data-ditto-id="style-section-5">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-div-30">
 <h1 className="block mb-2 text-color-005 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[3.875rem] font-bold leading-[4.625rem] text-center max-md:text-4xl max-md:leading-[2.6875rem] md:max-lg:text-5xl md:max-lg:leading-[3.625rem]" data-ditto-id="style-p-2" data-component="heading">
 <font className="inline text-color-010 max-lg:text-[3.875rem] max-lg:leading-[4.625rem]" data-ditto-id="style-br-4">
 Ahneta Advies is gespecialiseerd in:
 </font>
 {" "}
 <br className="inline" data-ditto-id="style-span-20" />
 {" "}
 </h1>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative py-10 bg-background" data-ditto-id="style-span-6">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-br-5">
 <ul className="block mb-4 pl-8 [list-style-type:disc] list-outside">
 {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} />)}
 <li className="list-item" data-ditto-id="style-br-7">
 Al vanaf de start van de onderneming heeft Ahneta zich dienstverlenend voor het MKB geprofileerd. Het pakket aan diensten voor het MKB is in de loop der jaren steeds verder uitgebreid.
 <br className="inline" data-ditto-id="style-span-10" />
 <br className="inline" />
 Door de wijziging van wetgeving verzorgt Ahneta ook voor besloten vennootschappen (B.V.) het complete traject vanaf controle boekhouding tot opstelling van de jaarrekening en de aangifte VPB.
 <br className="inline" />
 <br className="inline" />
 {" Uiteraard kunnen ook de eenmanszaak (ZZP’er) of de vennootschap onder firma ("}
 <a className="inline text-color-002 cursor-pointer" data-ditto-id="style-br-2" data-component="link" href="https://v.o.f.)/">
 V.O.F.)
 </a>
 {" door Ahneta worden begeleid."}
 <br className="inline" data-ditto-id="style-br-9" />
 <br className="inline" data-ditto-id="style-span-9" />
 Alvorens Ahneta voor uw bedrijf werkzaamheden kan verrichten wordt er eerst met u een prijsafspraak gemaakt. In de prijsafspraak wordt helder weergegeven welke werkzaamheden Ahneta voor u zal gaan verrichten en wat de uitvoering van deze werkzaamheden u gaat kosten.
 <br className="inline" data-ditto-id="style-br-8" />
 <br className="inline" data-ditto-id="style-br-18" />
 {" Indien Ahneta voor u de complete boekhouding verzorgt wordt duidelijk aangegeven op hoeveel boekingen de prijsopgave is gebaseerd. Hierop is een met u overeengekomen marge van meer of minder boekingen van toepassing. Worden er minder boekingen verricht ontvangt u een restitutie van honorarium en indien er meer boeking verricht moeten worden wordt de meerprijs aan u extra gedeclareerd. De declaratie wordt u per maand of per kwartaal toegezonden."}
 <br className="inline" data-ditto-id="style-span-15" />
 </li>
 </ul>
 {" "}
 <p className="block mb-4" data-ditto-id="style-br-17">
 <br className="inline" data-ditto-id="style-br-12" />
 {" "}
 </p>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative" data-ditto-id="style-span-13">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-br">
 <div className="flex -mx-[0.9375rem] flex-wrap">
 <div className="w-95 block max-w-full px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] md:max-lg:w-180 2xl:w-110">
 <p className="block mb-4" data-ditto-id="style-br-22">
 <span className="inline font-bold" data-ditto-id="style-br-13">
 FINANCIËLE ADMINISTRATIE EN ADVIES
 </span>
 <br className="inline" data-ditto-id="style-span-22" />
 <i className="inline italic" data-ditto-id="style-br-21">
 Administratieve werkzaamheden
 <br className="inline" />
 </i>
 <br className="inline" data-ditto-id="style-span-12" />
 • Verwerken beoordelen administratie;
 <br className="inline" data-ditto-id="style-u-2" />
 <br className="inline" />
 • Jaarrekening enkelvoudig;
 <br className="inline" data-ditto-id="style-br-14" />
 <br className="inline" />
 • Jaarrekening geconsolideerd;
 <br className="inline" data-ditto-id="style-br-16" />
 <br className="inline" data-ditto-id="style-br-6" />
 • Deponeren stukken bij KvK / opstellen notulen;
 <br className="inline" />
 <br className="inline" data-ditto-id="style-bottom" />
 • Overige werkzaamheden: advisering en aanvullende diensten;
 <br className="inline" data-ditto-id="style-footer" />
 <br className="inline" data-ditto-id="style-section" />
 • Overleg / communicatie; bij vaste prijsafspraak 2 uur inbegrepen.
 <br className="inline" data-ditto-id="style-div-31" />
 <br className="inline" data-ditto-id="style-div-7" />
 <br className="inline" data-ditto-id="style-div-32" />
 </p>
 {" "}
 <p className="block mb-4" data-ditto-id="style-p-3">
 <br className="inline" data-ditto-id="style-font-12" />
 {" "}
 </p>
 {" "}
 </div>
 {" "}
 <div className="w-95 block max-w-full px-[0.9375rem] shrink-0 bg-border max-md:w-[23.4375rem] md:max-lg:w-180 2xl:w-110" data-ditto-id="style-font-9">
 <p className="block mb-4" data-ditto-id="style-br-23">
 <span className="inline font-bold" data-ditto-id="style-heading-5">
 BELASTINGADVIES
 </span>
 <br className="inline" data-ditto-id="style-font-13" />
 <i className="inline italic" data-ditto-id="style-font-3">
 Fiscale werkzaamheden
 <br className="inline" data-ditto-id="style-div" />
 <br className="inline" data-ditto-id="style-p-4" />
 </i>
 • Aangifte inkomstenbelasting DGA;
 <br className="inline" data-ditto-id="style-font-41" />
 <br className="inline" />
 • Aangifte inkomstenbelasting ondernemer (een onderneming);
 <br className="inline" data-ditto-id="style-heading-3" />
 <br className="inline" data-ditto-id="style-span-17" />
 • Aangifte inkomstenbelasting partner (niet zijnde de ondernemer);
 <br className="inline" data-ditto-id="style-link-6" />
 <br className="inline" data-ditto-id="style-font-4" />
 • Aangifte vennootschapsbelasting (enkelvoudige BV);
 <br className="inline" data-ditto-id="style-font-14" />
 <br className="inline" data-ditto-id="style-heading" />
 • Aangifte vennootschapsbelasting (fiscale eenheid 2 BV’s);
 <br className="inline" data-ditto-id="style-link-7" />
 <br className="inline" data-ditto-id="style-font-5" />
 • Aangifte omzetbelasting;
 <br className="inline" data-ditto-id="style-font-42" />
 <br className="inline" data-ditto-id="style-span-16" />
 • Overige aangifte(n) en werkzaamheden (advisering, begeleiding, bezwaarprocedures).
 <br className="inline" data-ditto-id="style-div-13" />
 <br className="inline" />
 <br className="inline" data-ditto-id="style-font-15" />
 <br className="inline" data-ditto-id="style-font-10" />
 <br className="inline" data-ditto-id="style-br-11" />
 </p>
 {" "}
 <p className="block mb-4" data-ditto-id="style-heading-2">
 <br className="inline" data-ditto-id="style-link-8" />
 {" "}
 </p>
 {" "}
 </div>
 {" "}
 <div className="w-95 block max-w-full px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] md:max-lg:w-180 2xl:w-110" data-ditto-id="style-font-6">
 <p className="block mb-4" data-ditto-id="style-font-24">
 <span className="inline font-bold" data-ditto-id="style-div-22">
 SALARISADMINISTRATIE
 </span>
 <br className="inline" data-ditto-id="style-div-11" />
 <i className="inline italic" data-ditto-id="style-p-7">
 Loon administratieve werkzaamheden
 <br className="inline" data-ditto-id="style-font-7" />
 <br className="inline" data-ditto-id="style-font-35" />
 </i>
 • Opzetten en inrichten loonadministratie;
 <br className="inline" data-ditto-id="style-link-9" />
 <br className="inline" data-ditto-id="style-i-3" />
 • Verwerken loonadministratie;
 <br className="inline" data-ditto-id="style-link-10" />
 <br className="inline" data-ditto-id="style-i-2" />
 • Loon- en of pensioenaangifte;
 <br className="inline" data-ditto-id="style-link-11" />
 <br className="inline" data-ditto-id="style-i" />
 • Jaarwerk loonadministratie;
 <br className="inline" data-ditto-id="style-section-2" />
 <br className="inline" data-ditto-id="style-div-6" />
 • Opvoeren werknemer;
 <br className="inline" data-ditto-id="style-div-5" />
 <br className="inline" data-ditto-id="style-hr" />
 • Aanmelden werkgever;
 <br className="inline" data-ditto-id="style-section-6" />
 <br className="inline" data-ditto-id="style-div-34" />
 {"• Overige werkzaamheden. "}
 <br className="inline" data-ditto-id="style-div-4" />
 <br className="inline" data-ditto-id="style-div-21" />
 <br className="inline" data-ditto-id="style-link-12" />
 <br className="inline" data-ditto-id="style-irketim-logosu" />
 <br className="inline" data-ditto-id="style-div-12" />
 </p>
 {" "}
 <p className="block mb-4" data-ditto-id="style-ul">
 <br className="inline" data-ditto-id="style-li" />
 {" "}
 </p>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative bg-border" data-ditto-id="style-link-13">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-font-25">
 <div className="flex -mx-[0.9375rem] flex-wrap" data-ditto-id="style-font-16">
 <div className="w-142.5 block max-w-full px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] md:max-lg:w-180 2xl:w-165" data-ditto-id="style-li-3">
 <p className="block mb-4" data-ditto-id="style-font-22">
 <span className="inline font-bold">
 AFDELING JURIDISCHE ZAKEN
 </span>
 <br className="inline" data-ditto-id="style-li-8" />
 <i className="inline italic" data-ditto-id="style-link-14">
 {"Complete juridische ondersteuning voor ondernemer, organisatie & business"}
 <br className="inline" data-ditto-id="style-font-26" />
 {" "}
 <br className="inline" data-ditto-id="style-font" />
 </i>
 • Ondersteuning bij keuze rechtsvorm en inrichting structuur;
 <br className="inline" data-ditto-id="style-li-4" />
 <br className="inline" data-ditto-id="style-font-19" />
 {"• Herstructurering, reorganisatie & verandering; "}
 <br className="inline" data-ditto-id="style-font-43" />
 <br className="inline" data-ditto-id="style-li-11" />
 {"• Goed Bestuur en Compliance; "}
 <br className="inline" data-ditto-id="style-link-15" />
 <br className="inline" data-ditto-id="style-font-27" />
 {"• Corporate & Commercial Legal;"}
 <br className="inline" data-ditto-id="style-font-8" />
 <br className="inline" data-ditto-id="style-li-2" />
 • LegalTech, privacy en data protective;
 <br className="inline" data-ditto-id="style-font-33" />
 <br className="inline" data-ditto-id="style-font-2" />
 {"• Contracten, Algemene Voorwaarden en Aansprakelijkheidsrecht; "}
 <br className="inline" data-ditto-id="style-li-12" />
 <br className="inline" data-ditto-id="style-link-16" />
 • Aan- en verkoop van activiteiten en bedrijven;
 <br className="inline" data-ditto-id="style-font-28" />
 <br className="inline" data-ditto-id="style-font-34" />
 {"• Due diligence en integratie; "}
 <br className="inline" />
 <br className="inline" data-ditto-id="style-font-17" />
 {"• Privé, familie en eigendom; "}
 <br className="inline" data-ditto-id="style-font-11" />
 <br className="inline" data-ditto-id="style-li-13" />
 • Contract- en documentmanagement (De Kluis).
 <br className="inline" data-ditto-id="style-link-17" />
 <br className="inline" />
 {"De Afdeling Juridische Zaken is er speciaal voor opkomende, middelgrote en grote bedrijven zonder (interne) juridische bezetting, die regelmatig behoefte hebben aan bedrijfsjuridische expertise. Flexibel, on board of remote. "}
 <br className="inline" data-ditto-id="style-font-18" />
 <br className="inline" data-ditto-id="style-div-2" />
 Afdeling Juridische Zaken heeft een internationaal trackrecord weten op te bouwen bij cliënten in diverse industrietakken.
 <br className="inline" />
 <br className="inline" data-ditto-id="style-div-8" />
 Samen met cliënten bouwen wij aan stabiele en veelzijdige relaties en werken wij aan de ontwikkeling van solide transacties en een duurzame business propositie.
 </p>
 {" "}
 <p className="block mb-4" data-ditto-id="style-div-14">
 <br className="inline" data-ditto-id="style-span-11" />
 {" "}
 </p>
 {" "}
 </div>
 {" "}
 <div className="w-142.5 block max-w-full px-[0.9375rem] shrink-0 bg-border max-md:w-[23.4375rem] md:max-lg:w-180 2xl:w-165" data-ditto-id="style-p">
 <p className="block mb-4" data-ditto-id="style-link-18">
 <span className="inline font-bold" data-ditto-id="style-div-15">
 {"Business Consultancy & Interim"}
 </span>
 <br className="inline" />
 <i className="inline italic" data-ditto-id="style-link-40">
 In samenwerking met ketenpartners
 <br className="inline" data-ditto-id="style-image" />
 {" "}
 <br className="inline" data-ditto-id="style-link-19" />
 </i>
 • Werkkapitaal issues en cash flow analyse;
 <br className="inline" data-ditto-id="style-website-cookies-bar" />
 <br className="inline" data-ditto-id="style-div-26" />
 • Ondernemings- en businessplannen;
 <br className="inline" />
 <br className="inline" data-ditto-id="style-div-27" />
 • Analyse waardeketen en verdienmodel;
 <br className="inline" data-ditto-id="style-div-9" />
 <br className="inline" data-ditto-id="style-div-16" />
 {"• Business Development, positionering en bedrijfsstrategie; "}
 <br className="inline" />
 <br className="inline" data-ditto-id="style-link-21" />
 {"• Financiering en participaties; "}
 <br className="inline" data-ditto-id="style-font-21" />
 <br className="inline" data-ditto-id="style-font-36" />
 {"• Zakelijke correspondentie "}
 <br className="inline" />
 <br className="inline" data-ditto-id="style-font-20" />
 {"Voor familiebedrijven en het grotere MKB segment "}
 <br className="inline" />
 <br className="inline" data-ditto-id="style-li-6" />
 {"Aan het topmanagement worden steeds hogere eisen gesteld. Om hieraan en aan hogere verwachtingen te kunnen voldoen wordt aansluiting gezocht bij specifieke expertise en internationale ervaring. "}
 <br className="inline" data-ditto-id="style-link-22" />
 <br className="inline" data-ditto-id="style-font-23" />
 Die expertise en ervaring hebben wij in huis en stellen wij graag ter beschikking.
 <br className="inline" />
 <br className="inline" data-ditto-id="style-li-7" />
 {"Indien gewenst kan dat voor een vast aantal dagdelen per maand. "}
 <br className="inline" />
 <br className="inline" />
 <br className="inline" data-ditto-id="style-li-5" />
 <br className="inline" data-ditto-id="style-link-23" />
 <br className="inline" />
 <br className="inline" data-ditto-id="style-font-37" />
 <br className="inline" />
 </p>
 {" "}
 <p className="block mb-4" data-ditto-id="style-div-10">
 <br className="inline" />
 {" "}
 </p>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <QuoteCarousel />
 {" "}
 <section className="block relative pt-30 pb-60 bg-border" data-ditto-id="style-section-3">
 <div className="h-full block absolute top-0 inset-x-0 overflow-hidden [background-size:100%] [background-position:50%_100%] bg-no-repeat pointer-events-none max-md:hidden" style={{ backgroundImage: "url(\"/assets/cloned/svg/37dcd0b84539.svg\")" }} />
 {" "}
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-div-19">
 <h2 className="block mb-2 text-color-005 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[2.75rem] font-bold leading-[3.3125rem] text-center max-md:text-[1.8125rem] max-md:leading-[2.1875rem] md:max-lg:text-4xl md:max-lg:leading-[2.75rem]" data-component="heading">
 Wij zijn ervaren met programma's zoals:
 </h2>
 {" "}
 <p className="block mb-4 text-center">
 <br className="inline" data-ditto-id="style-br-19" />
 {" "}
 </p>
 {" "}
 <div className="flex -mx-[0.9375rem] flex-wrap justify-center max-md:[justify-content:initial]">
 {Logo_data.map((d, i) => <Logo key={i} d={d} styles={Logo_styles[i]} />)}
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </main>
 {" "}
 <footer className="block shrink-0 text-background bg-color-004" id="bottom">
 <div className="block" data-ditto-id="style-footer-2" id="footer">
 <section className="block relative pt-8 pb-4" data-ditto-id="style-section-4">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 ">
 <div className="flex -mx-[0.9375rem] flex-wrap items-end">
 <div className="w-[17.8125rem] h-[8.1rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[123.7px] md:max-lg:w-180 md:max-lg:h-[6.2rem] 2xl:w-82.5" data-ditto-id="style-div-20">
 <p className="block mb-2" data-ditto-id="style-p-5">
 <font className="inline">
 {" "}
 <font className="inline">
 Hoe kunnen we helpen
 </font>
 {" "}
 </font>
 {" "}
 <br className="inline" data-ditto-id="style-br-20" />
 {" "}
 </p>
 {" "}
 <h4 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-2xl font-bold leading-[1.8125rem] max-md:text-[1.375rem] max-md:leading-[1.625rem] md:max-lg:text-[1.4375rem] md:max-lg:leading-[1.6875rem]" data-ditto-id="style-heading-4" data-component="heading">
 <font className="inline">
 {" "}
 <font className="inline">
 {"U kunt altijd contact met ons opnemen "}
 </font>
 {" "}
 </font>
 {" "}
 </h4>
 {" "}
 </div>
 {" "}
 <div className="w-[17.8125rem] h-[8.15rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[128.9px] md:max-lg:w-180 md:max-lg:h-[8.1rem] 2xl:w-82.5" aria-describedby="tooltip8305">
 <p className="block mb-2">
 <font className="inline">
 {" "}
 <font className="inline" data-ditto-id="style-font-38">
 Bel ons
 </font>
 {" "}
 </font>
 {" "}
 </p>
 {" "}
 <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-component="heading">
 <span className="inline">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-link-26" data-component="link" href="tel:31 (0) 33 46 11 447">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline">
 {"+31 (0) 33 46 11 447 "}
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </span>
 {" "}
 </h5>
 {" "}
 <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-component="heading" aria-describedby="tooltip842231">
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-link-27" data-component="link" href="tel:31 (0) 33 46 11 447">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline">
 +31 (0) 6 11 23 88 30
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 <span className="inline">
 {" "}
 </span>
 {" "}
 </h5>
 {" "}
 </div>
 {" "}
 <div className="w-[17.8125rem] h-[6.075rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[6.025rem] md:max-lg:w-180 md:max-lg:h-[6.05rem] 2xl:w-82.5" aria-describedby="tooltip941693">
 <p className="block mb-2">
 <font className="inline">
 {" "}
 <font className="inline" data-ditto-id="style-font-39">
 Stuur ons een bericht
 </font>
 {" "}
 </font>
 {" "}
 <br className="inline" />
 {" "}
 </p>
 {" "}
 <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-component="heading">
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-link-28" data-component="link" href="mailto:info@ahneta.nl">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline">
 info@ahneta.nl
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </h5>
 {" "}
 </div>
 {" "}
 <div className="w-[17.8125rem] h-[97.3px] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] md:max-lg:w-180 2xl:w-82.5">
 <div className="block text-right">
 <p className="block mr-[0.4rem] mb-2 align-middle">
 <font className="inline align-middle" data-ditto-id="style-font-40">
 {" "}
 <font className="inline align-middle">
 Volg ons
 </font>
 {" "}
 </font>
 {" "}
 </p>
 {" "}
 <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-link-29" data-component="link" href="https://www.ahneta.nl/website/social/twitter">
 {" "}
 <i className="flex m-1 justify-center items-center [font-family:FontAwesome-twitter-x-only] leading-4 before:content-[''] before:block before:w-4 before:h-4 before:text-primary before:text-base before:leading-4 before:text-right">
 ​
 </i>
 {" "}
 </a>
 {" "}
 <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-link-30" data-component="link" href="https://www.ahneta.nl/website/social/linkedin">
 {" "}
 <i className="flex m-1 justify-center items-center [font-family:FontAwesome] leading-4 before:content-[''] before:block before:w-[13.7px] before:h-4 before:text-primary before:text-base before:leading-4 before:text-right" data-ditto-id="style-i-4" aria-describedby="tooltip290654">
 ​
 </i>
 {" "}
 </a>
 {" "}
 <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-link-31" data-component="link" href="https://www.ahneta.nl/website/social/instagram">
 {" "}
 <i className="flex m-1 justify-center items-center [font-family:FontAwesome] leading-4 before:content-[''] before:block before:w-[13.7px] before:h-4 before:text-primary before:text-base before:leading-4 before:text-right">
 ​
 </i>
 {" "}
 </a>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 ">
 <div className="block py-4 leading-0">
 <hr className="h-px border-t border-solid border-t-muted-foreground block overflow-hidden mx-auto w-[69.375rem] max-md:w-[21.5625rem] md:max-lg:w-[43.125rem] 2xl:w-[80.625rem]" />
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 ">
 <div className="flex -mx-[0.9375rem] flex-wrap items-center" aria-describedby="tooltip859185">
 <div className="w-47.5 h-[6.3125rem] min-h-6 block max-w-full pb-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-lg:h-34 md:max-lg:w-180 2xl:w-55 2xl:h-[116.9px]">
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-link-32" data-component="link" href="/">
 {" "}
 <img className="w-40 h-[5.3125rem] inline max-w-full overflow-clip align-middle max-lg:w-56.5 max-lg:h-30 2xl:w-47.5 2xl:h-[6.3125rem]" data-component="image" alt="" aria-label="Şirketim logosu" role="img" src="/assets/cloned/images/1461683c0d67.png" title="Benim şirketim" />
 {" "}
 </Link>
 {" "}
 </div>
 {" "}
 <div className="w-237.5 h-10 min-h-6 block max-w-full pb-4 px-[0.9375rem] shrink-0 text-right max-md:w-[23.4375rem] max-md:h-16 md:max-lg:w-180 2xl:w-275" data-ditto-id="style-div-23" aria-describedby="tooltip611099">
 <ul className="h-full block [list-style-type:none] list-outside" aria-describedby="tooltip612522">
 <li className="inline-block mr-2">
 {" "}
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-link-33" data-component="link" href="/">
 {" "}
 <font className="inline" data-ditto-id="style-font-29">
 {" "}
 <font className="inline">
 Home
 </font>
 {" "}
 </font>
 {" "}
 </Link>
 {" "}
 </li>
 <li className="inline-block mr-2">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block mr-2">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-link-34" data-component="link" href="#">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline">
 Over ons
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </li>
 <li className="inline-block mr-2">
 {" "}
 <font className="inline" data-ditto-id="style-font-30">
 {" "}
 <font className="inline">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block mr-2">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-link-35" data-component="link" href="#">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline" aria-describedby="tooltip841579">
 Product
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </li>
 <li className="inline-block mr-2">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline" data-ditto-id="style-font-31">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block mr-2">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-link-36" data-component="link" href="#">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline" data-ditto-id="style-font-32" aria-describedby="tooltip455312">
 Gebruiksvoorwaarden
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </li>
 <li className="inline-block mr-2">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block">
 {" "}
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-link-37" data-component="link" aria-describedby="tooltip848069" href="/privacy">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline">
 Privacybeleid
 </font>
 {" "}
 </font>
 {" "}
 </Link>
 {" "}
 </li>
 </ul>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 </div>
 {" "}
 <div className="block bg-color-005">
 <div className="block max-w-285 mx-auto py-4 px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 ">
 <div className="flex -mx-[0.9375rem] flex-wrap">
 <div className="w-full block max-w-full px-[0.9375rem] grow shrink-0 basis-[0%] text-color-003 text-left max-md:text-center max-md:grow-[initial] max-md:basis-[initial]">
 <span className="inline align-middle">
 Copyright © Ahneta Advies
 </span>
 {" "}
 <p className="block mb-4">
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-link-38" data-component="link" href="/cookie-policy">
 Cookiebeleid
 </Link>
 </p>
 </div>
 {" "}
 <div className="w-142.5 block max-w-full my-[1.3125rem] px-[0.9375rem] grow shrink-0 basis-[0%] text-right max-md:w-[23.4375rem] max-md:text-center max-md:my-0 max-md:grow-[initial] max-md:basis-[initial] md:max-lg:w-90 md:max-lg:my-[0.5625rem] 2xl:w-165" data-ditto-id="style-div-24">
 <div className="h-full block">
 {" "}
 <a className="text-color-003 cursor-pointer hover:underline" href="https://imora.nl" target="_blank" rel="noopener noreferrer">
 Maintained by Imora
 </a>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </footer>
 {" "}
 <div className="block shrink-0" id="website_cookies_bar">
 {" "}
 </div>
 {" "}
 <div className="block">
 <div className="block" data-ditto-id="style-div-25" />
 <div className="block" />
 <div className="w-78 h-0 block absolute top-[52.9px] left-240 z-1055 max-md:left-[3.4375rem] md:max-lg:left-112 2xl:left-400" />
 <div className="w-78 h-0 block absolute top-[52.9px] left-240 z-1055 max-md:left-[3.4375rem] md:max-lg:left-112 2xl:left-400" />
 </div>
 </>
 );
}
