import "./ditto.css";
import Tile from "./components/tile";
import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
import Logo from "./components/logo";
import Link from "next/link";
// Generated by clone-site. Do not edit by hand.
const Tile_data = [
 { text: "Lageprijsgarantie" },
 { text: "30 dagen online retourneren" },
 { text: "Standaard verzending" }
];
const ListRow_data = [
 { href: "/pricing", label: "Prijs" },
 { href: "/over-ons", label: "Over ons" },
 { href: "/contactus", label: "Contact" }
];
const ListRow2_data = [
 { text: "Verzorging van de complete bedrijfsboekhouding" },
 { text: " Controle van de door u ingevoerde boekhouding" },
 { text: "Opstellen van jaarrekeningen" },
 { text: "Verzorging van loonadministratie inclusief periodieke aangifte" },
 { text: "Verzorging van periodieke aangifte BTW" },
 { text: "Verzorging van aangifte VPB (Vennootschapsbelasting)" }
];
const ListRow2_data2 = [
 { text: "Advisering bij en de afhandeling van aangiftebiljetten recht van successie" },
 { text: "Advisering bij en afhandeling van aangiftebiljetten schenkingsrechten" },
 { text: "Advisering op gebied van Estate Planning (vermogensplanning)" },
 { text: "Advisering en afhandeling van de aangifte inkomstenbelasting" }
];
const Logo_data = [
 { imgSrc: "/assets/cloned/images/903d6bb6ee16.png" },
 { imgSrc: "/assets/cloned/images/b61f2bcc0fc1.png" },
 { imgSrc: "/assets/cloned/images/e11528624b63.png" }
];
const Logo_data2 = [
 { imgSrc: "/assets/cloned/images/1262e28d6378.png" },
 { imgSrc: "/assets/cloned/images/8927e11121f2.png" },
 { imgSrc: "/assets/cloned/images/d7f041b44e12.png" }
];
const Tile_meta: string[][] = [
 ["n10", "n11"],
 ["n12", "n13"],
 ["n14", "n15"]
];
const ListRow_meta: string[][] = [
 ["n48", "style-9", "style-15"],
 ["n51", "style-10", "style-16"],
 ["n54", "style-11", "style-17"]
];
const ListRow2_meta: string[][] = [
 ["style-span-10"],
 ["n92"],
 ["n93"],
 ["n94"],
 ["style-br-2"],
 ["style-br-9"]
];
const ListRow2_meta2: string[][] = [
 ["n106"],
 ["style-br-22"],
 ["style-br-13"],
 ["style-span-22"]
];
const Logo_meta: string[][] = [
 ["n312", "n313"],
 ["n314", "n315"],
 ["n316", "style-font-39"]
];
const Logo_meta2: string[][] = [
 ["n319", "style-link-28"],
 ["n321", "n322"],
 ["n323", "n324"]
];
const Tile_styles = [
 { className: "before:content-['']" },
 { className: "before:content-['']" },
 { className: "before:content-['']" }
];

export default function Page() {
 return (
 <>
 <main className="block grow shrink-0">
 <div className="h-full block" id="wrap">
 <div className="block">
 <section className="block relative py-6 overflow-hidden text-background bg-color-004">
 <span className="h-full block absolute top-0 inset-x-0 overflow-hidden bg-cover [background-position:50%_0px] bg-no-repeat [background-attachment:fixed] pointer-events-none max-lg:[background-attachment:initial]" style={{ backgroundImage: "url(\"/assets/cloned/images/2873c8e777c4.jpg\")" }} data-ditto-id="style-span-8" />
 {" "}
 <div className="h-full block absolute top-0 inset-x-0 overflow-hidden bg-color-004 bg-no-repeat pointer-events-none" data-ditto-id="style-div-28" />
 {" "}
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-div-33">
 <h1 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[3.875rem] font-bold leading-[4.625rem] max-md:text-4xl max-md:leading-[2.6875rem] md:max-lg:text-5xl md:max-lg:leading-[3.625rem]" data-ditto-id="style-heading-6" data-component="heading">
 Diensten
 </h1>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 </div>
 {" "}
 <div className="block" data-ditto-id="style-div-29">
 <section className="block relative py-10 bg-border" data-ditto-id="style-section-5">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-div-30">
 <h1 className="block mb-2 text-color-005 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[3.875rem] font-bold leading-[4.625rem] text-center max-md:text-4xl max-md:leading-[2.6875rem] md:max-lg:text-5xl md:max-lg:leading-[3.625rem]" data-ditto-id="style-p-2" data-component="heading">
 <font className="inline text-color-010 max-lg:text-[3.875rem] max-lg:leading-[4.625rem]" data-ditto-id="style-br-4">
 Ahneta Advies is gespecialiseerd in:
 </font>
 {" "}
 <br className="inline" data-ditto-id="style-span-20" />
 {" "}
 </h1>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative pb-18 bg-border" data-ditto-id="style-span-6">
 <div className="h-full block absolute top-0 inset-x-0 overflow-hidden [background-size:100%] [background-position:50%_50%] bg-no-repeat pointer-events-none max-md:hidden" style={{ backgroundImage: "url(\"/assets/cloned/svg/8a077abc9727.svg\")" }} data-ditto-id="style-br-5" />
 {" "}
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0">
 <div className="flex -mx-[0.9375rem] flex-wrap items-stretch">
 <div className="w-142.5 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] md:max-lg:w-180 2xl:w-165" data-ditto-id="style-span-5">
 <div className="flex relative rounded-md flex-col overflow-hidden [overflow-wrap:break-word] bg-background shadow-[var(--color-008)_0px_8px_16px_0px] h-[807.19px] max-md:h-[720.31px] md:max-lg:h-[950.97px] 2xl:h-[897.19px]" data-ditto-id="style-u">
 <Link className="block text-color-011 cursor-pointer" data-ditto-id="style-br-10" data-component="link" href="/bedrijven">
 {" "}
 <img className="w-135 h-135 inline rounded-tl-[5.4px] rounded-tr-[5.4px] overflow-clip align-middle max-md:w-[21.5625rem] max-md:h-[21.5625rem] md:max-lg:w-172.5 md:max-lg:h-172.5 2xl:w-157.5 2xl:h-157.5" data-ditto-id="style-br-3" data-component="image" alt="" aria-describedby="tooltip520268" src="/assets/cloned/images/32cb539d354b.jpg" />
 {" "}
 </Link>
 {" "}
 <div className="block p-4 rounded-br-[5.4px] rounded-bl-[5.4px] grow bg-surface-2" data-ditto-id="style-span-7">
 <h3 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-4xl font-bold leading-[2.6875rem] max-md:text-[1.625rem] max-md:leading-[1.9375rem] md:max-lg:text-[1.9375rem] md:max-lg:leading-[2.3125rem]" data-ditto-id="style-br-15" data-component="heading">
 Bedrijven
 </h3>
 {" "}
 <ul className="block mb-4 pl-8 [list-style-type:disc] list-outside" data-ditto-id="style-br-7">
 {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} />)}
 <li className="list-item" data-ditto-id="style-span-9">
 Advisering bij bedrijfsovernames
 <br className="inline" data-ditto-id="style-br-8" />
 </li>
 </ul>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 <div className="w-142.5 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] md:max-lg:w-180 2xl:w-165" data-ditto-id="style-br-18">
 <div className="flex relative rounded-md flex-col overflow-hidden [overflow-wrap:break-word] bg-background shadow-[var(--color-006)_0px_4px_16px_0px] h-[807.19px] max-md:h-[672.31px] md:max-lg:h-[902.97px] 2xl:h-[897.19px]" data-ditto-id="style-span-15">
 <Link className="block text-color-011 cursor-pointer" data-ditto-id="style-br-17" data-component="link" href="/particulieren">
 {" "}
 <img className="w-135 h-135 inline rounded-tl-[5.4px] rounded-tr-[5.4px] overflow-clip align-middle max-md:w-[21.5625rem] max-md:h-[21.5625rem] md:max-lg:w-172.5 md:max-lg:h-172.5 2xl:w-157.5 2xl:h-157.5" data-ditto-id="style-br-12" data-component="image" alt="" aria-describedby="tooltip988611" src="/assets/cloned/images/6ca993e9bf9e.jpg" />
 {" "}
 </Link>
 {" "}
 <div className="block p-4 rounded-br-[5.4px] rounded-bl-[5.4px] grow bg-surface-2" data-ditto-id="style-span-13">
 <h3 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-4xl font-bold leading-[2.6875rem] max-md:text-[1.625rem] max-md:leading-[1.9375rem] md:max-lg:text-[1.9375rem] md:max-lg:leading-[2.3125rem]" data-ditto-id="style-br" data-component="heading">
 Particulieren
 </h3>
 {" "}
 <ul className="block mb-4 pl-8 [list-style-type:disc] list-outside">
 {ListRow2_data2.map((d, i) => <ListRow2 key={i} d={d} />)}
 <li className="list-item" data-ditto-id="style-br-21">
 Advisering en afhandeling van bezwaar- en beroepschriften
 <br className="inline" />
 </li>
 </ul>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative pt-10 bg-border" data-ditto-id="style-span-12">
 <div className="h-full block absolute top-0 inset-x-0 overflow-hidden [background-size:100%] [background-position:50%_50%] bg-no-repeat pointer-events-none max-md:hidden" style={{ backgroundImage: "url(\"/assets/cloned/svg/8a077abc9727.svg\")" }} data-ditto-id="style-u-2" />
 {" "}
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0">
 <div className="flex -mx-[0.9375rem] flex-wrap" data-ditto-id="style-br-14">
 <div className="w-142.5 block max-w-full pb-2 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] md:max-lg:w-180 2xl:w-165">
 <p className="block mb-4" data-ditto-id="style-br-16">
 {" Al vanaf de start van de onderneming heeft Ahneta zich dienstverlenend voor het MKB geprofileerd. Het pakket aan diensten voor het MKB is in de loop der jaren steeds verder uitgebreid. "}
 </p>
 {" "}
 <p className="block mb-4" data-ditto-id="style-br-6" aria-describedby="tooltip204831">
 Door de wijziging van wetgeving verzorgt Ahneta ook voor besloten vennootschappen (B.V.) het complete traject vanaf controle boekhouding tot opstelling van de jaarrekening en de aangifte VPB.
 <br className="inline" />
 <br className="inline" data-ditto-id="style-bottom" />
 {" Uiteraard kunnen ook de eenmanszaak (ZZP’er) of de vennootschap onder firma"}
 <font className="inline" data-ditto-id="style-footer">
 {" ("}
 </font>
 <a className="inline text-color-011 cursor-pointer" data-ditto-id="style-section" data-component="link" href="https://v.o.f.)/">
 <font className="inline text-foreground" data-ditto-id="style-div-31">
 V.O.F.)
 </font>
 </a>
 <font className="inline" data-ditto-id="style-div-7">
 {" d"}
 </font>
 oor Ahneta worden begeleid.
 <br className="inline" data-ditto-id="style-div-32" />
 <br className="inline" data-ditto-id="style-p-3" />
 Alvorens Ahneta voor uw bedrijf werkzaamheden kan verrichten wordt er eerst met u een prijsafspraak gemaakt. In de prijsafspraak wordt helder weergegeven welke werkzaamheden Ahneta voor u zal gaan verrichten en wat de uitvoering van deze werkzaamheden u gaat kosten.
 <br className="inline" data-ditto-id="style-font-12" />
 <br className="inline" data-ditto-id="style-font-9" />
 Indien Ahneta voor u de complete boekhouding verzorgt wordt duidelijk aangegeven op hoeveel boekingen de prijsopgave is gebaseerd. Hierop is een met u overeengekomen marge van meer of minder boekingen van toepassing. Worden er minder boekingen verricht ontvangt u een restitutie van honorarium en indien er meer boeking verricht moeten worden wordt de meerprijs aan u extra gedeclareerd. De declaratie wordt u per maand of per kwartaal toegezonden.
 <br className="inline" data-ditto-id="style-br-23" />
 </p>
 {" "}
 </div>
 {" "}
 <div className="w-142.5 block max-w-full px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] md:max-lg:w-180 2xl:w-165" data-ditto-id="style-heading-5">
 <p className="block mb-4" data-ditto-id="style-font-13">
 Ahneta is geen groot bedrijf en hiervoor is bewust gekozen. Hierdoor hebben wij voldoende tijd voor u en kunnen wij u beter van dienst zijn met een persoonlijk advies.
 <br className="inline" data-ditto-id="style-font-3" />
 <br className="inline" data-ditto-id="style-div" />
 Door deze keuze hebben wij ook lage overheadkosten waardoor wij de tarieven van onze dienstverlening aantrekkelijk kunnen houden.
 <br className="inline" data-ditto-id="style-p-4" />
 </p>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative" data-ditto-id="style-font-41">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0">
 <div className="flex -mx-[0.9375rem] flex-wrap" data-ditto-id="style-heading-3">
 <div className="w-95 block max-w-full px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] md:max-lg:w-180 2xl:w-110" data-ditto-id="style-span-17">
 <p className="block mb-4" data-ditto-id="style-link-6">
 <span className="inline font-bold" data-ditto-id="style-font-4">
 FINANCIËLE ADMINISTRATIE EN ADVIES
 </span>
 <br className="inline" data-ditto-id="style-font-14" />
 <i className="inline italic" data-ditto-id="style-heading">
 Administratieve werkzaamheden
 <br className="inline" data-ditto-id="style-link-7" />
 </i>
 <br className="inline" data-ditto-id="style-font-5" />
 • Verwerken beoordelen administratie;
 <br className="inline" data-ditto-id="style-font-42" />
 <br className="inline" data-ditto-id="style-span-16" />
 • Jaarrekening enkelvoudig;
 <br className="inline" data-ditto-id="style-div-13" />
 <br className="inline" />
 • Jaarrekening geconsolideerd;
 <br className="inline" data-ditto-id="style-font-15" />
 <br className="inline" data-ditto-id="style-font-10" />
 • Deponeren stukken bij KvK / opstellen notulen;
 <br className="inline" data-ditto-id="style-br-11" />
 <br className="inline" data-ditto-id="style-heading-2" />
 • Overige werkzaamheden: advisering en aanvullende diensten;
 <br className="inline" data-ditto-id="style-link-8" />
 <br className="inline" data-ditto-id="style-font-6" />
 • Overleg / communicatie; bij vaste prijsafspraak 2 uur inbegrepen.
 <br className="inline" data-ditto-id="style-font-24" />
 <br className="inline" data-ditto-id="style-div-22" />
 <br className="inline" data-ditto-id="style-div-11" />
 </p>
 {" "}
 <p className="block mb-4" data-ditto-id="style-p-7">
 <br className="inline" data-ditto-id="style-font-7" />
 {" "}
 </p>
 {" "}
 </div>
 {" "}
 <div className="w-95 block max-w-full px-[0.9375rem] shrink-0 bg-border max-md:w-[23.4375rem] md:max-lg:w-180 2xl:w-110" data-ditto-id="style-font-35">
 <p className="block mb-4" data-ditto-id="style-link-9">
 <span className="inline font-bold" data-ditto-id="style-i-3">
 BELASTINGADVIES
 </span>
 <br className="inline" data-ditto-id="style-link-10" />
 <i className="inline italic" data-ditto-id="style-i-2">
 Fiscale werkzaamheden
 <br className="inline" data-ditto-id="style-link-11" />
 <br className="inline" data-ditto-id="style-i" />
 </i>
 • Aangifte inkomstenbelasting DGA;
 <br className="inline" data-ditto-id="style-section-2" />
 <br className="inline" data-ditto-id="style-div-6" />
 • Aangifte inkomstenbelasting ondernemer (een onderneming);
 <br className="inline" data-ditto-id="style-div-5" />
 <br className="inline" data-ditto-id="style-hr" />
 • Aangifte inkomstenbelasting partner (niet zijnde de ondernemer);
 <br className="inline" data-ditto-id="style-section-6" />
 <br className="inline" data-ditto-id="style-div-34" />
 • Aangifte vennootschapsbelasting (enkelvoudige BV);
 <br className="inline" data-ditto-id="style-div-4" />
 <br className="inline" data-ditto-id="style-div-21" />
 • Aangifte vennootschapsbelasting (fiscale eenheid 2 BV’s);
 <br className="inline" data-ditto-id="style-link-12" />
 <br className="inline" data-ditto-id="style-irketim-logosu" />
 • Aangifte omzetbelasting;
 <br className="inline" data-ditto-id="style-div-12" />
 <br className="inline" data-ditto-id="style-ul" />
 • Overige aangifte(n) en werkzaamheden (advisering, begeleiding, bezwaarprocedures).
 <br className="inline" data-ditto-id="style-li" />
 <br className="inline" data-ditto-id="style-link-13" />
 <br className="inline" data-ditto-id="style-font-25" />
 <br className="inline" data-ditto-id="style-font-16" />
 <br className="inline" data-ditto-id="style-li-3" />
 </p>
 {" "}
 <p className="block mb-4" data-ditto-id="style-font-22">
 <br className="inline" />
 {" "}
 </p>
 {" "}
 </div>
 {" "}
 <div className="w-95 block max-w-full px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] md:max-lg:w-180 2xl:w-110" data-ditto-id="style-li-8">
 <p className="block mb-4" data-ditto-id="style-link-14">
 <span className="inline font-bold" data-ditto-id="style-font-26">
 SALARISADMINISTRATIE
 </span>
 <br className="inline" data-ditto-id="style-font" />
 <i className="inline italic" data-ditto-id="style-li-4">
 Loon administratieve werkzaamheden
 <br className="inline" data-ditto-id="style-font-19" />
 <br className="inline" data-ditto-id="style-font-43" />
 </i>
 • Opzetten en inrichten loonadministratie;
 <br className="inline" data-ditto-id="style-li-11" />
 <br className="inline" data-ditto-id="style-link-15" />
 • Verwerken loonadministratie;
 <br className="inline" data-ditto-id="style-font-27" />
 <br className="inline" data-ditto-id="style-font-8" />
 • Loon- en of pensioenaangifte;
 <br className="inline" data-ditto-id="style-li-2" />
 <br className="inline" data-ditto-id="style-font-33" />
 • Jaarwerk loonadministratie;
 <br className="inline" data-ditto-id="style-font-2" />
 <br className="inline" data-ditto-id="style-li-12" />
 • Opvoeren werknemer;
 <br className="inline" data-ditto-id="style-link-16" />
 <br className="inline" data-ditto-id="style-font-28" />
 • Aanmelden werkgever;
 <br className="inline" data-ditto-id="style-font-34" />
 <br className="inline" />
 {"• Overige werkzaamheden. "}
 <br className="inline" data-ditto-id="style-font-17" />
 <br className="inline" data-ditto-id="style-font-11" />
 <br className="inline" data-ditto-id="style-li-13" />
 <br className="inline" data-ditto-id="style-link-17" />
 <br className="inline" />
 </p>
 {" "}
 <p className="block mb-4" data-ditto-id="style-font-18">
 <br className="inline" data-ditto-id="style-div-2" />
 {" "}
 </p>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative bg-border">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-div-8">
 <div className="flex -mx-[0.9375rem] flex-wrap" data-ditto-id="style-div-14">
 <div className="w-142.5 block max-w-full px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] md:max-lg:w-180 2xl:w-165" data-ditto-id="style-span-11">
 <p className="block mb-4" data-ditto-id="style-p">
 <span className="inline font-bold" data-ditto-id="style-link-18">
 AFDELING JURIDISCHE ZAKEN
 </span>
 <br className="inline" data-ditto-id="style-div-15" />
 <i className="inline italic">
 {"Complete juridische ondersteuning voor ondernemer, organisatie & business"}
 <br className="inline" data-ditto-id="style-link-40" />
 {" "}
 <br className="inline" data-ditto-id="style-image" />
 </i>
 • Ondersteuning bij keuze rechtsvorm en inrichting structuur;
 <br className="inline" data-ditto-id="style-link-19" />
 <br className="inline" data-ditto-id="style-website-cookies-bar" />
 {"• Herstructurering, reorganisatie & verandering; "}
 <br className="inline" data-ditto-id="style-div-26" />
 <br className="inline" />
 {"• Goed Bestuur en Compliance; "}
 <br className="inline" data-ditto-id="style-div-27" />
 <br className="inline" data-ditto-id="style-div-9" />
 {"• Corporate & Commercial Legal;"}
 <br className="inline" data-ditto-id="style-div-16" />
 <br className="inline" />
 • LegalTech, privacy en data protective;
 <br className="inline" data-ditto-id="style-link-21" />
 <br className="inline" data-ditto-id="style-font-21" />
 {"• Contracten, Algemene Voorwaarden en Aansprakelijkheidsrecht; "}
 <br className="inline" data-ditto-id="style-font-36" />
 <br className="inline" />
 • Aan- en verkoop van activiteiten en bedrijven;
 <br className="inline" data-ditto-id="style-font-20" />
 <br className="inline" />
 {"• Due diligence en integratie; "}
 <br className="inline" data-ditto-id="style-li-6" />
 <br className="inline" data-ditto-id="style-link-22" />
 {"• Privé, familie en eigendom; "}
 <br className="inline" data-ditto-id="style-font-23" />
 <br className="inline" />
 • Contract- en documentmanagement (De Kluis).
 <br className="inline" data-ditto-id="style-li-7" />
 <br className="inline" />
 {"De Afdeling Juridische Zaken is er speciaal voor opkomende, middelgrote en grote bedrijven zonder (interne) juridische bezetting, die regelmatig behoefte hebben aan bedrijfsjuridische expertise. Flexibel, on board of remote. "}
 <br className="inline" />
 <br className="inline" data-ditto-id="style-li-5" />
 Afdeling Juridische Zaken heeft een internationaal trackrecord weten op te bouwen bij cliënten in diverse industrietakken.
 <br className="inline" data-ditto-id="style-link-23" />
 <br className="inline" />
 Samen met cliënten bouwen wij aan stabiele en veelzijdige relaties en werken wij aan de ontwikkeling van solide transacties en een duurzame business propositie.
 </p>
 {" "}
 <p className="block mb-4" data-ditto-id="style-font-37">
 <br className="inline" />
 {" "}
 </p>
 {" "}
 </div>
 {" "}
 <div className="w-142.5 block max-w-full px-[0.9375rem] shrink-0 bg-border max-md:w-[23.4375rem] md:max-lg:w-180 2xl:w-165" data-ditto-id="style-div-10">
 <p className="block mb-4">
 <span className="inline font-bold">
 {"Business Consultancy & Interim"}
 </span>
 <br className="inline" data-ditto-id="style-span-18" />
 <i className="inline italic" data-ditto-id="style-p-6">
 In samenwerking met ketenpartners
 <br className="inline" data-ditto-id="style-link-24" />
 {" "}
 <br className="inline" data-ditto-id="style-div-3" />
 </i>
 • Werkkapitaal issues en cash flow analyse;
 <br className="inline" data-ditto-id="style-div-17" />
 <br className="inline" />
 • Ondernemings- en businessplannen;
 <br className="inline" />
 <br className="inline" data-ditto-id="style-link-25" />
 • Analyse waardeketen en verdienmodel;
 <br className="inline" />
 <br className="inline" />
 {"• Business Development, positionering en bedrijfsstrategie; "}
 <br className="inline" />
 <br className="inline" data-ditto-id="style-div-18" />
 {"• Financiering en participaties; "}
 <br className="inline" />
 <br className="inline" />
 {"• Zakelijke correspondentie "}
 <br className="inline" data-ditto-id="style-avatar" />
 <br className="inline" />
 {"Voor familiebedrijven en het grotere MKB segment "}
 <br className="inline" />
 <br className="inline" />
 {"Aan het topmanagement worden steeds hogere eisen gesteld. Om hieraan en aan hogere verwachtingen te kunnen voldoen wordt aansluiting gezocht bij specifieke expertise en internationale ervaring. "}
 <br className="inline" data-ditto-id="style-span-14" />
 <br className="inline" data-ditto-id="style-span-21" />
 Die expertise en ervaring hebben wij in huis en stellen wij graag ter beschikking.
 <br className="inline" />
 <br className="inline" data-ditto-id="style-span-19" />
 {"Indien gewenst kan dat voor een vast aantal dagdelen per maand. "}
 <br className="inline" />
 <br className="inline" data-ditto-id="style-section-3" />
 <br className="inline" />
 <br className="inline" data-ditto-id="style-div-19" />
 <br className="inline" />
 <br className="inline" />
 <br className="inline" data-ditto-id="style-br-19" />
 </p>
 {" "}
 <p className="block mb-4">
 <br className="inline" />
 {" "}
 </p>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative">
 <div className="block relative bg-border" data-ditto-id="style-myquotecarousel617108" id="myQuoteCarousel617108">
 <ol className="h-[1.1rem] flex absolute bottom-0 inset-x-0 z-2 mb-4 mx-48 justify-center [list-style-type:none] list-outside max-md:mx-[56.3px] md:max-lg:mx-[7.2rem] ">
 <li className="box-content w-7.5 h-[0.6rem] list-item opacity-50 mb-2 mx-[0.1875rem] rounded-[4.8px] indent-[-999px] bg-background [background-clip:padding-box] shadow-[var(--color-006)_0px_1px_3px_0px] [-webkit-background-clip:padding-box] cursor-pointer" data-ditto-id="style-li-9" />
 <li className="box-content w-7.5 h-[0.6rem] list-item opacity-50 mb-2 mx-[0.1875rem] rounded-[4.8px] indent-[-999px] bg-background [background-clip:padding-box] shadow-[var(--color-006)_0px_1px_3px_0px] [-webkit-background-clip:padding-box] cursor-pointer" data-ditto-id="style-li-10" />
 <li className="box-content w-7.5 h-[0.6rem] list-item mb-2 mx-[0.1875rem] rounded-[4.8px] indent-[-999px] bg-background [background-clip:padding-box] shadow-[var(--color-006)_0px_1px_3px_0px] [-webkit-background-clip:padding-box] cursor-pointer" />
 </ol>
 {" "}
 <div className="block relative isolate overflow-hidden after:content-[''] after:block after:w-full after:h-0" data-ditto-id="style-footer-2">
 <div className="w-full h-88.5 min-h-88.5 block relative float-left -mr-320 py-20 bg-cover [background-position:50%_50%] bg-no-repeat max-lg:h-[440.3px] max-lg:min-h-[440.3px] max-md:-mr-[23.4375rem] md:max-lg:-mr-192 2xl:-mr-480" style={{ backgroundImage: "url(\"/assets/cloned/images/647d672ef452.jpg\")" }} data-ditto-id="style-section-4">
 <div className="h-full block absolute top-0 inset-x-0 overflow-hidden text-background bg-color-004 bg-no-repeat pointer-events-none" />
 {" "}
 <div className="h-full block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0">
 <blockquote className="h-full block mx-auto text-xl italic leading-7.5 w-[34.6875rem] max-lg:w-[21.5625rem] 2xl:w-[40.3125rem]" data-ditto-id="style-div-20">
 <i className="w-12 h-12 block float-left rounded-tl-md rounded-bl-md align-middle text-background [font-family:FontAwesome] text-base not-italic leading-12 text-center bg-accent before:content-[''] before:text-background before:text-base before:leading-12 before:text-center" data-ditto-id="style-p-5" />
 {" "}
 <div className="h-full block p-6 overflow-hidden bg-background">
 <p className="block mb-4">
 Schrijf hier een citaat van één van je klanten. Citaten zijn een geweldige manier om het vertrouwen in je producten of diensten te vergroten.
 </p>
 {" "}
 <footer className="block text-muted-foreground text-lg leading-[1.625rem] before:content-['']" data-ditto-id="style-br-20">
 <img className="w-10 h-10 inline max-h-10 mr-2 rounded-[50%] overflow-clip align-middle" data-ditto-id="style-heading-4" data-component="avatar" alt="" src="/assets/cloned/images/e964d90c8602.jpg" />
 {" "}
 <span className="inline opacity-75">
 <b className="inline font-bold">
 Jane DOE
 </b>
 {" • CEO of MyCompany"}
 </span>
 {" "}
 </footer>
 {" "}
 </div>
 {" "}
 </blockquote>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 <div className="h-full flex absolute top-0 right-[73.6rem] left-0 z-1 justify-start items-center text-background text-center cursor-pointer max-md:hidden md:max-lg:right-[44.1625rem] 2xl:right-[110.4rem]" aria-label="Vorige" role="img" title="Vorige">
 <span className="w-[46.9px] h-12 block text-foreground [background-size:100%_100%] [background-position:50%_50%] bg-no-repeat md:max-lg:w-11 md:max-lg:h-[2.6375rem] before:content-[''] before:inline-block before:w-[22.9px] before:h-12 before:ml-6 before:text-background before:text-[2rem] before:leading-12 before:text-center before:[font-family:FontAwesome] max-md:before:text-[1.5625rem] max-md:before:leading-[2.3125rem] max-md:before:w-auto max-md:before:h-auto md:max-lg:before:w-5 md:max-lg:before:h-[2.6375rem] md:max-lg:before:text-[1.75rem] md:max-lg:before:leading-[2.625rem]" />
 {" "}
 <span className="w-px h-px block absolute top-[177.5px] left-0 min-w-0 -m-px overflow-hidden whitespace-nowrap text-nowrap">
 Vorige
 </span>
 {" "}
 </div>
 {" "}
 <div className="h-full flex absolute top-0 right-0 left-[73.6rem] z-1 justify-end items-center text-background text-center cursor-pointer max-md:hidden md:max-lg:left-[44.1625rem] 2xl:left-[110.4rem]" data-ditto-id="style-font-38" aria-label="Volgende" role="img" title="Volgende">
 <span className="w-[46.9px] h-12 block text-foreground [background-size:100%_100%] [background-position:50%_50%] bg-no-repeat md:max-lg:w-11 md:max-lg:h-[2.6375rem] before:content-[''] before:inline-block before:w-[22.9px] before:h-12 before:mr-6 before:text-background before:text-[2rem] before:leading-12 before:text-center before:[font-family:FontAwesome] max-md:before:text-[1.5625rem] max-md:before:leading-[2.3125rem] max-md:before:w-auto max-md:before:h-auto md:max-lg:before:w-5 md:max-lg:before:h-[2.6375rem] md:max-lg:before:text-[1.75rem] md:max-lg:before:leading-[2.625rem]" />
 {" "}
 <span className="w-px h-px block absolute left-[3.2rem] min-w-0 -m-px overflow-hidden whitespace-nowrap text-nowrap md:max-lg:left-[30.7px] 2xl:left-[4.8rem]">
 Volgende
 </span>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative pt-30 pb-60 bg-border" data-ditto-id="style-link-26">
 <div className="h-full block absolute top-0 inset-x-0 overflow-hidden [background-size:100%] [background-position:50%_100%] bg-no-repeat pointer-events-none max-md:hidden" style={{ backgroundImage: "url(\"/assets/cloned/svg/37dcd0b84539.svg\")" }} />
 {" "}
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0">
 <h2 className="block mb-2 text-color-005 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[2.75rem] font-bold leading-[3.3125rem] text-center max-md:text-[1.8125rem] max-md:leading-[2.1875rem] md:max-lg:text-4xl md:max-lg:leading-[2.75rem]" data-component="heading">
 Onze referenties
 </h2>
 {" "}
 <p className="block mb-4 text-center" data-ditto-id="style-link-27">
 We zijn in goed gezelschap.
 </p>
 {" "}
 <div className="flex -mx-[0.9375rem] flex-wrap justify-center max-md:[justify-content:initial]">
 {Logo_data.map((d, i) => <Logo key={i} d={d} />)}
 {" "}
 </div>
 {" "}
 <div className="flex -mx-[0.9375rem] flex-wrap justify-center max-md:[justify-content:initial]">
 {Logo_data2.map((d, i) => <Logo key={i} d={d} />)}
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </main>
 {" "}
 <footer className="block shrink-0 text-background bg-color-004" id="bottom">
 <div className="block" data-ditto-id="style-font-40" id="footer">
 <section className="block relative pt-8 pb-4">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 " data-ditto-id="style-link-29">
 <div className="flex -mx-[0.9375rem] flex-wrap items-end">
 <div className="w-[17.8125rem] h-[8.1rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[123.7px] md:max-lg:w-180 md:max-lg:h-[6.2rem] 2xl:w-82.5" data-ditto-id="style-link-30">
 <p className="block mb-2" data-ditto-id="style-i-4">
 <font className="inline" data-ditto-id="style-link-31">
 {" "}
 <font className="inline">
 Hoe kunnen we helpen
 </font>
 {" "}
 </font>
 {" "}
 <br className="inline" />
 {" "}
 </p>
 {" "}
 <h4 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-2xl font-bold leading-[1.8125rem] max-md:text-[1.375rem] max-md:leading-[1.625rem] md:max-lg:text-[1.4375rem] md:max-lg:leading-[1.6875rem]" data-component="heading">
 <font className="inline">
 {" "}
 <font className="inline">
 {"U kunt altijd contact met ons opnemen "}
 </font>
 {" "}
 </font>
 {" "}
 </h4>
 {" "}
 </div>
 {" "}
 <div className="w-[17.8125rem] h-[8.15rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[128.9px] md:max-lg:w-180 md:max-lg:h-[8.1rem] 2xl:w-82.5" aria-describedby="tooltip8305">
 <p className="block mb-2">
 <font className="inline">
 {" "}
 <font className="inline">
 Bel ons
 </font>
 {" "}
 </font>
 {" "}
 </p>
 {" "}
 <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-ditto-id="style-link-32" data-component="heading">
 <span className="inline">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-div-23" data-component="link" href="tel:31 (0) 33 46 11 447">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline">
 {"+31 (0) 33 46 11 447 "}
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </span>
 {" "}
 </h5>
 {" "}
 <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-ditto-id="style-link-33" data-component="heading" aria-describedby="tooltip842231">
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-font-29" data-component="link" href="tel:31 (0) 33 46 11 447">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline">
 +31 (0) 6 11 23 88 30
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 <span className="inline">
 {" "}
 </span>
 {" "}
 </h5>
 {" "}
 </div>
 {" "}
 <div className="w-[17.8125rem] h-[6.075rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[6.025rem] md:max-lg:w-180 md:max-lg:h-[6.05rem] 2xl:w-82.5" aria-describedby="tooltip941693">
 <p className="block mb-2">
 <font className="inline" data-ditto-id="style-link-34">
 {" "}
 <font className="inline">
 Stuur ons een bericht
 </font>
 {" "}
 </font>
 {" "}
 <br className="inline" />
 {" "}
 </p>
 {" "}
 <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-component="heading">
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-font-30" data-component="link" href="mailto:info@ahneta.nl">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline">
 info@ahneta.nl
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </h5>
 {" "}
 </div>
 {" "}
 <div className="w-[17.8125rem] h-[97.3px] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] md:max-lg:w-180 2xl:w-82.5" data-ditto-id="style-link-35">
 <div className="block text-right">
 <p className="block mr-[0.4rem] mb-2 align-middle">
 <font className="inline align-middle">
 {" "}
 <font className="inline align-middle">
 Volg ons
 </font>
 {" "}
 </font>
 {" "}
 </p>
 {" "}
 <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-font-31" data-component="link" href="https://www.ahneta.nl/website/social/twitter">
 {" "}
 <i className="flex m-1 justify-center items-center [font-family:FontAwesome-twitter-x-only] leading-4 before:content-[''] before:block before:w-4 before:h-4 before:text-primary before:text-base before:leading-4 before:text-right">
 ​
 </i>
 {" "}
 </a>
 {" "}
 <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-link-36" data-component="link" href="https://www.ahneta.nl/website/social/linkedin">
 {" "}
 <i className="flex m-1 justify-center items-center [font-family:FontAwesome] leading-4 before:content-[''] before:block before:w-[13.7px] before:h-4 before:text-primary before:text-base before:leading-4 before:text-right" aria-describedby="tooltip290654">
 ​
 </i>
 {" "}
 </a>
 {" "}
 <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-font-32" data-component="link" href="https://www.ahneta.nl/website/social/instagram">
 {" "}
 <i className="flex m-1 justify-center items-center [font-family:FontAwesome] leading-4 before:content-[''] before:block before:w-[13.7px] before:h-4 before:text-primary before:text-base before:leading-4 before:text-right">
 ​
 </i>
 {" "}
 </a>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 ">
 <div className="block py-4 leading-0">
 <hr className="h-px border-t border-solid border-t-muted-foreground block overflow-hidden mx-auto w-[69.375rem] max-md:w-[21.5625rem] md:max-lg:w-[43.125rem] 2xl:w-[80.625rem]" data-ditto-id="style-link-37" />
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 ">
 <div className="flex -mx-[0.9375rem] flex-wrap items-center" aria-describedby="tooltip859185">
 <div className="w-47.5 h-10 min-h-6 block max-w-full pb-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] md:max-lg:w-180 2xl:w-55">
 <Link className="inline text-primary cursor-pointer" data-component="link" href="/">
 {" "}
 <img className="w-0 h-px min-h-px inline max-w-full overflow-clip align-middle" data-component="image" alt="" aria-label="Şirketim logosu" role="img" src="/assets/cloned/images/1461683c0d67.png" title="Benim şirketim" />
 {" "}
 </Link>
 {" "}
 </div>
 {" "}
 <div className="w-237.5 h-10 min-h-6 block max-w-full pb-4 px-[0.9375rem] shrink-0 text-right max-md:w-[23.4375rem] max-md:h-16 md:max-lg:w-180 2xl:w-275" aria-describedby="tooltip611099">
 <ul className="h-full block [list-style-type:none] list-outside" aria-describedby="tooltip612522">
 <li className="inline-block mr-2" data-ditto-id="style-link-38">
 {" "}
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-div-24" data-component="link" href="/">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline">
 Home
 </font>
 {" "}
 </font>
 {" "}
 </Link>
 {" "}
 </li>
 <li className="inline-block mr-2">
 {" "}
 <font className="inline" data-ditto-id="style-link-39">
 {" "}
 <font className="inline">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block mr-2">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-div-25" data-component="link" href="#">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline">
 Over ons
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </li>
 <li className="inline-block mr-2">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block mr-2">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-link-41" data-component="link" href="#">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline" aria-describedby="tooltip841579">
 Product
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </li>
 <li className="inline-block mr-2">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block mr-2">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-link-42" data-component="link" href="#">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline" aria-describedby="tooltip455312">
 Gebruiksvoorwaarden
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </li>
 <li className="inline-block mr-2">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block">
 {" "}
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-link-43" data-component="link" aria-describedby="tooltip848069" href="/privacy">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline">
 Privacybeleid
 </font>
 {" "}
 </font>
 {" "}
 </Link>
 {" "}
 </li>
 </ul>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 </div>
 {" "}
 <div className="block bg-color-005">
 <div className="block max-w-285 mx-auto py-4 px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 ">
 <div className="flex -mx-[0.9375rem] flex-wrap">
 <div className="w-full block max-w-full px-[0.9375rem] grow shrink-0 basis-[0%] text-color-003 text-left max-md:text-center max-md:grow-[initial] max-md:basis-[initial]">
 <span className="inline align-middle">
 Copyright © Ahneta Advies
 </span>
 {" "}
 <p className="block mb-4">
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-link-44" data-component="link" href="/cookie-policy">
 Cookiebeleid
 </Link>
 </p>
 </div>
 {" "}
 <div className="w-142.5 block max-w-full my-[1.3125rem] px-[0.9375rem] grow shrink-0 basis-[0%] text-right max-md:w-[23.4375rem] max-md:text-center max-md:my-0 max-md:grow-[initial] max-md:basis-[initial] md:max-lg:w-90 md:max-lg:my-[0.5625rem] 2xl:w-165">
 <div className="h-full block">
 {" "}
 <a className="text-color-003 cursor-pointer hover:underline" href="https://imora.nl" target="_blank" rel="noopener noreferrer">
 Maintained by Imora
 </a>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </footer>
 {" "}
 <div className="block shrink-0" id="website_cookies_bar">
 {" "}
 </div>
 {" "}
 {" "}
 <div className="block">
 <div className="block" />
 <div className="block" />
 <div className="w-78 h-0 block absolute top-[52.9px] left-240 z-1055 max-md:left-[3.4375rem] md:max-lg:left-112 2xl:left-400" />
 <div className="w-78 h-0 block absolute top-[52.9px] left-240 z-1055 max-md:left-[3.4375rem] md:max-lg:left-112 2xl:left-400" />
 </div>
 </>
 );
}
