import "./ditto.css";
import Tile from "./components/tile";
import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
import ListRow3 from "./components/list-row3";
import ListRow4 from "./components/list-row4";
import Link from "next/link";
// Generated by clone-site. Do not edit by hand.
const Tile_data = [
 { text: "Lageprijsgarantie" },
 { text: "30 dagen online retourneren" },
 { text: "Standaard verzending" }
];
const ListRow_data = [
 { href: "/pricing", label: "Prijs" },
 { href: "/over-ons", label: "Over ons" },
 { href: "/contactus", label: "Contact" }
];
const ListRow2_data = [
 { text: "Standaard verkoop en marketing voor maximaal 2 gebruikers" },
 { text: "Boekhouding en verkoopadministratie" },
 { text: "Geen maatwerk" },
 { text: "Geen steun" }
];
const ListRow3_data = [
 { text: "\n  Complete CRM voor elke teamgrootte" },
 { text: "\n  Toegang tot alle modulen" },
 { text: "\n  Beperkt maatwerk" },
 { text: "\n  E-mail ondersteuning" }
];
const ListRow4_data = [
 { text: "\n  Onbeperkte CRM-kracht en ondersteuning" },
 { text: "\n  Toegang tot alle modules en opties" },
 { text: "\n  Onbeperkte wijzigingen" },
 { text: "\n  7x24 gratis ondersteuning" }
];
const Tile_meta: string[][] = [
 ["n10", "n11"],
 ["n12", "n13"],
 ["n14", "n15"]
];
const ListRow_meta: string[][] = [
 ["n48", "style-9", "style-15"],
 ["n51", "style-10", "style-16"],
 ["n54", "style-11", "style-17"]
];
const ListRow2_meta: string[][] = [
 ["style-br-12", "style-span-13", "style-br", "n105"],
 ["n106", "style-br-22", "style-br-13", "style-span-22"],
 ["style-br-21", "n111", "style-span-12", "style-u-2"],
 ["n114", "style-br-14", "n116", "style-br-16"]
];
const ListRow3_meta: string[][] = [
 ["style-font-15"],
 ["style-font-10"],
 ["style-br-11"],
 ["style-heading-2"]
];
const ListRow4_meta: string[][] = [
 ["style-font-25"],
 ["style-font-16"],
 ["style-li-3"],
 ["style-font-22"]
];
const Tile_styles = [
 { className: "before:content-['']" },
 { className: "before:content-['']" },
 { className: "before:content-['']" }
];
const ListRow_styles = [
 { className: "text-color-007" },
 { className: "text-color-001" },
 { className: "text-color-001" }
];
const ListRow2_styles = [
 { className: "border-b border-solid border-b-color-006" },
 { className: "border-b border-solid border-b-color-006" },
 { className: "border-b border-solid border-b-color-006" },
 { }
];
const ListRow3_styles = [
 { className: "border-b border-solid border-b-color-006" },
 { className: "border-b border-solid border-b-color-006" },
 { className: "border-b border-solid border-b-color-006" },
 { }
];
const ListRow4_styles = [
 { className: "border-b border-solid border-b-color-006" },
 { className: "border-b border-solid border-b-color-006" },
 { className: "border-b border-solid border-b-color-006" },
 { }
];

export default function Page() {
 return (
 <>
 <main className="block grow shrink-0">
 <div className="h-full block" id="wrap">
 <div className="block">
 <section className="block relative py-6 overflow-hidden text-background bg-color-004">
 <span className="h-full block absolute top-0 inset-x-0 overflow-hidden bg-cover [background-position:50%_0px] bg-no-repeat [background-attachment:fixed] pointer-events-none max-lg:[background-attachment:initial]" style={{ backgroundImage: "url(\"/assets/cloned/images/2873c8e777c4.jpg\")" }} data-ditto-id="style-span-8" />
 {" "}
 <div className="h-full block absolute top-0 inset-x-0 overflow-hidden bg-color-004 bg-no-repeat pointer-events-none" data-ditto-id="style-div-28" />
 {" "}
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-div-33">
 <h1 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[3.875rem] font-bold leading-[4.625rem] max-md:text-4xl max-md:leading-[2.6875rem] md:max-lg:text-5xl md:max-lg:leading-[3.625rem]" data-ditto-id="style-heading-6" data-component="heading">
 <font className="inline" data-ditto-id="style-div-29">
 {" "}
 <font className="inline" data-ditto-id="style-section-5">
 Prijs : €
 </font>
 {" "}
 </font>
 {" "}
 </h1>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 </div>
 {" "}
 <div className="block pt-8 pb-12 text-background bg-color-005" data-ditto-id="style-div-30">
 <div className="h-200 block absolute top-0 inset-x-0 overflow-hidden [background-size:100%] [background-position:50%_100%] bg-no-repeat pointer-events-none max-md:hidden md:max-lg:h-256 2xl:h-270" style={{ backgroundImage: "url(\"/assets/cloned/svg/0ee549800605.svg\")" }} data-ditto-id="style-p-2" />
 {" "}
 <div className="block max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-br-4">
 <div className="flex -mx-[0.9375rem] flex-wrap" data-ditto-id="style-span-20">
 <div className="w-95 h-[37.6125rem] min-h-6 block max-w-full pt-20 pb-4 px-[0.9375rem] shrink-0 text-center max-md:w-[23.4375rem] max-md:h-[35.2rem] md:max-lg:w-180 md:max-lg:h-[34.85rem] 2xl:w-110" data-ditto-id="style-span-6">
 <div className="h-full border border-solid border-clr-0 flex relative rounded-md flex-col overflow-hidden text-foreground [overflow-wrap:break-word] bg-border" data-ditto-id="style-br-5">
 <h4 className="border-b border-solid border-b-clr-0 block py-2 px-4 rounded-tl-[5.4px] rounded-tr-[5.4px] [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-2xl font-bold leading-[1.8125rem] bg-color-008 max-md:text-[1.375rem] max-md:leading-[1.625rem] md:max-lg:text-[1.4375rem] md:max-lg:leading-[1.6875rem]" data-component="heading">
 <font className="inline">
 {" "}
 <font className="inline" data-ditto-id="style-span-5">
 Eenvoudig
 </font>
 {" "}
 </font>
 {" "}
 <br className="inline" data-ditto-id="style-u" />
 {" "}
 </h4>
 {" "}
 <div className="block p-4 grow bg-surface-2" data-ditto-id="style-br-10">
 <h2 className="block [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[2.75rem] font-bold leading-[3.3125rem] max-md:text-[1.8125rem] max-md:leading-[2.1875rem] md:max-lg:text-4xl md:max-lg:leading-[2.75rem]" data-ditto-id="style-br-3" data-component="heading">
 <span className="inline-block align-middle text-[2.1875rem] leading-[2.625rem] max-md:text-[1.4375rem] max-md:leading-7 md:max-lg:text-[1.8125rem] md:max-lg:leading-[2.1875rem]" data-ditto-id="style-span-7">
 <font className="inline align-middle" data-ditto-id="style-br-15">
 <font className="inline align-middle" data-ditto-id="style-br-7">
 €
 </font>
 </font>
 </span>
 {" "}
 <span className="inline-block align-middle text-[5.5rem] leading-[6.625rem] max-md:text-[3.625rem] max-md:leading-[4.375rem] md:max-lg:text-7xl md:max-lg:leading-[5.4375rem]" data-ditto-id="style-span-10">
 <b className="inline font-black">
 <font className="inline">
 <font className="inline">
 35
 </font>
 </font>
 </b>
 </span>
 <span className="inline-block align-middle text-[2.1875rem] leading-[2.625rem] max-md:text-[1.4375rem] max-md:leading-7 md:max-lg:text-[1.8125rem] md:max-lg:leading-[2.1875rem]" data-ditto-id="style-br-2">
 <font className="inline align-middle" data-ditto-id="style-br-9">
 <font className="inline align-middle" data-ditto-id="style-span-9">
 .00
 </font>
 </font>
 </span>
 </h2>
 {" "}
 <small className="inline text-sm leading-[1.3125rem]" data-ditto-id="style-br-8">
 {" "}
 <font className="inline" data-ditto-id="style-br-18">
 {" "}
 <font className="inline" data-ditto-id="style-span-15">
 / Maan
 </font>
 {" "}
 </font>
 {" "}
 </small>
 {" "}
 </div>
 {" "}
 <ul className="border-t border-solid border-t-clr-0 border-b border-b-clr-0 flex flex-col [list-style-type:disc] list-outside" data-ditto-id="style-br-17">
 {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} styles={ListRow2_styles[i]} />)}
 </ul>
 {" "}
 <div className="block py-2 px-4 rounded-br-[5.4px] rounded-bl-[5.4px] bg-color-008" data-ditto-id="style-br-6" aria-describedby="tooltip940462">
 <p className="block mb-4">
 <i className="inline italic" data-ditto-id="style-bottom">
 {" "}
 <font className="inline" data-ditto-id="style-footer">
 {" "}
 <font className="inline" data-ditto-id="style-section">
 Directe installatie, tevredenheid of geld terug.
 </font>
 {" "}
 </font>
 {" "}
 </i>
 {" "}
 <br className="inline" data-ditto-id="style-div-31" />
 {" "}
 </p>
 {" "}
 <Link className="h-[43.5px] inline-block mb-2 py-3 px-6 align-middle text-background text-xs leading-4.5 tracking-[0.6px] uppercase bg-accent cursor-pointer" data-ditto-id="style-div-7" data-component="link" href="/contactus">
 {" "}
 <font className="inline align-middle" data-ditto-id="style-div-32">
 {" "}
 <font className="inline align-middle" data-ditto-id="style-p-3" aria-describedby="tooltip761609">
 bestel nu
 </font>
 {" "}
 </font>
 {" "}
 </Link>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 <div className="w-95 h-[37.6125rem] min-h-6 block max-w-full pt-8 pb-4 px-[0.9375rem] shrink-0 text-center max-md:w-[23.4375rem] max-md:h-[30.7rem] md:max-lg:w-180 md:max-lg:h-[30.35rem] 2xl:w-110" data-ditto-id="style-font-12">
 <div className="border border-solid border-clr-1 flex relative rounded-md flex-col overflow-hidden [overflow-wrap:break-word] bg-accent" data-ditto-id="style-font-9">
 <h4 className="border-b border-solid border-b-clr-1 block py-2 px-4 rounded-tl-[5.4px] rounded-tr-[5.4px] [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-2xl font-bold leading-[1.8125rem] bg-color-008 max-md:text-[1.375rem] max-md:leading-[1.625rem] md:max-lg:text-[1.4375rem] md:max-lg:leading-[1.6875rem]" data-ditto-id="style-br-23" data-component="heading">
 <font className="inline" data-ditto-id="style-heading-5">
 {" "}
 <font className="inline" data-ditto-id="style-font-13">
 Professioneel
 </font>
 {" "}
 </font>
 {" "}
 <br className="inline" data-ditto-id="style-font-3" />
 {" "}
 </h4>
 {" "}
 <div className="block p-4 grow text-foreground bg-surface-2" data-ditto-id="style-div">
 <h2 className="block [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[2.75rem] font-bold leading-[3.3125rem] max-md:text-[1.8125rem] max-md:leading-[2.1875rem] md:max-lg:text-4xl md:max-lg:leading-[2.75rem]" data-ditto-id="style-p-4" data-component="heading" aria-describedby="tooltip653069">
 <span className="inline-block align-middle text-[2.1875rem] leading-[2.625rem] max-md:text-[1.4375rem] max-md:leading-7 md:max-lg:text-[1.8125rem] md:max-lg:leading-[2.1875rem]" data-ditto-id="style-font-41">
 {" "}
 <font className="inline align-middle">
 {" "}
 <font className="inline align-middle" data-ditto-id="style-heading-3">
 €
 </font>
 {" "}
 </font>
 {" "}
 </span>
 {" "}
 <span className="inline-block align-middle text-[5.5rem] leading-[6.625rem] max-md:text-[3.625rem] max-md:leading-[4.375rem] md:max-lg:text-7xl md:max-lg:leading-[5.4375rem]" data-ditto-id="style-span-17">
 {" "}
 <b className="inline font-black" data-ditto-id="style-link-6">
 {" "}
 <font className="inline" data-ditto-id="style-font-4">
 {" "}
 <font className="inline" data-ditto-id="style-font-14">
 65
 </font>
 {" "}
 </font>
 {" "}
 </b>
 {" "}
 </span>
 {" "}
 <span className="inline-block align-middle text-[2.1875rem] leading-[2.625rem] max-md:text-[1.4375rem] max-md:leading-7 md:max-lg:text-[1.8125rem] md:max-lg:leading-[2.1875rem]" data-ditto-id="style-heading">
 {" "}
 <font className="inline align-middle" data-ditto-id="style-link-7">
 {" "}
 <font className="inline align-middle" data-ditto-id="style-font-5">
 .00
 </font>
 {" "}
 </font>
 {" "}
 </span>
 {" "}
 </h2>
 {" "}
 <small className="inline text-sm leading-[1.3125rem]" data-ditto-id="style-font-42">
 {" "}
 <font className="inline" data-ditto-id="style-span-16">
 {" "}
 <font className="inline" data-ditto-id="style-div-13">
 / Maan
 </font>
 {" "}
 </font>
 {" "}
 </small>
 {" "}
 </div>
 {" "}
 <ul className="border-t border-solid border-t-clr-1 border-b border-b-clr-1 flex flex-col [list-style-type:disc] list-outside">
 {ListRow3_data.map((d, i) => <ListRow3 key={i} d={d} styles={ListRow3_styles[i]} />)}
 </ul>
 {" "}
 <div className="block py-2 px-4 rounded-br-[5.4px] rounded-bl-[5.4px] bg-color-008" data-ditto-id="style-link-8">
 <p className="block mb-4" data-ditto-id="style-font-6">
 <i className="inline italic" data-ditto-id="style-font-24">
 {" Directe installatie, tevredenheid of geld terug."}
 </i>
 <Link className="h-[43.5px] inline-block mb-2 py-3 px-6 align-middle text-foreground text-xs leading-4.5 tracking-[0.6px] uppercase bg-border cursor-pointer" data-ditto-id="style-div-22" data-component="link" href="/contactus">
 <font className="inline align-middle" data-ditto-id="style-div-11">
 <font className="inline align-middle" data-ditto-id="style-p-7" aria-describedby="tooltip913795">
 BESTEL NU
 </font>
 </font>
 </Link>
 {" "}
 </p>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 <div className="w-95 h-[37.6125rem] min-h-6 block max-w-full pt-20 pb-4 px-[0.9375rem] shrink-0 text-center max-md:w-[23.4375rem] max-md:h-[33.7rem] md:max-lg:w-180 md:max-lg:h-[34.85rem] 2xl:w-110" data-ditto-id="style-font-7">
 <div className="border border-solid border-clr-0 flex relative rounded-md flex-col overflow-hidden text-foreground [overflow-wrap:break-word] bg-border" data-ditto-id="style-font-35">
 <h4 className="border-b border-solid border-b-clr-0 block py-2 px-4 rounded-tl-[5.4px] rounded-tr-[5.4px] [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-2xl font-bold leading-[1.8125rem] bg-color-008 max-md:text-[1.375rem] max-md:leading-[1.625rem] md:max-lg:text-[1.4375rem] md:max-lg:leading-[1.6875rem]" data-ditto-id="style-link-9" data-component="heading">
 <font className="inline" data-ditto-id="style-i-3">
 {" "}
 <font className="inline" data-ditto-id="style-link-10">
 Deskundige
 </font>
 {" "}
 </font>
 {" "}
 <br className="inline" data-ditto-id="style-i-2" />
 {" "}
 </h4>
 {" "}
 <div className="block p-4 grow bg-surface-2" data-ditto-id="style-link-11">
 <h2 className="block [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[2.75rem] font-bold leading-[3.3125rem] max-md:text-[1.8125rem] max-md:leading-[2.1875rem] md:max-lg:text-4xl md:max-lg:leading-[2.75rem]" data-ditto-id="style-i" data-component="heading">
 <span className="inline-block align-middle text-[2.1875rem] leading-[2.625rem] max-md:text-[1.4375rem] max-md:leading-7 md:max-lg:text-[1.8125rem] md:max-lg:leading-[2.1875rem]" data-ditto-id="style-section-2">
 <font className="inline align-middle" data-ditto-id="style-div-6">
 <font className="inline align-middle" data-ditto-id="style-div-5">
 €
 </font>
 </font>
 </span>
 {" "}
 <span className="inline-block align-middle text-[5.5rem] leading-[6.625rem] max-md:text-[3.625rem] max-md:leading-[4.375rem] md:max-lg:text-7xl md:max-lg:leading-[5.4375rem]" data-ditto-id="style-hr">
 <b className="inline font-black" data-ditto-id="style-section-6">
 <font className="inline" data-ditto-id="style-div-34">
 <font className="inline" data-ditto-id="style-div-4">
 125
 </font>
 </font>
 </b>
 </span>
 <span className="inline-block align-middle text-[2.1875rem] leading-[2.625rem] max-md:text-[1.4375rem] max-md:leading-7 md:max-lg:text-[1.8125rem] md:max-lg:leading-[2.1875rem]" data-ditto-id="style-div-21">
 <font className="inline align-middle" data-ditto-id="style-link-12">
 <font className="inline align-middle" data-ditto-id="style-irketim-logosu">
 .00
 </font>
 </font>
 </span>
 </h2>
 {" "}
 <small className="inline text-sm leading-[1.3125rem]" data-ditto-id="style-div-12">
 {" "}
 <font className="inline" data-ditto-id="style-ul">
 {" "}
 <font className="inline" data-ditto-id="style-li">
 / Maan
 </font>
 {" "}
 </font>
 {" "}
 </small>
 {" "}
 </div>
 {" "}
 <ul className="border-t border-solid border-t-clr-0 border-b border-b-clr-0 flex flex-col [list-style-type:disc] list-outside" data-ditto-id="style-link-13">
 {ListRow4_data.map((d, i) => <ListRow4 key={i} d={d} styles={ListRow4_styles[i]} />)}
 </ul>
 {" "}
 <div className="block py-2 px-4 rounded-br-[5.4px] rounded-bl-[5.4px] bg-color-008">
 <p className="block mb-4" data-ditto-id="style-li-8">
 <i className="inline italic" data-ditto-id="style-link-14">
 {" Directe installatie, tevredenheid of geld terug. "}
 </i>
 {" "}
 </p>
 {" "}
 <Link className="h-[43.5px] inline-block mb-2 py-3 px-6 align-middle text-background text-xs leading-4.5 tracking-[0.6px] uppercase bg-accent cursor-pointer" data-ditto-id="style-font-26" data-component="link" href="/contactus">
 {" "}
 <font className="inline align-middle" data-ditto-id="style-font">
 {" "}
 <font className="inline align-middle" data-ditto-id="style-li-4" aria-describedby="tooltip741046">
 bestel nu​
 </font>
 {" "}
 </font>
 {" "}
 </Link>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </main>
 {" "}
 <footer className="block shrink-0 text-background bg-color-004" data-ditto-id="style-font-19" id="bottom">
 <div className="block" data-ditto-id="style-font-43" id="footer">
 <section className="block relative pt-8 pb-4" data-ditto-id="style-li-11">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 " data-ditto-id="style-link-15">
 <div className="flex -mx-[0.9375rem] flex-wrap items-end" data-ditto-id="style-font-27">
 <div className="w-[17.8125rem] h-[8.1rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[123.7px] md:max-lg:w-180 md:max-lg:h-[6.2rem] 2xl:w-82.5" data-ditto-id="style-font-8">
 <p className="block mb-2" data-ditto-id="style-li-2">
 <font className="inline" data-ditto-id="style-font-33">
 {" "}
 <font className="inline" data-ditto-id="style-font-2">
 Hoe kunnen we helpen
 </font>
 {" "}
 </font>
 {" "}
 <br className="inline" data-ditto-id="style-li-12" />
 {" "}
 </p>
 {" "}
 <h4 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-2xl font-bold leading-[1.8125rem] max-md:text-[1.375rem] max-md:leading-[1.625rem] md:max-lg:text-[1.4375rem] md:max-lg:leading-[1.6875rem]" data-ditto-id="style-link-16" data-component="heading">
 <font className="inline" data-ditto-id="style-font-28">
 {" "}
 <font className="inline" data-ditto-id="style-font-34">
 {"U kunt altijd contact met ons opnemen "}
 </font>
 {" "}
 </font>
 {" "}
 </h4>
 {" "}
 </div>
 {" "}
 <div className="w-[17.8125rem] h-[8.15rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[128.9px] md:max-lg:w-180 md:max-lg:h-[8.1rem] 2xl:w-82.5" aria-describedby="tooltip8305">
 <p className="block mb-2" data-ditto-id="style-font-17">
 <font className="inline" data-ditto-id="style-font-11">
 {" "}
 <font className="inline" data-ditto-id="style-li-13">
 Bel ons
 </font>
 {" "}
 </font>
 {" "}
 </p>
 {" "}
 <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-ditto-id="style-link-17" data-component="heading">
 <span className="inline">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-font-18" data-component="link" href="tel:31 (0) 33 46 11 447">
 {" "}
 <font className="inline" data-ditto-id="style-div-2">
 {" "}
 <font className="inline">
 {"+31 (0) 33 46 11 447 "}
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </span>
 {" "}
 </h5>
 {" "}
 <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-ditto-id="style-div-8" data-component="heading" aria-describedby="tooltip842231">
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-div-14" data-component="link" href="tel:31 (0) 33 46 11 447">
 {" "}
 <font className="inline" data-ditto-id="style-span-11">
 {" "}
 <font className="inline" data-ditto-id="style-p">
 +31 (0) 6 11 23 88 30
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 <span className="inline" data-ditto-id="style-link-18">
 {" "}
 </span>
 {" "}
 </h5>
 {" "}
 </div>
 {" "}
 <div className="w-[17.8125rem] h-[6.075rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[6.025rem] md:max-lg:w-180 md:max-lg:h-[6.05rem] 2xl:w-82.5" data-ditto-id="style-div-15" aria-describedby="tooltip941693">
 <p className="block mb-2">
 <font className="inline" data-ditto-id="style-link-40">
 {" "}
 <font className="inline" data-ditto-id="style-image">
 Stuur ons een bericht
 </font>
 {" "}
 </font>
 {" "}
 <br className="inline" data-ditto-id="style-link-19" />
 {" "}
 </p>
 {" "}
 <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-ditto-id="style-website-cookies-bar" data-component="heading">
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-div-26" data-component="link" href="mailto:info@ahneta.nl">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline" data-ditto-id="style-div-27">
 info@ahneta.nl
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </h5>
 {" "}
 </div>
 {" "}
 <div className="w-[17.8125rem] h-[97.3px] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] md:max-lg:w-180 2xl:w-82.5" data-ditto-id="style-div-9">
 <div className="block text-right" data-ditto-id="style-div-16">
 <p className="block mr-[0.4rem] mb-2 align-middle">
 <font className="inline align-middle" data-ditto-id="style-link-21">
 {" "}
 <font className="inline align-middle" data-ditto-id="style-font-21">
 Volg ons
 </font>
 {" "}
 </font>
 {" "}
 </p>
 {" "}
 <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-font-36" data-component="link" href="https://www.ahneta.nl/website/social/twitter">
 {" "}
 <i className="flex m-1 justify-center items-center [font-family:FontAwesome-twitter-x-only] leading-4 before:content-[''] before:block before:w-4 before:h-4 before:text-primary before:text-base before:leading-4 before:text-right">
 ​
 </i>
 {" "}
 </a>
 {" "}
 <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-font-20" data-component="link" href="https://www.ahneta.nl/website/social/linkedin">
 {" "}
 <i className="flex m-1 justify-center items-center [font-family:FontAwesome] leading-4 before:content-[''] before:block before:w-[13.7px] before:h-4 before:text-primary before:text-base before:leading-4 before:text-right" aria-describedby="tooltip290654">
 ​
 </i>
 {" "}
 </a>
 {" "}
 <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-li-6" data-component="link" href="https://www.ahneta.nl/website/social/instagram">
 {" "}
 <i className="flex m-1 justify-center items-center [font-family:FontAwesome] leading-4 before:content-[''] before:block before:w-[13.7px] before:h-4 before:text-primary before:text-base before:leading-4 before:text-right" data-ditto-id="style-link-22">
 ​
 </i>
 {" "}
 </a>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative" data-ditto-id="style-font-23">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 ">
 <div className="block py-4 leading-0" data-ditto-id="style-li-7">
 <hr className="h-px border-t border-solid border-t-muted-foreground block overflow-hidden mx-auto w-[69.375rem] max-md:w-[21.5625rem] md:max-lg:w-[43.125rem] 2xl:w-[80.625rem]" />
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 " data-ditto-id="style-li-5">
 <div className="flex -mx-[0.9375rem] flex-wrap items-center" data-ditto-id="style-link-23" aria-describedby="tooltip859185">
 <div className="w-47.5 h-[6.3125rem] min-h-6 block max-w-full pb-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-lg:h-34 md:max-lg:w-180 2xl:w-55 2xl:h-[116.9px]">
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-font-37" data-component="link" href="/">
 {" "}
 <img className="w-40 h-[5.3125rem] inline max-w-full overflow-clip align-middle max-lg:w-56.5 max-lg:h-30 2xl:w-47.5 2xl:h-[6.3125rem]" data-component="image" alt="" aria-label="Şirketim logosu" role="img" src="/assets/cloned/images/1461683c0d67.png" title="Benim şirketim" />
 {" "}
 </Link>
 {" "}
 </div>
 {" "}
 <div className="w-237.5 h-10 min-h-6 block max-w-full pb-4 px-[0.9375rem] shrink-0 text-right max-md:w-[23.4375rem] max-md:h-16 md:max-lg:w-180 2xl:w-275" data-ditto-id="style-div-10" aria-describedby="tooltip611099">
 <ul className="h-full block [list-style-type:none] list-outside" aria-describedby="tooltip612522">
 <li className="inline-block mr-2">
 {" "}
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-span-18" data-component="link" href="/">
 {" "}
 <font className="inline" data-ditto-id="style-p-6">
 {" "}
 <font className="inline" data-ditto-id="style-link-24">
 Home
 </font>
 {" "}
 </font>
 {" "}
 </Link>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-div-3">
 {" "}
 <font className="inline" data-ditto-id="style-div-17">
 {" "}
 <font className="inline">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block mr-2">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-link-25" data-component="link" href="#">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline">
 Over ons
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </li>
 <li className="inline-block mr-2">
 {" "}
 <font className="inline" data-ditto-id="style-div-18">
 {" "}
 <font className="inline">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block mr-2">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-avatar" data-component="link" href="#">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline" aria-describedby="tooltip841579">
 Product
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </li>
 <li className="inline-block mr-2">
 {" "}
 <font className="inline" data-ditto-id="style-span-14">
 {" "}
 <font className="inline" data-ditto-id="style-span-21">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block mr-2">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-span-19" data-component="link" href="#">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline" data-ditto-id="style-section-3" aria-describedby="tooltip455312">
 Gebruiksvoorwaarden
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </li>
 <li className="inline-block mr-2">
 {" "}
 <font className="inline" data-ditto-id="style-div-19">
 {" "}
 <font className="inline">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block">
 {" "}
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-br-19" data-component="link" aria-describedby="tooltip848069" href="/privacy">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline">
 Privacybeleid
 </font>
 {" "}
 </font>
 {" "}
 </Link>
 {" "}
 </li>
 </ul>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 </div>
 {" "}
 <div className="block bg-color-005">
 <div className="block max-w-285 mx-auto py-4 px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 " data-ditto-id="style-myquotecarousel617108">
 <div className="flex -mx-[0.9375rem] flex-wrap">
 <div className="w-full block max-w-full px-[0.9375rem] grow shrink-0 basis-[0%] text-color-003 text-left max-md:text-center max-md:grow-[initial] max-md:basis-[initial]" data-ditto-id="style-li-9">
 <span className="inline align-middle" data-ditto-id="style-li-10">
 Copyright © Ahneta Advies
 </span>
 {" "}
 <p className="block mb-4">
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-footer-2" data-component="link" href="/cookie-policy">
 Cookiebeleid
 </Link>
 </p>
 </div>
 {" "}
 <div className="w-142.5 block max-w-full my-[1.3125rem] px-[0.9375rem] grow shrink-0 basis-[0%] text-right max-md:w-[23.4375rem] max-md:text-center max-md:my-0 max-md:grow-[initial] max-md:basis-[initial] md:max-lg:w-90 md:max-lg:my-[0.5625rem] 2xl:w-165" data-ditto-id="style-section-4">
 <div className="h-full block">
 {" "}
 <a className="text-color-003 cursor-pointer hover:underline" href="https://imora.nl" target="_blank" rel="noopener noreferrer">
 Maintained by Imora
 </a>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </footer>
 {" "}
 <div className="block shrink-0" id="website_cookies_bar">
 {" "}
 </div>
 {" "}
 {" "}
 <div className="block">
 <div className="block" data-ditto-id="style-br-20" />
 <div className="block" data-ditto-id="style-heading-4" />
 <div className="w-78 h-0 block absolute top-[52.9px] left-240 z-1055 max-md:left-[3.4375rem] md:max-lg:left-112 2xl:left-400" />
 <div className="w-78 h-0 block absolute top-[52.9px] left-240 z-1055 max-md:left-[3.4375rem] md:max-lg:left-112 2xl:left-400" />
 </div>
 </>
 );
}
