import "./ditto.css";
import Tile from "./components/tile";
import ListRow from "./components/list-row";
import Link from "next/link";

export const metadata = {
 "title": "Privacy Policy | Ahneta Advies",
 "alternates": {
 "canonical": "/privacy"
 },
 "openGraph": {
 "title": "Privacy Policy | Ahneta Advies"
 },
 "twitter": {
 "title": "Privacy Policy | Ahneta Advies"
 }
};
// Generated by clone-site. Do not edit by hand.
const Tile_data = [
 { text: "Lageprijsgarantie" },
 { text: "30 dagen online retourneren" },
 { text: "Standaard verzending" }
];
const ListRow_data = [
 { href: "/pricing", label: "Prijs" },
 { href: "/over-ons", label: "Over ons" },
 { href: "/contactus", label: "Contact" }
];
const Tile_meta: string[][] = [
 ["n10", "n11"],
 ["n12", "n13"],
 ["n14", "n15"]
];
const ListRow_meta: string[][] = [
 ["n48", "style-9", "style-15"],
 ["n51", "style-10", "style-16"],
 ["n54", "style-11", "style-17"]
];
const Tile_styles = [
 { className: "before:content-['']" },
 { className: "before:content-['']" },
 { className: "before:content-['']" }
];

export default function Page() {
 return (
 <>
 <main className="block grow shrink-0">
 <div className="h-full block" id="wrap">
 <div className="block">
 <section className="block relative py-6 overflow-hidden text-background bg-color-004">
 <span className="h-full block absolute top-0 inset-x-0 overflow-hidden bg-cover [background-position:50%_0px] bg-no-repeat [background-attachment:fixed] pointer-events-none max-lg:[background-attachment:initial]" style={{ backgroundImage: "url(\"/assets/cloned/images/2873c8e777c4.jpg\")" }} data-ditto-id="style-span-8" />
 {" "}
 <div className="h-full block absolute top-0 inset-x-0 overflow-hidden bg-color-004 bg-no-repeat pointer-events-none" data-ditto-id="style-div-28" />
 {" "}
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-div-33">
 <h1 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[3.875rem] font-bold leading-[4.625rem] max-md:text-4xl max-md:leading-[2.6875rem] md:max-lg:text-5xl md:max-lg:leading-[3.625rem]" data-ditto-id="style-heading-6" data-component="heading">
 Algemene Voorwaarden Ahneta
 <br className="inline" data-ditto-id="style-div-29" />
 </h1>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 </div>
 {" "}
 <div className="block py-8" data-ditto-id="style-section-5">
 <div className="block max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-ditto-id="style-div-30">
 <div className="block" data-ditto-id="style-p-2" id="myCollapse" role="tablist">
 <div className="border border-solid border-clr-0 flex relative rounded-md flex-col overflow-hidden [overflow-wrap:break-word] bg-background" data-ditto-id="style-br-4">
 <a className="border-b border-solid border-b-clr-2 block relative py-2 pr-4 pl-9 text-color-002 bg-color-008 cursor-pointer before:content-[''] before:[font-family:FontAwesome] before:block before:absolute before:inset-y-2 before:right-[1082.3px] before:left-9 before:w-[13.7px] before:h-6 before:-ml-6 before:text-muted-foreground before:text-base before:leading-6 max-md:before:right-[317.3px] md:max-lg:before:right-[662.3px] 2xl:before:right-[1262.3px]" data-ditto-id="style-span-20" data-component="link" aria-expanded="true" href="#" role="tab">
 Servicevoorwaarden
 </a>
 {" "}
 <div className="block" data-ditto-id="style-span-6" id="myCollapseTab663658_1" role="tabpanel">
 <div className="block mt-px py-4 pr-4 pl-9 rounded-[5.4px] grow bg-surface-2" data-ditto-id="style-br-5">
 <p className="block mb-4">
 Deze servicevoorwaarden ("Voorwaarden", "Overeenkomst") vormen een overeenkomst tussen de website ("Website-operator", "ons", "wij" of "onze") en je ("Gebruiker", "jij" of "je"). Deze overeenkomst bevat de algemene voorwaarden voor je gebruik van deze website en alle producten of diensten (gezamenlijk, "Website" of "Diensten").
 </p>
 {" "}
 <p className="block">
 <span className="inline font-bold" data-ditto-id="style-span-5">
 Artikel 1 Algemeen
 </span>
 <br className="inline" data-ditto-id="style-u" />
 In de algemene voorwaarden wordt verstaan onder:
 <br className="inline" data-ditto-id="style-br-10" />
 1. Opdrachtgever: de partij die opdracht geeft.
 <br className="inline" data-ditto-id="style-br-3" />
 2. Opdrachtnemer: Ahneta.
 <br className="inline" data-ditto-id="style-span-7" />
 <br className="inline" data-ditto-id="style-br-15" />
 <span className="inline font-bold" data-ditto-id="style-br-7">
 Artikel 2 Toepasselijkheid
 </span>
 <br className="inline" data-ditto-id="style-span-10" />
 <span className="inline">
 1. Deze algemene voorwaarden zijn van toepassing op alle rechtsverhoudingen tussen opdrachtnemer en opdrachtgever, behoudens wijzigingen in deze voorwaarden welke door beide partijen uitdrukkelijk en schriftelijk dienen te zijn bevestigd.
 </span>
 <br className="inline" />
 <span className="inline">
 2. De gedrags- en beroepsregels voor de opdrachtnemer maken deel uit van de overeenkomst. De opdrachtgever verklaart de daaruit voor opdrachtnemer voortvloeiende verplichtingen steeds volledig te zullen respecteren.
 </span>
 <br className="inline" data-ditto-id="style-br-2" />
 <span className="inline" data-ditto-id="style-br-9">
 3. De toepasselijkheid van de algemene voorwaarden van opdrachtgever wordt hierbij nadrukkelijk van de hand gewezen.
 </span>
 <br className="inline" data-ditto-id="style-span-9" />
 <br className="inline" data-ditto-id="style-br-8" />
 <span className="inline font-bold" data-ditto-id="style-br-18">
 Artikel 3 Totstandkoming van de overeenkomst
 </span>
 <br className="inline" data-ditto-id="style-span-15" />
 <span className="inline" data-ditto-id="style-br-17">
 1. De overeenkomst komt tot stand op het moment dat de door opdrachtnemer en opdrachtgever ondertekende opdrachtbevestiging door opdrachtnemer retour is ontvangen. De bevestiging is gebaseerd op de ten tijde daarvan door opdrachtgever aan opdrachtnemer verstrekte informatie. De bevestiging wordt geacht de overeenkomst juist en volledig weer te geven. Indien de opdracht mondeling is overeengekomen, wordt de opdracht geacht te zijn tot stand gekomen op het moment dat de opdrachtnemer op verzoek van de opdrachtgever de werkzaamheden aanvangt onder toepassing van deze algemene voorwaarden.
 </span>
 <br className="inline" data-ditto-id="style-br-12" />
 <span className="inline" data-ditto-id="style-span-13">
 2. Het staat partijen vrij te bewijzen dat de overeenkomst op andere wijze tot stand is gekomen.
 </span>
 <br className="inline" data-ditto-id="style-br" />
 <span className="inline">
 3. De overeenkomst wordt aangegaan voor onbepaalde tijd tenzij uit de inhoud, aard of strekking van de verleende opdracht voortvloeit dat deze voor een bepaalde tijd is aangegaan.
 </span>
 <br className="inline" />
 <br className="inline" data-ditto-id="style-br-22" />
 <span className="inline font-bold" data-ditto-id="style-br-13">
 Artikel 4 Terbeschikkingstelling van informatie door de opdrachtgever
 </span>
 <br className="inline" data-ditto-id="style-span-22" />
 <span className="inline" data-ditto-id="style-br-21">
 1. Opdrachtgever is gehouden alle gegevens en bescheiden, welke opdrachtnemer in overeenstemming met zijn oordeel nodig heeft voor het correct uitvoeren van de verleende opdracht, tijdig in de gewenste vorm en op de gewenste wijze ter beschikking te stellen.
 </span>
 <br className="inline" />
 <span className="inline" data-ditto-id="style-span-12">
 2. In geval van opdrachten tot controle van financiële verantwoordingen zal opdrachtgever de opdrachtnemer op de hoogte brengen van alle overige informatie die voor de uitvoering of voltooiing van de opdracht relevant is.
 </span>
 <br className="inline" data-ditto-id="style-u-2" />
 <span className="inline">
 3. Opdrachtgever staat in voor de juistheid, volledigheid en betrouwbaarheid van de aan opdrachtnemer ter beschikking gestelde gegevens en bescheiden, ook indien deze van derden afkomstig zijn, voorzover uit de aard van de opdracht niet anders voortvloeit.
 </span>
 <br className="inline" data-ditto-id="style-br-14" />
 <span className="inline">
 4. Indien en voorzover opdrachtgever dat verzoekt, worden de ter beschikking gestelde bescheiden aan deze geretourneerd.
 </span>
 <br className="inline" data-ditto-id="style-br-16" />
 <span className="inline" data-ditto-id="style-br-6">
 5. De uit de vertraging in de uitvoering van de opdracht voortvloeiende extra kosten en extra honorarium, ontstaan door het niet, niet tijdig of niet behoorlijk ter beschikking stellen van de verlangde gegevens en bescheiden, zijn voor rekening van opdrachtgever.
 </span>
 <br className="inline" />
 <br className="inline" data-ditto-id="style-bottom" />
 <span className="inline" data-ditto-id="style-footer">
 <span className="inline font-bold" data-ditto-id="style-section">
 Artikel 5 Uitvoering van de opdracht
 </span>
 </span>
 <br className="inline" data-ditto-id="style-div-31" />
 <span className="inline" data-ditto-id="style-div-7">
 1. Opdrachtnemer bepaalt de wijze waarop en door welke persoon de verleende opdracht uitgevoerd wordt.
 </span>
 <br className="inline" data-ditto-id="style-div-32" />
 <span className="inline" data-ditto-id="style-p-3">
 2. Opdrachtnemer kan eerst meer werkzaamheden verrichten en aan opdrachtgever in rekening brengen dan waartoe opdracht is verstrekt, indien opdrachtgever hiervoor vooraf toestemming heeft verleend.
 </span>
 <br className="inline" data-ditto-id="style-font-12" />
 <span className="inline" data-ditto-id="style-font-9">
 3. Indien opdrachtgever derden bij de uitvoering van de opdracht wenst te betrekken, zal hij daartoe slechts overgaan na daarover met opdrachtnemer overeenstemming te hebben bereikt. Het bepaalde in de vorige volzin is van overeenkomstige toepassing op opdrachtnemer.
 </span>
 <br className="inline" data-ditto-id="style-br-23" />
 <br className="inline" data-ditto-id="style-heading-5" />
 <span className="inline font-bold" data-ditto-id="style-font-13">
 Artikel 6 Geheimhouding
 </span>
 <br className="inline" data-ditto-id="style-font-3" />
 <span className="inline" data-ditto-id="style-div">
 1. Opdrachtnemer is, tenzij hij een wettelijke of beroepsplicht tot bekendmaking heeft, verplicht tot geheimhouding tegenover derden.
 </span>
 <br className="inline" data-ditto-id="style-p-4" />
 <span className="inline" data-ditto-id="style-font-41">
 2. Opdrachtnemer is niet gerechtigd de informatie die aan hem door opdrachtgever ter beschikking wordt gesteld aan te wenden tot een ander doel dan waarvoor zij werd verkregen. Hierop wordt echter een uitzondering gemaakt in het geval opdrachtnemer voor zichzelf optreedt in een tucht-, civiele, of strafprocedure waarbij deze stukken van belang kunnen zijn.
 </span>
 <br className="inline" />
 <span className="inline" data-ditto-id="style-heading-3">
 3. Tenzij daartoe door opdrachtnemer voorafgaande schriftelijke toestemming is verleend, zal opdrachtgever de inhoud van rapporten, adviezen of andere al of niet schriftelijke uitingen van opdrachtnemer, die niet zijn opgesteld of gedaan met de strekking derden van de daarin neergelegde informatie te voorzien, niet openbaar maken. De opdrachtgever zal er tevens voor zorgdragen dat derden niet van de in de vorige zin bedoelde inhoud kennis kunnen nemen.
 </span>
 <br className="inline" data-ditto-id="style-span-17" />
 <span className="inline" data-ditto-id="style-link-6">
 4. Opdrachtnemer zal zijn verplichtingen op grond van dit artikel opleggen aan door hem ingeschakelde derden.
 </span>
 <br className="inline" data-ditto-id="style-font-4" />
 <br className="inline" data-ditto-id="style-font-14" />
 <span className="inline font-bold" data-ditto-id="style-heading">
 Artikel 7 Intellectuele eigendom
 </span>
 <br className="inline" data-ditto-id="style-link-7" />
 <span className="inline" data-ditto-id="style-font-5">
 1. Opdrachtnemer behoudt zich alle rechten voor met betrekking tot producten van de geest welke hij gebruikt of heeft gebruikt in het kader van de uitvoering van de opdracht van opdrachtgever, voorzover deze uit de wet voortvloeien.
 </span>
 <br className="inline" data-ditto-id="style-font-42" />
 <span className="inline" data-ditto-id="style-span-16">
 2. Het is opdrachtgever uitdrukkelijk verboden die producten, waaronder mede begrepen computerprogramma’s, systeemontwerpen, werkwijzen, adviezen, (model)contracten en andere geestesproducten van opdrachtnemer, een en ander in de ruimste zin des woords, al dan niet met inschakeling van derden te verveelvoudigen, te openbaren of te exploiteren.
 </span>
 <br className="inline" data-ditto-id="style-div-13" />
 <span className="inline">
 3. Het is opdrachtgever niet toegestaan hulpmiddelen van die producten aan derden ter hand te stellen, anders dan ter inwinning van een deskundig oordeel omtrent de werkzaamheden van opdrachtnemer.
 </span>
 <br className="inline" data-ditto-id="style-font-15" />
 <br className="inline" data-ditto-id="style-font-10" />
 <span className="inline font-bold" data-ditto-id="style-br-11">
 Artikel 8 Honorarium
 </span>
 <br className="inline" data-ditto-id="style-heading-2" />
 <span className="inline" data-ditto-id="style-link-8">
 1. Het honorarium van opdrachtnemer is niet afhankelijk van de uitkomst van de verleende opdracht.
 </span>
 <br className="inline" data-ditto-id="style-font-6" />
 <span className="inline" data-ditto-id="style-font-24">
 2. Indien na de totstandkoming van de overeenkomst, doch voordat de opdracht geheel is uitgevoerd, lonen en/of prijzen een wijziging ondergaan, is opdrachtnemer gerechtigd het overeengekomen tarief dienovereenkomstig aan te passen, tenzij opdrachtgever en opdrachtnemer hierover andere afspraken hebben gemaakt.
 </span>
 <br className="inline" data-ditto-id="style-div-22" />
 <span className="inline" data-ditto-id="style-div-11">
 3. Het honorarium van opdrachtnemer, zo nodig vermeerderd met voorschotten en declaraties van ingeschakelde derden, wordt per maand, per kwartaal, per jaar of na volbrenging van de werkzaamheden aan opdrachtgever in rekening gebracht, tenzij opdrachtgever en opdrachtnemer hierover andere afspraken hebben gemaakt. Over alle door opdrachtgever aan opdrachtnemer verschuldigde bedragen wordt de omzetbelasting afzonderlijk in rekening gebracht.
 </span>
 <br className="inline" data-ditto-id="style-p-7" />
 <br className="inline" data-ditto-id="style-font-7" />
 <span className="inline font-bold" data-ditto-id="style-font-35">
 Artikel 9 Betaling
 </span>
 <br className="inline" data-ditto-id="style-link-9" />
 <span className="inline" data-ditto-id="style-i-3">
 1. Betaling door opdrachtgever dient, zonder aftrek, korting of schuldverrekening, te geschieden binnen de overeengekomen termijnen, doch in geen geval later dan veertien dagen na factuurdatum. Betaling dient te geschieden in Nederlandse valuta door middel van overmaking ten gunste van een door opdrachtnemer aan te wijzen bankrekening.
 </span>
 <br className="inline" data-ditto-id="style-link-10" />
 <span className="inline" data-ditto-id="style-i-2">
 2. Indien opdrachtgever niet binnen de onder 9.1 genoemde termijn heeft betaald, is opdrachtnemer gerechtigd, nadat hij opdrachtgever ten minste eenmaal heeft aangemaand te betalen, zonder nadere ingebrekestelling en onverminderd de overige rechten van opdrachtnemer, vanaf de vervaldag opdrachtgever de wettelijke rente in rekening te brengen tot op de datum van algehele voldoening.
 </span>
 <br className="inline" data-ditto-id="style-link-11" />
 <span className="inline" data-ditto-id="style-i">
 3. Alle in redelijkheid gemaakte gerechtelijke en buitengerechtelijke ( incasso)kosten, die opdrachtnemer maakt als gevolg van de niet-nakoming door opdrachtgever van diens betalingsverplichtingen, komen ten laste van opdrachtgever.
 </span>
 <br className="inline" data-ditto-id="style-section-2" />
 <span className="inline" data-ditto-id="style-div-6">
 4. Indien de financiële positie of het betalingsgedrag van opdrachtgever naar het oordeel van opdrachtnemer daartoe aanleiding geeft, is opdrachtnemer gerechtigd van opdrachtgever te verlangen, dat deze onverwijld (aanvullende) zekerheid stelt in een door opdrachtnemer te bepalen vorm. Indien opdrachtgever nalaat de verlangde zekerheid te stellen, is opdrachtnemer gerechtigd, onverminderd zijn overige rechten, de verdere uitvoering van de overeenkomst onmiddellijk op te schorten en is al hetgeen opdrachtgever aan opdrachtnemer uit welke hoofde ook verschuldigd is, direct opeisbaar.
 </span>
 <br className="inline" data-ditto-id="style-div-5" />
 <span className="inline" data-ditto-id="style-hr">
 5. In geval van een gezamenlijk gegeven opdracht zijn opdrachtgevers, voorzover de werkzaamheden ten behoeve van de gezamenlijke opdrachtgevers zijn verricht, hoofdelijk verbonden voor de betaling van het factuurbedrag.
 </span>
 <br className="inline" data-ditto-id="style-section-6" />
 <br className="inline" data-ditto-id="style-div-34" />
 <span className="inline font-bold" data-ditto-id="style-div-4">
 Artikel 10 Reclames
 </span>
 <br className="inline" data-ditto-id="style-div-21" />
 <span className="inline" data-ditto-id="style-link-12">
 1. Reclames met betrekking tot de verrichte werkzaamheden en/of het factuurbedrag dienen schriftelijk binnen 60 dagen na de verzenddatum van de stukken of informatie waarover opdrachtgever reclameert, dan wel binnen 60 dagen na de ontdekking van het gebrek indien opdrachtgever aantoont dat hij het gebrek redelijkerwijs niet eerder kon ontdekken, aan opdrachtnemer te worden kenbaar gemaakt.
 </span>
 <br className="inline" data-ditto-id="style-irketim-logosu" />
 <span className="inline" data-ditto-id="style-div-12">
 2. Reclames als in het eerste lid bedoeld, schorten de betalingsverplichting van opdrachtgever niet op.
 </span>
 <br className="inline" data-ditto-id="style-ul" />
 <span className="inline" data-ditto-id="style-li">
 3. In geval van een terecht uitgebrachte reclame heeft opdrachtnemer de keuze tussen aanpassing van het in rekening gebrachte honorarium, het kosteloos verbeteren of opnieuw verrichten van de afgekeurde werkzaamheden of het geheel of gedeeltelijk niet (meer) uitvoeren van de opdracht tegen een restitutie naar evenredigheid van door opdrachtgever reeds betaald honorarium.
 </span>
 <br className="inline" data-ditto-id="style-link-13" />
 <br className="inline" data-ditto-id="style-font-25" />
 <span className="inline font-bold" data-ditto-id="style-font-16">
 Artikel 11 Leveringstermijn
 </span>
 <br className="inline" data-ditto-id="style-li-3" />
 <span className="inline" data-ditto-id="style-font-22">
 1. Is opdrachtgever een vooruitbetaling verschuldigd of dient hij voor de uitvoering benodigde informatie en/of materialen ter beschikking te stellen dan gaat de termijn waarbinnen de werkzaamheden dienen te worden afgerond niet eerder in dan nadat de betaling geheel is ontvangen, respectievelijk de informatie en/of materialen geheel ter beschikking zijn gesteld.
 </span>
 <br className="inline" />
 <span className="inline" data-ditto-id="style-li-8">
 2. Termijnen waarbinnen de werkzaamheden dienen te zijn afgerond, zijn slechts te beschouwen als een fatale termijn indien dit uitdrukkelijk is overeengekomen.
 </span>
 <br className="inline" data-ditto-id="style-link-14" />
 <span className="inline" data-ditto-id="style-font-26">
 3. De overeenkomst kan – tenzij uitvoering ontwijfelbaar blijvend onmogelijk is – door opdrachtgever niet wegens termijnoverschrijding worden ontbonden, tenzij opdrachtnemer de overeenkomst ook niet of niet geheel uitvoert binnen een hem na afloop van de overeengekomen leveringstermijn schriftelijk aangezegde redelijke termijn. Ontbinding is dan toegestaan conform artikel 265 Boek 6 van het Burgerlijk Wetboek.
 </span>
 <br className="inline" data-ditto-id="style-font" />
 <br className="inline" data-ditto-id="style-li-4" />
 <span className="inline font-bold" data-ditto-id="style-font-19">
 Artikel 12 Opzegging
 </span>
 <br className="inline" data-ditto-id="style-font-43" />
 <span className="inline" data-ditto-id="style-li-11">
 1. Opdrachtgever en opdrachtnemer kunnen te allen tijde de overeenkomst opzeggen met in achtneming van een redelijke opzegtermijn.
 </span>
 <br className="inline" data-ditto-id="style-link-15" />
 <span className="inline" data-ditto-id="style-font-27">
 2. Opzegging dient schriftelijk aan de wederpartij te worden meegedeeld.
 </span>
 <br className="inline" data-ditto-id="style-font-8" />
 <br className="inline" data-ditto-id="style-li-2" />
 <span className="inline font-bold" data-ditto-id="style-font-33">
 Artikel 13 Aansprakelijkheid
 </span>
 <br className="inline" data-ditto-id="style-font-2" />
 <span className="inline" data-ditto-id="style-li-12">
 1. Opdrachtnemer zal zijn werkzaamheden naar beste kunnen verrichten en daarbij de zorgvuldigheid in acht nemen die van hem kan worden verwacht. Indien een fout wordt gemaakt doordat de opdrachtgever hem onjuiste of onvolledige informatie heeft verstrekt, is opdrachtnemer voor de daardoor ontstane schade niet aansprakelijk. Indien de opdrachtgever aantoont dat hij schade heeft geleden door een fout van opdrachtnemer die bij zorgvuldig handelen zou zijn vermeden, is opdrachtnemer voor die schade slechts aansprakelijk tot:
 </span>
 <br className="inline" data-ditto-id="style-link-16" />
 <span className="inline" data-ditto-id="style-font-28">
 * in het geval van een opdracht tot controle van financiële verantwoordingen: een maximum van driemaal het bedrag van het honorarium voor de desbetreffende opdracht over het laatste kalenderjaar,
 </span>
 <br className="inline" data-ditto-id="style-font-34" />
 <span className="inline">
 * in alle andere gevallen: een maximum van het bedrag van het honorarium voor de desbetreffende opdracht, waarbij bij een doorlopende opdracht de hierbij bedoelde aansprakelijkheid maximaal het honorarium bedraagt dat in het kader van de opdracht in de laatste zes maanden voorafgaand aan de fouten aan de opdrachtgever is gefactureerd, tenzij er aan de zijde van opdrachtnemer sprake is van opzet of daarmee gelijk te stellen grove nalatigheid.
 </span>
 <br className="inline" data-ditto-id="style-font-17" />
 <span className="inline" data-ditto-id="style-font-11">
 2. Opdrachtgever vrijwaart opdrachtnemer voor vorderingen van derden wegens schade die veroorzaakt is doordat de opdrachtgever aan opdrachtnemer onjuiste of onvolledige informatie heeft verstrekt, tenzij opdrachtgever aantoont dat de schade geen verband houdt met verwijtbaar handelen of nalaten zijnerzijds danwel veroorzaakt is door opzet of grove schuld van opdrachtnemer.
 </span>
 <br className="inline" data-ditto-id="style-li-13" />
 <br className="inline" data-ditto-id="style-link-17" />
 <span className="inline font-bold">
 Artikel 14 Vervaltermijn
 </span>
 <br className="inline" data-ditto-id="style-font-18" />
 <span className="inline" data-ditto-id="style-div-2">
 Voorzover in deze algemene voorwaarden niet anders is bepaald, vervallen vorderingsrechten en andere bevoegdheden van opdrachtgever uit welke hoofde ook jegens opdrachtnemer in verband met het verrichten van werkzaamheden door opdrachtnemer in ieder geval na één jaar na het moment waarop opdrachtgever bekend werd of redelijkerwijs bekend kon zijn met het bestaan van deze rechten en bevoegdheden.
 </span>
 <br className="inline" />
 <br className="inline" data-ditto-id="style-div-8" />
 <span className="inline font-bold" data-ditto-id="style-div-14">
 Artikel 15 Toepasselijk recht en forumkeuze
 </span>
 <br className="inline" data-ditto-id="style-span-11" />
 <span className="inline" data-ditto-id="style-p">
 1. Op alle overeenkomsten tussen opdrachtgever en opdrachtnemer waarop deze algemene voorwaarden van toepassing zijn, is Nederlands recht van toepassing.
 </span>
 <br className="inline" data-ditto-id="style-link-18" />
 <span className="inline" data-ditto-id="style-div-15">
 2. Alle geschillen die verband houden met overeenkomsten tussen opdrachtgever en opdrachtnemer, waarop deze voorwaarden van toepassing zijn en welke niet tot de competentie van de kantonrechter behoren, worden beslecht door de bevoegde rechter in het arrondissement waarin opdrachtnemer zijn woonplaats heeft.
 </span>
 <br className="inline" />
 <span className="inline" data-ditto-id="style-link-40">
 3. In afwijking van het bepaalde in lid 2 zijn opdrachtgever en opdrachtnemer bevoegd om geschillen aan een college voor geschillen voor te leggen.
 </span>
 <br className="inline" data-ditto-id="style-image" />
 <br className="inline" data-ditto-id="style-link-19" />
 <span className="inline" data-ditto-id="style-website-cookies-bar">
 Juni 2010
 </span>
 <br className="inline" data-ditto-id="style-div-26" />
 </p>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 <div className="border border-solid border-clr-0 flex relative rounded-md flex-col overflow-hidden [overflow-wrap:break-word] bg-background">
 <a className="border-b border-solid border-b-clr-2 block relative py-2 pr-4 pl-9 text-color-002 bg-color-008 cursor-pointer before:content-[''] before:[font-family:FontAwesome] before:block before:absolute before:inset-y-2 before:right-[1082.3px] before:left-9 before:w-[13.7px] before:h-6 before:-ml-6 before:text-muted-foreground before:text-base before:leading-6 max-md:before:right-[317.3px] md:max-lg:before:right-[662.3px] 2xl:before:right-[1262.3px]" data-ditto-id="style-div-27" data-component="link" aria-expanded="false" href="#" role="tab">
 Links naar andere websites
 </a>
 {" "}
 </div>
 {" "}
 <div className="border border-solid border-clr-0 flex relative rounded-md flex-col overflow-hidden [overflow-wrap:break-word] bg-background" data-ditto-id="style-div-9">
 <a className="border-b border-solid border-b-clr-2 block relative py-2 pr-4 pl-9 text-color-002 bg-color-008 cursor-pointer before:content-[''] before:[font-family:FontAwesome] before:block before:absolute before:inset-y-2 before:right-[1082.3px] before:left-9 before:w-[13.7px] before:h-6 before:-ml-6 before:text-muted-foreground before:text-base before:leading-6 max-md:before:right-[317.3px] md:max-lg:before:right-[662.3px] 2xl:before:right-[1262.3px]" data-ditto-id="style-div-16" data-component="link" aria-expanded="false" href="#" role="tab">
 Gebruik van cookies
 </a>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </main>
 {" "}
 <footer className="block shrink-0 text-background bg-color-004" id="bottom">
 <div className="block" data-ditto-id="style-link-21" id="footer">
 <section className="block relative pt-8 pb-4" data-ditto-id="style-font-21">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 " data-ditto-id="style-font-36">
 <div className="flex -mx-[0.9375rem] flex-wrap items-end">
 <div className="w-[17.8125rem] h-[8.1rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[123.7px] md:max-lg:w-180 md:max-lg:h-[6.2rem] 2xl:w-82.5" data-ditto-id="style-font-20">
 <p className="block mb-2">
 <font className="inline" data-ditto-id="style-li-6">
 {" "}
 <font className="inline" data-ditto-id="style-link-22">
 Hoe kunnen we helpen
 </font>
 {" "}
 </font>
 {" "}
 <br className="inline" data-ditto-id="style-font-23" />
 {" "}
 </p>
 {" "}
 <h4 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-2xl font-bold leading-[1.8125rem] max-md:text-[1.375rem] max-md:leading-[1.625rem] md:max-lg:text-[1.4375rem] md:max-lg:leading-[1.6875rem]" data-component="heading">
 <font className="inline" data-ditto-id="style-li-7">
 {" "}
 <font className="inline">
 {"U kunt altijd contact met ons opnemen "}
 </font>
 {" "}
 </font>
 {" "}
 </h4>
 {" "}
 </div>
 {" "}
 <div className="w-[17.8125rem] h-[8.15rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[128.9px] md:max-lg:w-180 md:max-lg:h-[8.1rem] 2xl:w-82.5" aria-describedby="tooltip8305">
 <p className="block mb-2" data-ditto-id="style-li-5">
 <font className="inline" data-ditto-id="style-link-23">
 {" "}
 <font className="inline">
 Bel ons
 </font>
 {" "}
 </font>
 {" "}
 </p>
 {" "}
 <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-ditto-id="style-font-37" data-component="heading">
 <span className="inline">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-div-10" data-component="link" href="tel:31 (0) 33 46 11 447">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline">
 {"+31 (0) 33 46 11 447 "}
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </span>
 {" "}
 </h5>
 {" "}
 <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-ditto-id="style-span-18" data-component="heading" aria-describedby="tooltip842231">
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-p-6" data-component="link" href="tel:31 (0) 33 46 11 447">
 {" "}
 <font className="inline" data-ditto-id="style-link-24">
 {" "}
 <font className="inline" data-ditto-id="style-div-3">
 +31 (0) 6 11 23 88 30
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 <span className="inline" data-ditto-id="style-div-17">
 {" "}
 </span>
 {" "}
 </h5>
 {" "}
 </div>
 {" "}
 <div className="w-[17.8125rem] h-[6.075rem] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] max-md:h-[6.025rem] md:max-lg:w-180 md:max-lg:h-[6.05rem] 2xl:w-82.5" aria-describedby="tooltip941693">
 <p className="block mb-2">
 <font className="inline" data-ditto-id="style-link-25">
 {" "}
 <font className="inline">
 Stuur ons een bericht
 </font>
 {" "}
 </font>
 {" "}
 <br className="inline" />
 {" "}
 </p>
 {" "}
 <h5 className="block mb-2 [font-family:'Work_Sans',_'Odoo_Unicode_Support_Noto',_sans-serif] text-[1.3125rem] font-bold leading-[1.5625rem] max-md:text-xl" data-component="heading">
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-div-18" data-component="link" href="mailto:info@ahneta.nl">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline">
 info@ahneta.nl
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </h5>
 {" "}
 </div>
 {" "}
 <div className="w-[17.8125rem] h-[97.3px] min-h-6 block max-w-full py-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] md:max-lg:w-180 2xl:w-82.5" data-ditto-id="style-avatar">
 <div className="block text-right">
 <p className="block mr-[0.4rem] mb-2 align-middle">
 <font className="inline align-middle">
 {" "}
 <font className="inline align-middle" data-ditto-id="style-span-14">
 Volg ons
 </font>
 {" "}
 </font>
 {" "}
 </p>
 {" "}
 <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-span-21" data-component="link" href="https://www.ahneta.nl/website/social/twitter">
 {" "}
 <i className="flex m-1 justify-center items-center [font-family:FontAwesome-twitter-x-only] leading-4 before:content-[''] before:block before:w-4 before:h-4 before:text-primary before:text-base before:leading-4 before:text-right">
 ​
 </i>
 {" "}
 </a>
 {" "}
 <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-span-19" data-component="link" href="https://www.ahneta.nl/website/social/linkedin">
 {" "}
 <i className="flex m-1 justify-center items-center [font-family:FontAwesome] leading-4 before:content-[''] before:block before:w-[13.7px] before:h-4 before:text-primary before:text-base before:leading-4 before:text-right" aria-describedby="tooltip290654">
 ​
 </i>
 {" "}
 </a>
 {" "}
 <a className="h-6 inline-block m-[0.2rem] align-middle text-primary cursor-pointer" data-ditto-id="style-section-3" data-component="link" href="https://www.ahneta.nl/website/social/instagram">
 {" "}
 <i className="flex m-1 justify-center items-center [font-family:FontAwesome] leading-4 before:content-[''] before:block before:w-[13.7px] before:h-4 before:text-primary before:text-base before:leading-4 before:text-right">
 ​
 </i>
 {" "}
 </a>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative" data-ditto-id="style-div-19">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 ">
 <div className="block py-4 leading-0">
 <hr className="h-px border-t border-solid border-t-muted-foreground block overflow-hidden mx-auto w-[69.375rem] max-md:w-[21.5625rem] md:max-lg:w-[43.125rem] 2xl:w-[80.625rem]" data-ditto-id="style-br-19" />
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 <section className="block relative">
 <div className="block relative max-w-285 mx-auto px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 ">
 <div className="flex -mx-[0.9375rem] flex-wrap items-center" aria-describedby="tooltip859185">
 <div className="w-47.5 h-10 min-h-6 block max-w-full pb-4 px-[0.9375rem] shrink-0 max-md:w-[23.4375rem] md:max-lg:w-180 2xl:w-55 2xl:h-[116.9px]" data-ditto-id="style-myquotecarousel617108">
 <Link className="inline text-primary cursor-pointer" data-component="link" href="/">
 {" "}
 <img className="w-0 h-px min-h-px inline max-w-full overflow-clip align-middle 2xl:w-47.5 2xl:h-[6.3125rem] 2xl:min-h-0" data-ditto-id="style-li-9" data-component="image" alt="" aria-label="Şirketim logosu" role="img" src="/assets/cloned/images/1461683c0d67.png" title="Benim şirketim" />
 {" "}
 </Link>
 {" "}
 </div>
 {" "}
 <div className="w-237.5 h-10 min-h-6 block max-w-full pb-4 px-[0.9375rem] shrink-0 text-right max-md:w-[23.4375rem] max-md:h-16 md:max-lg:w-180 2xl:w-275" data-ditto-id="style-li-10" aria-describedby="tooltip611099">
 <ul className="h-full block [list-style-type:none] list-outside" aria-describedby="tooltip612522">
 <li className="inline-block mr-2" data-ditto-id="style-footer-2">
 {" "}
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-section-4" data-component="link" href="/">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline">
 Home
 </font>
 {" "}
 </font>
 {" "}
 </Link>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-div-20">
 {" "}
 <font className="inline" data-ditto-id="style-p-5">
 {" "}
 <font className="inline">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block mr-2">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-br-20" data-component="link" href="#">
 {" "}
 <font className="inline" data-ditto-id="style-heading-4">
 {" "}
 <font className="inline">
 Over ons
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </li>
 <li className="inline-block mr-2">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block mr-2">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-font-38" data-component="link" href="#">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline" aria-describedby="tooltip841579">
 Product
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </li>
 <li className="inline-block mr-2" data-ditto-id="style-link-26">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block mr-2">
 {" "}
 <a className="inline text-primary cursor-pointer" data-ditto-id="style-link-27" data-component="link" href="#">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline" aria-describedby="tooltip455312">
 Gebruiksvoorwaarden
 </font>
 {" "}
 </font>
 {" "}
 </a>
 {" "}
 </li>
 <li className="inline-block mr-2">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline">
 •
 </font>
 {" "}
 </font>
 {" "}
 </li>
 <li className="inline-block">
 {" "}
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-font-39" data-component="link" aria-describedby="tooltip848069" href="/privacy">
 {" "}
 <font className="inline">
 {" "}
 <font className="inline">
 Privacybeleid
 </font>
 {" "}
 </font>
 {" "}
 </Link>
 {" "}
 </li>
 </ul>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </section>
 {" "}
 </div>
 {" "}
 <div className="block bg-color-005" data-ditto-id="style-link-28">
 <div className="block max-w-285 mx-auto py-4 px-[0.9375rem] max-md:max-w-none md:max-lg:max-w-180 2xl:max-w-330 ">
 <div className="flex -mx-[0.9375rem] flex-wrap">
 <div className="w-full block max-w-full px-[0.9375rem] grow shrink-0 basis-[0%] text-color-003 text-left max-md:text-center max-md:grow-[initial] max-md:basis-[initial]">
 <span className="inline align-middle">
 Copyright © Ahneta Advies
 </span>
 {" "}
 <p className="block mb-4">
 <Link className="inline text-primary cursor-pointer" data-ditto-id="style-font-40" data-component="link" href="/cookie-policy">
 Cookiebeleid
 </Link>
 </p>
 </div>
 {" "}
 <div className="w-142.5 block max-w-full my-[1.3125rem] px-[0.9375rem] grow shrink-0 basis-[0%] text-right max-md:w-[23.4375rem] max-md:text-center max-md:my-0 max-md:grow-[initial] max-md:basis-[initial] md:max-lg:w-90 md:max-lg:my-[0.5625rem] 2xl:w-165">
 <div className="h-full block" data-ditto-id="style-link-29">
 {" "}
 <a className="text-color-003 cursor-pointer hover:underline" href="https://imora.nl" target="_blank" rel="noopener noreferrer">
 Maintained by Imora
 </a>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </div>
 {" "}
 </footer>
 {" "}
 <div className="block shrink-0" data-ditto-id="style-link-31" id="website_cookies_bar">
 {" "}
 </div>
 {" "}
 {" "}
 <div className="block">
 <div className="block" />
 <div className="block" />
 <div className="w-78 h-0 block absolute top-[52.9px] left-240 z-1055 max-md:left-[3.4375rem] md:max-lg:left-112 2xl:left-400" />
 <div className="w-78 h-0 block absolute top-[52.9px] left-240 z-1055 max-md:left-[3.4375rem] md:max-lg:left-112 2xl:left-400" />
 </div>
 </>
 );
}
